### ISSUE TITLE
Got stuck running horovod

### ISSUE THREAD

**Issue by fdas3213** [horovod/horovod#1169]
**Environment:**
1. Tensorflow-gpu: 1.11.0
2. Horovod version: newest? Just installed Horovod using `pip install horovod`
4. MPI version: Open MPI 4.0.0
5. CUDA version: 9.0
6. NCCL version: 2.4.7
7. Python version: 3.6
8. OS and version: Ubuntu 16.04
9. GCC version: 5.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes, but not helpful.

**Your question:**
I want to test horovod using Tensorflow for a image classification task. I am using AWS ec2 p3.2xlarge instance, which is a V100 gpu. When I run my script without Horovod, it works all well. However, when I added horovod and use `horovod run -np 1 -H localhost:1 python train_horovod.py`, it just got stuck. Nothing showed up; there's no error, no warning, nothing. Could anyone help me identify this problem? Thank you.

I then cloned Horovod github page to try to run tensorflow_mnist.py example to see if the problem is with my code. However, when I run tensorflow_mnist.py, it also got stuck. Nothing is showing up, and when I run `nvidia-smi`, memory and gpu is not used at all. So I guess horovod did not even run. Can anyone please help me identify the issue? Thank you.

**Comment by fdas3213** [comment]
Nevermind, I just fixed this problem. It seems that I need to install horovod using the GPU way listed here: https://github.com/horovod/horovod/blob/master/docs/gpus.rst.
