### ISSUE TITLE
mpirun hangs with no output on localhost

### ISSUE THREAD

**Issue by aellaboudy** [horovod/horovod#125]
I'm running on an Ubuntu server with 8 K80 GPUs. Everything is done locally but mpirun seems to hang with no output. After some debugging, it looks like the call to hvd.init() is hanging. Here's the command I'm running from the examples folder:

mpirun -bind-to none -np 8 -map-by slot -H localhost:8 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH python tensorflow_mnist.py

I've verified that NCCL 2.1 and OpenMPI 3.0.0 were installed correctly by running tests from https://github.com/NVIDIA/nccl-tests. They run successfully on all 8 GPUs.

I'm using CUDA 8 with cuDNN 6 and Tensorflow 1.4. I've tried the --mca btl_tcp_if_exclude for different combinations of network interfaces (I only have lo and ens3), but no dice.

**Comment by alsrgv** [comment]
@aellaboudy, does `ssh` ask you to add a new entry to `known_hosts`? E.g.:

```
$ ssh localhost
The authenticity of host 'localhost (127.0.0.1)' can't be established.
RSA key fingerprint is ....
Are you sure you want to continue connecting (yes/no)?
```

If so, can you try to accept and retry `mpirun ... tensorflow_mnist.py`?

**Comment by aellaboudy** [comment]
I tried to ssh into localhost and it asked for confirmation. I typed "yes" and I'm now able to ssh into localhost. I re-tried the mpirun command but it still hangs.

**Comment by alsrgv** [comment]
@aellaboudy, can you try to do the same with:
```
$ ssh `hostname`
...
yes
```

**Comment by aellaboudy** [comment]
Just tried it, same result. ssh asked me to verify, I typed yes, but mpirun still hangs.

**Comment by alsrgv** [comment]
Gotcha. Can you try to make a gist with an output of `strace ... mpirun ...` like in [this comment](https://github.com/uber/horovod/issues/110#issuecomment-347737251)

**Comment by aellaboudy** [comment]
Seems like it's looping indefinitely and I had to Ctrl-C to stop the output. Here's the output txt file compressed.
[hang.txt.zip](https://github.com/uber/horovod/files/1576871/hang.txt.zip)

**Comment by aellaboudy** [comment]
By adding some print statements, I've confirmed that the hang always happens on the call to hvd.init().

**Comment by alsrgv** [comment]
@aellaboudy, I see that you have this line in your log:
```
open("/usr/lib/libmpi_cxx.so", O_RDONLY|O_CLOEXEC) = 3
```
At the same time, it appears that you have installed OpenMPI into `/usr/local/openmpi`.

Do you happen to have two version of MPI installed in your system?  You can check by doing `find /usr | grep mpi`.

**Comment by aellaboudy** [comment]
Hmm...I'm running a Amazon EC2 deep learning instance, so it might be that OpenMPI was already installed in a different location. When I did the manual install I placed it in /usr/local, but I see from the find command that there is also native OpenMPI libraries is /usr/lib and /usr/include.

**Comment by alsrgv** [comment]
@aellaboudy, that may be tripping you up. Can you do:
```
$ pip uninstall -y horovod
$ export PATH=/usr/local/openmpi/bin:$PATH
$ HOROVOD_GPU_ALLREDUCE=NCCL pip install horovod
$ mpirun --prefix=/usr/local/openmpi -bind-to none -np 8 -map-by slot -H localhost:8 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH python tensorflow_mnist.py
```

**Comment by aellaboudy** [comment]
mpirun has no prefix option:

mpirun: Error: unknown option "--prefix=/usr/local/openmpi"
Type 'mpirun --help' for usage.

**Comment by alsrgv** [comment]
Oh, sorry, `mpirun --prefix /usr/local/openmpi -bind-to none -np 8 -map-by slot -H localhost:8 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH python tensorflow_mnist.py`

**Comment by aellaboudy** [comment]
I uninstalled the other versions of openmpi using "sudo make uninstall" in the openmpi directory on my computer and then made sure that only one installation existed in /usr/local/openmpi, then followed your command line instructions. I'm seeing the same hang on hvd.init().

I actually see that /usr/lib/libmpi_cxx.so still exists after the re-installation, but this file is just a symbolic link to the libraries in /usr/local/openmpi/. Same for all the OpenMPI files in /usr/lib and /usr/bin, they're just symbolic links to the actual installation in /usr/local/openmpi.

ompi_info -V shows the correct version, 3.0.0.

**Comment by alsrgv** [comment]
@aellaboudy, ok, good that we ruled that issue out. Can you try doing mpirun with just two processes?

Another observation from your strace is that one of the processes was still doing some python initalization when you interrupted the script:
```
[pid  9116] open("/usr/local/lib/python2.7/dist-packages/pandas/util/warningsmodule.so", O_RDONLY <unfinished ...>
```

How long did you wait before you Ctrl+C'ed it?

**Comment by aellaboudy** [comment]
I Ctrl+C'ed it about 20 seconds in.

**Comment by alsrgv** [comment]
Can you do `strace` with 2 processes, and if it hangs, wait for ~5 min before terminating it?

**Comment by aellaboudy** [comment]
Ok i'll try that.

**Comment by aellaboudy** [comment]
Here's the new strace output with just two processes after 5 minutes of hang.

[hang2.txt.zip](https://github.com/uber/horovod/files/1580903/hang2.txt.zip)

**Comment by alsrgv** [comment]
Can you also do `gdb -p <pid> -ex "thread apply all bt" --batch` for one of the processes that will be spawned (you can check pid with `nvidia-smi`)?

**Comment by aellaboudy** [comment]
So I opened a separate tmux session to start the job and monitor the pid through nvidia-smi and it seems like it works now and doesn't hang, but only if started in a separate tmux session....weird.

**Comment by alsrgv** [comment]
Strange. What if you don't use tmux at all, does it work?

**Comment by gururao001** [comment]
@aellaboudy Where you able to resolve this issue? @alsrgv I am having the same trouble

**Comment by alsrgv** [comment]
Closing due to lack of activity.  Going forward, `horovodrun` is a preferred way to run Horovod, while `mpirun` should be reserved for advanced use cases.

**Comment by CuriousCat-7** [comment]
> Strange. What if you don't use tmux at all, does it work?

Hi, I in my case, I solve this problem by uninstalling horovod, updating openmpi and installing horovod again. I think the old openmpi version made you install a not so good horovod.
