### ISSUE TITLE
Error in run multiple node

### ISSUE THREAD

**Issue by PlusWayne** [horovod/horovod#1363]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: 2.0rc
3. Horovod version:  0.18.0
4. MPI version: 4.0.1
5. CUDA version: 10.0
6. NCCL version:
7. Python version: 3.6.5
8. OS and version: linux
9. GCC version: 7.3.1

**Your question:**
Please ask your question here.

Hi, i am running the example `tensorflow2_keras_mnist.py` using tensorflow 2 and horovod.
the command line is ` horovodrun --verbose -np 4 -H 100.102.32.179:2,100.102.33.44:2 python tensorflow2_keras_mnist.py`. However, error occures, the log is as follows.
```
horovodrun --verbose -np 4 -H 100.102.32.179:2,100.102.33.44:2 python tensorflow2_keras_mnist.py
Filtering local host names.
Remote host found: 100.102.32.179
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Interfaces on all the hosts were successfully checked.
Common interface found: eth1
Checking whether extension tensorflow was built with MPI.
Extension tensorflow was built with MPI.
mpirun --allow-run-as-root --tag-output -np 4 -H 100.102.32.179:2,100.102.33.44:2 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib  -mca btl_tcp_if_include eth1 -x NCCL_SOCKET_IFNAME=eth1 -x MANPATH -x XDG_SESSION_ID -x HOSTNAME -x TERM -x SHELL -x HISTSIZE -x TMPDIR -x SSH_CLIENT -x PERL5LIB -x HADOOP_PREFIX -x JAVACONFDIRS -x SSH_TTY -x LC_ALL -x QT_GRAPHICSSYSTEM_CHECKED -x http_proxy -x PCP_DIR -x JRE_HOME -x USER -x TEMP -x LD_LIBRARY_PATH -x LS_COLORS -x SSH_GLOBAL_ONION_INFOMATION -x XDG_CONFIG_DIRS -x MAIL -x PATH -x PWD -x JAVA_HOME -x HADOOP_CLASSPATH -x TST_HACK_BASH_SESSION_ID -x HADOOP_CONF_DIR -x LANG -x HADOOP_USER_NAME -x PS1 -x https_proxy -x HISTCONTROL -x SHLVL -x HOME -x PYTHONPATH -x TMP -x LOGNAME -x CVS_RSH -x XDG_DATA_DIRS -x CLASSPATH -x SSH_CONNECTION -x LESSOPEN -x PROMPT_COMMAND -x INFOPATH -x XDG_RUNTIME_DIR -x _ -x HOROVOD_FUSION_THRESHOLD -x HOROVOD_CYCLE_TIME -x HOROVOD_CACHE_CAPACITY -x HOROVOD_HIERARCHICAL_ALLREDUCE -x HOROVOD_HIERARCHICAL_ALLGATHER -x HOROVOD_STALL_CHECK_DISABLE -x HOROVOD_STALL_CHECK_TIME_SECONDS -x HOROVOD_STALL_SHUTDOWN_TIME_SECONDS -x HOROVOD_MPI_THREADS_DISABLE -x HOROVOD_NUM_NCCL_STREAMS -x HOROVOD_MLSL_BGT_AFFINITY python tensorflow2_keras_mnist.py
[TENCENT64.site:02628] Warning: could not find environment variable "PS1"
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[34405,1],2]) is on host: XX64
  Process 2 ([[34405,1],0]) is on host: XX64
  BTLs attempted: self vader tcp

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
[1,2]<stderr>:Error in MPI_Isend(140110828931088, 1, 0x7f6ebf83b500, 0, -27, 140113636234944) (-12)
[1,2]<stderr>:Error in NBC_Start_round() (-12)
[1,2]<stderr>:Error in NBC_Start_round() (-1)
 An error occurred in MPI_Comm_dup
 reported by process [2254766081,2]
on communicator MPI_COMM_WORLD
 MPI_ERR_OTHER: known error not in list
MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
    and potentially your MPI job)
```

By the way, i can run when i use `horovodrun --verbose -np 2 -H localhost:2 python tensorflow2_keras_mnist.py`. But it fails with multiple nodes.

**Comment by abditag2** [comment]
Does this happen with other examples as well or just tf2 example?

**Comment by PlusWayne** [comment]
> Does this happen with other examples as well or just tf2 example?
> […](#)
> On Thu, Aug 29, 2019, 12:59 AM PlusWayne ***@***.***> wrote: *Environment:* 1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow 2. Framework version: 2.0rc 3. Horovod version: 0.18.0 4. MPI version: 4.0.1 5. CUDA version: 10.0 6. NCCL version: 7. Python version: 3.6.5 8. OS and version: linux 9. GCC version: 7.3.1 *Checklist:* 1. Did you search issues to find if somebody asked this question before? 2. If your question is about hang, did you read this doc <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_horovod_horovod_blob_master_docs_running.rst&d=DwMFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=RSeJ4a5w_WS1RIZ-J1O_c1MwJ8ReRE0mJ8QAjJ6-xlQ&e=> ? 3. If your question is about docker, did you read this doc <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_horovod_horovod_blob_master_docs_docker.rst&d=DwMFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=TOaPM9iaC5Ub-9B9TmchdF5cH7G4bQyE7PvTHINDvbU&e=> ? 4. Did you check if you question is answered in the troubleshooting guide <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_horovod_horovod_blob_master_docs_troubleshooting.rst&d=DwMFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=GABaSUTiWJ3gtLHEhGRDGw5uHuK6GoCH0ypbK8GdPr0&e=> ? *Your question:* Please ask your question here. Hi, i am running the example tensorflow2_keras_mnist.py <https://urldefense.proofpoint.com/v2/url?u=http-3A__tensorflow2-5Fkeras-5Fmnist.py&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=bHtcfqvXo76-Tp_JKLmOUm0xOtTqhOxXN4z2ebvxmQ0&e=> using tensorflow 2 and horovod. the command line is horovodrun --verbose -np 4 -H 100.102.32.179 <https://urldefense.proofpoint.com/v2/url?u=http-3A__100.102.32.179&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=appPGosP9G5cR2Z6mOYfxOlZ7B7sY34qsDTNmNnLmGM&e=> :2,100.102.33.44 <https://urldefense.proofpoint.com/v2/url?u=http-3A__100.102.33.44&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=91MfmpEO6dbGjq_oMRl0ZKv_u295IobNMtikEJSSZdQ&e=>:2 python tensorflow2_keras_mnist.py <https://urldefense.proofpoint.com/v2/url?u=http-3A__tensorflow2-5Fkeras-5Fmnist.py&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=bHtcfqvXo76-Tp_JKLmOUm0xOtTqhOxXN4z2ebvxmQ0&e=>. However, error occures, the log is as follows. horovodrun --verbose -np 4 -H 100.102.32.179 <https://urldefense.proofpoint.com/v2/url?u=http-3A__100.102.32.179&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=appPGosP9G5cR2Z6mOYfxOlZ7B7sY34qsDTNmNnLmGM&e=> :2,100.102.33.44 <https://urldefense.proofpoint.com/v2/url?u=http-3A__100.102.33.44&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=91MfmpEO6dbGjq_oMRl0ZKv_u295IobNMtikEJSSZdQ&e=>:2 python tensorflow2_keras_mnist.py <https://urldefense.proofpoint.com/v2/url?u=http-3A__tensorflow2-5Fkeras-5Fmnist.py&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=bHtcfqvXo76-Tp_JKLmOUm0xOtTqhOxXN4z2ebvxmQ0&e=> Filtering local host names. Remote host found: 100.102.32.179 <https://urldefense.proofpoint.com/v2/url?u=http-3A__100.102.32.179&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=appPGosP9G5cR2Z6mOYfxOlZ7B7sY34qsDTNmNnLmGM&e=> Checking ssh on all remote hosts. SSH was successful into all the remote hosts. Testing interfaces on all the hosts. Interfaces on all the hosts were successfully checked. Common interface found: eth1 Checking whether extension tensorflow was built with MPI. Extension tensorflow was built with MPI. mpirun --allow-run-as-root --tag-output -np 4 -H 100.102.32.179 <https://urldefense.proofpoint.com/v2/url?u=http-3A__100.102.32.179&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=appPGosP9G5cR2Z6mOYfxOlZ7B7sY34qsDTNmNnLmGM&e=> :2,100.102.33.44 <https://urldefense.proofpoint.com/v2/url?u=http-3A__100.102.33.44&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=91MfmpEO6dbGjq_oMRl0ZKv_u295IobNMtikEJSSZdQ&e=>:2 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_include eth1 -x NCCL_SOCKET_IFNAME=eth1 -x MANPATH -x XDG_SESSION_ID -x HOSTNAME -x TERM -x SHELL -x HISTSIZE -x TMPDIR -x SSH_CLIENT -x PERL5LIB -x HADOOP_PREFIX -x JAVACONFDIRS -x SSH_TTY -x LC_ALL -x QT_GRAPHICSSYSTEM_CHECKED -x http_proxy -x PCP_DIR -x JRE_HOME -x USER -x TEMP -x LD_LIBRARY_PATH -x LS_COLORS -x SSH_GLOBAL_ONION_INFOMATION -x XDG_CONFIG_DIRS -x MAIL -x PATH -x PWD -x JAVA_HOME -x HADOOP_CLASSPATH -x TST_HACK_BASH_SESSION_ID -x HADOOP_CONF_DIR -x LANG -x HADOOP_USER_NAME -x PS1 -x https_proxy -x HISTCONTROL -x SHLVL -x HOME -x PYTHONPATH -x TMP -x LOGNAME -x CVS_RSH -x XDG_DATA_DIRS -x CLASSPATH -x SSH_CONNECTION -x LESSOPEN -x PROMPT_COMMAND -x INFOPATH -x XDG_RUNTIME_DIR -x _ -x HOROVOD_FUSION_THRESHOLD -x HOROVOD_CYCLE_TIME -x HOROVOD_CACHE_CAPACITY -x HOROVOD_HIERARCHICAL_ALLREDUCE -x HOROVOD_HIERARCHICAL_ALLGATHER -x HOROVOD_STALL_CHECK_DISABLE -x HOROVOD_STALL_CHECK_TIME_SECONDS -x HOROVOD_STALL_SHUTDOWN_TIME_SECONDS -x HOROVOD_MPI_THREADS_DISABLE -x HOROVOD_NUM_NCCL_STREAMS -x HOROVOD_MLSL_BGT_AFFINITY python tensorflow2_keras_mnist.py <https://urldefense.proofpoint.com/v2/url?u=http-3A__tensorflow2-5Fkeras-5Fmnist.py&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=bHtcfqvXo76-Tp_JKLmOUm0xOtTqhOxXN4z2ebvxmQ0&e=> [TENCENT64.site <https://urldefense.proofpoint.com/v2/url?u=http-3A__TENCENT64.site&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=OmC9Flxxie9PCzkEcU70I-c5OJbTd2uR3jaiodtw93s&e=>:02628] Warning: could not find environment variable "PS1" At least one pair of MPI processes are unable to reach each other for MPI communications. This means that no Open MPI device has indicated that it can be used to communicate between these processes. This is an error; Open MPI requires that all MPI processes be able to reach each other. This error can sometimes be the result of forgetting to specify the "self" BTL. Process 1 ([[34405,1],2]) is on host: XX64 Process 2 ([[34405,1],0]) is on host: XX64 BTLs attempted: self vader tcp Your MPI job is now going to abort; sorry. [1,2]:Error in MPI_Isend(140110828931088, 1, 0x7f6ebf83b500, 0, -27, 140113636234944) (-12) [1,2]:Error in NBC_Start_round() (-12) [1,2]:Error in NBC_Start_round() (-1) *** An error occurred in MPI_Comm_dup *** reported by process [2254766081,2] *** on communicator MPI_COMM_WORLD *** MPI_ERR_OTHER: known error not in list *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort, *** and potentially your MPI job) By the way, i can run when i use `horovodrun --verbose -np 2 -H localhost:2 python tensorflow2_keras_mnist.py <[https://urldefense.proofpoint.com/v2/url?u=http-3A__tensorflow2-5Fkeras-5Fmnist.py&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=bHtcfqvXo76-Tp_JKLmOUm0xOtTqhOxXN4z2ebvxmQ0&e=>`](https://urldefense.proofpoint.com/v2/url?u=http-3A__tensorflow2-5Fkeras-5Fmnist.py&d=DwQFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=bHtcfqvXo76-Tp_JKLmOUm0xOtTqhOxXN4z2ebvxmQ0&e=>%60). But it fails with multiple nodes. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_horovod_horovod_issues_1363-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAW4JGXQDWPNEBQFIXRQTS3QG56WJA5CNFSM4IR7DDG2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HID7TXA&d=DwMFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=_pxHfeVxp4odF2K2B--COE5qdIpMZIIq98H7fJk_7WU&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAW4JGQOBK7YL4ZXLEJHNRTQG56WJANCNFSM4IR7DDGQ&d=DwMFaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=Jcn0WXylthWxLPEr38PPjw&m=t9P60BORPAG0MjSk5axM0vI71_YFO2wPjmQmpvfHEB4&s=nBCd90PPCG0n3Pr90Hcn_RFFVAUKWXaHkvz4FJ85dQg&e=> .

Thank you for you help, I finally fixed this issue by reinstall horovod.  
I found that tensorflow 2.0 needs gcc 7.3.1, so hope can update the installation guide.
