### ISSUE TITLE
Multi Machine crush with gloo::IoException

### ISSUE THREAD

**Issue by Marsyyh** [horovod/horovod#1459]
Environment:

Framework: (TensorFlow, Keras, PyTorch, MXNet) PyTorch
Framework version: 1.2.0
Horovod version: Latest
MPI version: (Open MPI) 4.0.2
CUDA version: 9.2
NCCL version: 2.4.7
Python version: 2.7
OS and version: ubuntu 16.04
GCC version: 5.4
Bug report:
After installing Horovod with MPI, when I run the my trainning on multiple machines I get an error. When run on multi-gpus within the same machine it works.

```
HOROVOD_NCCL_IFACE=eno2 horovodrun -np 2 -H localhost:1,10.1.6.52:1 --start-timeout 300 --log-level DEBUG python train_kitti_pillar.py
Tue Oct 22 20:44:33 2019[0]<stdout>:[2019-10-22 20:44:33.124735: D horovod/common/utils/env_parser.cc:106] Using GLOO to perform controller operations.
Tue Oct 22 20:44:33 2019[0]<stdout>:[2019-10-22 20:44:33.124842: D horovod/common/utils/env_parser.cc:72] Using GLOO to perform CPU operations.
Tue Oct 22 20:44:33 2019[0]<stdout>:[2019-10-22 20:44:33.124875: D horovod/common/gloo/gloo_context.h:45] Gloo context enabled.
Tue Oct 22 20:44:33 2019[0]<stdout>:[2019-10-22 20:44:33.124885: D horovod/common/gloo/gloo_controller.h:33] GLOO Controller Initialized.
Tue Oct 22 20:44:33 2019[0]<stdout>:[2019-10-22 20:44:33.130682: D horovod/common/gloo/gloo_context.cc:123] rendezvous server address: 10.1.6.54
Tue Oct 22 20:44:33 2019[0]<stdout>:[2019-10-22 20:44:33.130754: D horovod/common/gloo/gloo_context.cc:60] global_ rendezvous started for rank=0, size=2
Tue Oct 22 20:44:33 2019[1]<stdout>:[2019-10-22 20:44:34. 24657: D horovod/common/utils/env_parser.cc:106] Using GLOO to perform controller operations.
Tue Oct 22 20:44:33 2019[1]<stdout>:[2019-10-22 20:44:34. 24737: D horovod/common/utils/env_parser.cc:72] Using GLOO to perform CPU operations.
Tue Oct 22 20:44:33 2019[1]<stdout>:[2019-10-22 20:44:34. 24757: D horovod/common/gloo/gloo_context.h:45] Gloo context enabled.
Tue Oct 22 20:44:34 2019[1]<stdout>:[2019-10-22 20:44:34. 31799: D horovod/common/gloo/gloo_context.cc:138] rendezvous server address: 10.1.6.54
Tue Oct 22 20:44:34 2019[1]<stdout>:[2019-10-22 20:44:34. 31934: D horovod/common/gloo/gloo_context.cc:68] global_ rendezvous started for rank=1, size=2, dev={tcp, pci=0000:01:00.1, iface=eno2, speed=1000, addr=[10.1.6.52]}
Tue Oct 22 20:44:34 2019[0]<stdout>:[2019-10-22 20:44:34. 12159: D horovod/common/gloo/gloo_context.cc:131] Global Gloo context initialized.
Tue Oct 22 20:44:34 2019[0]<stdout>:[2019-10-22 20:44:34. 12240: D horovod/common/gloo/gloo_context.cc:60] local_ rendezvous started for rank=0, size=1
Tue Oct 22 20:44:34 2019[1]<stdout>:[2019-10-22 20:44:34. 43402: D horovod/common/gloo/gloo_context.cc:146] Global Gloo context initialized.
Tue Oct 22 20:44:34 2019[1]<stdout>:[2019-10-22 20:44:34. 43537: D horovod/common/gloo/gloo_context.cc:68] local_1 rendezvous started for rank=0, size=1, dev={tcp, pci=0000:01:00.1, iface=eno2, speed=1000, addr=[10.1.6.52]}
Tue Oct 22 20:44:34 2019[0]<stdout>:[2019-10-22 20:44:34. 14882: D horovod/common/gloo/gloo_context.cc:136] Local Gloo context initialized.
Tue Oct 22 20:44:34 2019[0]<stdout>:[2019-10-22 20:44:34. 14942: D horovod/common/gloo/gloo_context.cc:60] cross_ rendezvous started for rank=0, size=2
Tue Oct 22 20:44:34 2019[1]<stdout>:[2019-10-22 20:44:34. 45794: D horovod/common/gloo/gloo_context.cc:151] Local Gloo context initialized.
Tue Oct 22 20:44:34 2019[1]<stdout>:[2019-10-22 20:44:34. 45914: D horovod/common/gloo/gloo_context.cc:68] cross_0 rendezvous started for rank=1, size=2, dev={tcp, pci=0000:01:00.1, iface=eno2, speed=1000, addr=[10.1.6.52]}
Tue Oct 22 20:45:05 2019[1]<stderr>:terminate called after throwing an instance of 'gloo::IoException'
Tue Oct 22 20:45:05 2019[1]<stderr>:  what():  [horovod/common/gloo/http_store.cc:53] [horovod/common/gloo/http_store.cc:53] Wait timeout for key(s): 0
Tue Oct 22 20:45:05 2019[0]<stderr>:terminate called after throwing an instance of 'gloo::IoException'
Tue Oct 22 20:45:05 2019[0]<stderr>:  what():  [horovod/common/gloo/http_store.cc:53] [horovod/common/gloo/http_store.cc:53] Wait timeout for key(s): 1
```

**Comment by tgaddair** [comment]
Hey @Marsyyh, looks like MPI + Horovod didn't install correctly.  If you want to use MPI, you can try reinstalling Horovod with `HOROVOD_WITH_MPI=1 ... pip install --no-cache-dir horovod`, which will force Horovod to raise an error if MPI can't be installed.  Then you can post the error message here and we can help you debug it.

If you're okay using Gloo instead of MPI (performance should be the same), then you can install from master (v0.18.1 has a bug with multi-machine training when using Gloo): `... pip install --no-cache-dir git+https://github.com/horovod/horovod.git`.

**Comment by Marsyyh** [comment]
@tgaddair Thanks for the Guilding. This is solved by reinstall horovod on both machines with `HOROVOD_WITH_MPI=1 HOROVOD_GPU_ALLREDUCE=NCCL sudo pip install --no-cache-dir horovod` since I'm using MPI + Horovod
