### ISSUE TITLE
seemingly not using gpus though they are available

### ISSUE THREAD

**Issue by zdgithub** [horovod/horovod#1518]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) tensorflow-gpu
2. Framework version: 1.12.0
3. Horovod version: 0.18.1
4. MPI version: 4.0.0
5. CUDA version: 10.0
6. NCCL version: 2.4.8
7. Python version: 3.6
8. OS and version: Ubuntu18.04
9. GCC version: 4.8.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
I try to run the example keras_mnist.py: `horovodrun -np 3 -H localhost:3 python keras_mnist.py`, 
```
[1,1]<stderr>:2019-11-17 17:28:47.301238: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
[1,2]<stderr>:2019-11-17 17:28:47.301520: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
[1,0]<stderr>:2019-11-17 17:28:47.301802: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
[1,2]<stderr>:2019-11-17 17:28:47.310173: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[1,1]<stderr>:2019-11-17 17:28:47.310527: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[1,0]<stderr>:2019-11-17 17:28:47.324847: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[1,0]<stdout>:x_train shape: (60000, 28, 28, 1)
[1,0]<stdout>:60000 train samples
[1,0]<stdout>:10000 test samples
[1,2]<stdout>:x_train shape: (60000, 28, 28, 1)
[1,2]<stdout>:60000 train samples
[1,2]<stdout>:10000 test samples
[1,1]<stdout>:x_train shape: (60000, 28, 28, 1)
[1,1]<stdout>:60000 train samples
[1,1]<stdout>:10000 test samples
[1,0]<stdout>:Train on 60000 samples, validate on 10000 samples
[1,0]<stdout>:Epoch 1/4
[1,0]<stdout>:60000/60000 [==============================] - 91s 2ms/step - loss: 0.1945 - acc: 0.9407 - val_loss: 0.0369 - val_acc: 0.9879
```
It seems to be working well. But when I run `nvidia-smi` to watch the use ratio of gpus, I get the following result:
```
|   0  GeForce RTX 208...  Off  | 00000000:03:00.0  On |                  N/A |
| 23%   42C    P8    10W / 250W |     11MiB / 10988MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:04:00.0 Off |                  N/A |
| 22%   39C    P8    12W / 250W |      1MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:81:00.0 Off |                  N/A |
| 22%   39C    P8     6W / 250W |      1MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:82:00.0 Off |                  N/A |
| 22%   36C    P8     2W / 250W |      1MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```
I'm confused why none of the gpus are occupied or maybe it just uses cpus

**Comment by tgaddair** [comment]
Hey @zdgithub, can you try setting `config.log_device_placement = True` as suggested [here](https://stackoverflow.com/questions/38009682/how-to-tell-if-tensorflow-is-using-gpu-acceleration-from-inside-python-shell) to check that TensorFlow is correctly making use of GPU acceleration?

**Comment by zdgithub** [comment]
> 
> 
> Hey @zdgithub, can you try setting `config.log_device_placement = True` as suggested [here](https://stackoverflow.com/questions/38009682/how-to-tell-if-tensorflow-is-using-gpu-acceleration-from-inside-python-shell) to check that TensorFlow is correctly making use of GPU acceleration?

Thank you! I found it's because my tensorflow-gpu 1.12.0 is too low to use the cuda 10.0.
So when I upgraded the tensorflow-gpu to 1.13.1, the problem was solved.
