### ISSUE TITLE
Question about memory usage for gpus

### ISSUE THREAD

**Issue by hoangcuong2011** [horovod/horovod#1620]
I just wanted to have a quick question about memory usage for gpus.

I have two different machines, one of them has 4 gpus and the another has 8 gpus.

I run the amazing horovod succesfully on the first machine with 4 GPUs (just in case my model is with 80M and I use a batch size of 50 to train the model).

However, give them same model and batch size setting, I could not run horovod on the another machine that has 8 gpus. I got a problem with out of memory.

From technical point of view, why is it the case (using more machines needs more ram memory?) From this [tutorial](http://andrew.gibiansky.com/) about Allreduce I don't think it is the case. Any explanation is more than helpful!

Thank you very much!

**Comment by tgaddair** [comment]
Hey @hoangcuong2011, because Horovod uses a parallel-programming approach to training, every GPU will have a separate worker process that runs a replica of the training script.  As a result, if your training script is using a lot of memory running as a single process (for example, reading the entire dataset into memory), then it will use linearly more memory as you scale the number of GPUs up.

For example, suppose your dataset is 10GB and your training script reads the whole dataset into memory with pandas or similar.  With 4GPUs, you'll read the dataset 4 times costing 40GB of memory, with 8GPUs 8 times for 80GB, etc.

My suspicion is that something like that is the cause of your issue here.  Wherever possible, it's a good idea to try streaming data into your training process as needed as opposed to reading large objects into memory.  In some cases, you may also want to look into using shared memory systems like [Plasma Store](https://arrow.apache.org/docs/python/plasma.html) for large objects if you can't avoid reading the whole thing into memory.

**Comment by hoangcuong2011** [comment]
@tgaddair I think you are right. I just checked carefully. It is all about memories in CPUs that keeps a lot of data or so as you mentioned when we have more GPUs. I thought it was because the memory in GPUs increased significantly when we have more GPUs, but it is indeed not the case.
To fix this issue, I increased the RAM memory from 30Gb to 58GB, and it works well now!

Thank you for your help! This is very interesting to know, from my side (Even though I don't know how large the memory in the machine is for people at Google or Facebook who runs experiments with 1000 GPUs or so. Perhaps you must look into using shared memory systems or so, like you mentioned).

**Comment by tgaddair** [comment]
Hey @hoangcuong2011, glad you got it working.  One thing to point out: when running with 1000 GPUs, those 1000 GPUs will be spread across many hosts, each with their own pool of host memory.  So maybe every host only has 4 GPUs, so as long as you have enough memory per host to read 4x the data of a single process, then you should not get any OOM issues.
