### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError: ncclCommInitRank failed: unhandled system error

### ISSUE THREAD

**Issue by mnmhouse** [horovod/horovod#1651]
##

when i run this commond ：

    mpirun -np 2 -x NCCL_IB_DISABLE=0 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x NCCL_IB_GID_INDEX=5 -x NCCL_IB_HCA=mlx4_0:2 -H 1.0.43.203:1,1.0.123.52:1 --allow-run-as-root   python tensorflow_mnist_estimator.py

log: 

name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:0e:00.0
totalMemory: 23.88GiB freeMemory: 23.55GiB
2020-01-10 09:37:17.419529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu
 devices: 0
2020-01-10 09:37:17.599526: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 wit
h properties:
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:0c:00.0
totalMemory: 23.88GiB freeMemory: 23.71GiB
2020-01-10 09:37:17.599630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu
 devices: 0
2020-01-10 09:37:18.015923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect
 StreamExecutor with strength 1 edge matrix:
2020-01-10 09:37:18.016014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2020-01-10 09:37:18.016041: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2020-01-10 09:37:18.016705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow
 device (/job:localhost/replica:0/task:0/device:GPU:0 with 23000 MB memory) -> physical GPU (device: 0,
 name: Tesla P40, pci bus id: 0000:0c:00.0, compute capability: 6.1)
2020-01-10 09:37:18.019404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect
 StreamExecutor with strength 1 edge matrix:
2020-01-10 09:37:18.019490: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2020-01-10 09:37:18.019515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2020-01-10 09:37:18.019695: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow
 device (/job:localhost/replica:0/task:0/device:GPU:0 with 23013 MB memory) -> physical GPU (device: 0,
 name: Tesla P40, pci bus id: 0000:0e:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from ./mnist_convnet_model/model.ckpt-0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_ses
sion.py:804: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and
will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_ses
sion.py:804: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and
will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into ./mnist_convnet_model/model.ckpt.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpnfiuxaa1/model.ckpt.
ta1-0:2668:2780 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
ta1-0:2668:2780 [0] NCCL INFO NET : Using interface eth0:1.0.123.52<0>
ta1-0:2668:2780 [0] NCCL INFO NET/IB : Using interface eth0 for sideband communication
ta1-0:2668:2780 [0] NCCL INFO NET/IB: [0] mlx4_0:2/RoCE
ta1-0:2668:2780 [0] NCCL INFO Using internal Network IB
ta1-0:2668:2780 [0] NCCL INFO NET : Using interface eth0:1.0.123.52<0>
ta1-0:2668:2780 [0] NCCL INFO NET/Socket : 1 interfaces found
NCCL version 2.3.7+cuda9.0
ta1-0:2668:2780 [0] NCCL INFO rank 0 nranks 2
ta1-1:2712:2824 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
ta1-1:2712:2824 [0] NCCL INFO NET : Using interface eth0:1.0.43.203<0>
ta1-1:2712:2824 [0] NCCL INFO NET/IB : Using interface eth0 for sideband communication
ta1-1:2712:2824 [0] NCCL INFO NET/IB: [0] mlx4_0:2/RoCE
ta1-1:2712:2824 [0] NCCL INFO Using internal Network IB
ta1-1:2712:2824 [0] NCCL INFO rank 1 nranks 2
ta1-1:2712:2824 [0] NCCL INFO comm 0x7fa94834ec90 rank 1 nranks 2
ta1-1:2712:2824 [0] NCCL INFO NET : Using interface eth0:1.0.43.203<0>
ta1-1:2712:2824 [0] NCCL INFO NET/Socket : 1 interfaces found
ta1-0:2668:2780 [0] NCCL INFO comm 0x7f0a88349770 rank 0 nranks 2
ta1-0:2668:2780 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(PHB)
ta1-1:2712:2824 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(PHB)
ta1-0:2668:2780 [0] NCCL INFO Using 256 threads
ta1-0:2668:2780 [0] NCCL INFO Min Comp Cap 6
ta1-0:2668:2780 [0] NCCL INFO Ring 00 :    0   1
ta1-1:2712:2824 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported b
y GPU)
ta1-1:2712:2824 [0] NCCL INFO Ring 00 : 0 -> 1 via NET/IB/0
ta1-0:2668:2780 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported b
y GPU)
ta1-0:2668:2780 [0] NCCL INFO Ring 00 : 1 -> 0 via NET/IB/0
                                                                                                       
ta1-0:2668:2780 [0] misc/ibvwrap.cu:280 NCCL WARN Call to ibv_create_qp failed
ta1-0:2668:2780 [0] NCCL INFO transport/net_ib.cu:371 -> 2
ta1-0:2668:2780 [0] NCCL INFO transport/net_ib.cu:449 -> 2
ta1-0:2668:2780 [0] NCCL INFO include/net.h:25 -> 2
ta1-0:2668:2780 [0] NCCL INFO transport/net.cu:290 -> 2
ta1-0:2668:2780 [0] NCCL INFO init.cu:519 -> 2
ta1-0:2668:2780 [0] NCCL INFO init.cu:593 -> 2
                                                                                                       
ta1-1:2712:2824 [0] misc/ibvwrap.cu:280 NCCL WARN Call to ibv_create_qp failed
ta1-1:2712:2824 [0] NCCL INFO transport/net_ib.cu:371 -> 2
ta1-1:2712:2824 [0] NCCL INFO transport/net_ib.cu:449 -> 2
ta1-1:2712:2824 [0] NCCL INFO include/net.h:25 -> 2
ta1-1:2712:2824 [0] NCCL INFO transport/net.cu:290 -> 2
ta1-1:2712:2824 [0] NCCL INFO init.cu:519 -> 2
ta1-1:2712:2824 [0] NCCL INFO init.cu:593 -> 2
ta1-0:2668:2780 [0] NCCL INFO rank 0 nranks 2
ta1-1:2712:2824 [0] NCCL INFO rank 1 nranks 2
ta1-0:2668:2780 [0] NCCL INFO comm 0x7f0a8834b870 rank 0 nranks 2
ta1-1:2712:2824 [0] NCCL INFO comm 0x7fa94834c010 rank 1 nranks 2
ta1-0:2668:2780 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(PHB)
ta1-1:2712:2824 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(PHB)
ta1-0:2668:2780 [0] NCCL INFO Using 256 threads
ta1-0:2668:2780 [0] NCCL INFO Min Comp Cap 6
ta1-0:2668:2780 [0] NCCL INFO Ring 00 :    0   1
ta1-0:2668:2780 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported b
y GPU)
ta1-1:2712:2824 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported b
y GPU)
ta1-1:2712:2824 [0] NCCL INFO Ring 00 : 0 -> 1 via NET/IB/0
ta1-0:2668:2780 [0] NCCL INFO Ring 00 : 1 -> 0 via NET/IB/0
                                                                                                       
ta1-0:2668:2780 [0] misc/ibvwrap.cu:268 NCCL WARN Call to ibv_create_cq failed
ta1-0:2668:2780 [0] NCCL INFO transport/net_ib.cu:350 -> 2
ta1-0:2668:2780 [0] NCCL INFO transport/net_ib.cu:447 -> 2
ta1-0:2668:2780 [0] NCCL INFO include/net.h:25 -> 2
ta1-0:2668:2780 [0] NCCL INFO transport/net.cu:290 -> 2
ta1-0:2668:2780 [0] NCCL INFO init.cu:519 -> 2
ta1-0:2668:2780 [0] NCCL INFO init.cu:593 -> 2
                                                                                                       
ta1-1:2712:2824 [0] misc/ibvwrap.cu:268 NCCL WARN Call to ibv_create_cq failed
ta1-1:2712:2824 [0] NCCL INFO transport/net_ib.cu:350 -> 2
ta1-1:2712:2824 [0] NCCL INFO transport/net_ib.cu:447 -> 2
ta1-1:2712:2824 [0] NCCL INFO include/net.h:25 -> 2
ta1-1:2712:2824 [0] NCCL INFO transport/net.cu:290 -> 2
ta1-1:2712:2824 [0] NCCL INFO init.cu:519 -> 2
ta1-1:2712:2824 [0] NCCL INFO init.cu:593 -> 2
ta1-0:2668:2780 [0] NCCL INFO rank 0 nranks 2
ta1-0:2668:2780 [0] NCCL INFO comm 0x7f0a8833b010 rank 0 nranks 2
ta1-1:2712:2824 [0] NCCL INFO rank 1 nranks 2
ta1-1:2712:2824 [0] NCCL INFO comm 0x7fa948340010 rank 1 nranks 2
ta1-0:2668:2780 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(PHB)
ta1-1:2712:2824 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(PHB)
ta1-0:2668:2780 [0] NCCL INFO Using 256 threads
ta1-0:2668:2780 [0] NCCL INFO Min Comp Cap 6
ta1-0:2668:2780 [0] NCCL INFO Ring 00 :    0   1
ta1-0:2668:2780 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported b
y GPU)
ta1-1:2712:2824 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported b
y GPU)
ta1-1:2712:2824 [0] NCCL INFO Ring 00 : 0 -> 1 via NET/IB/0
ta1-0:2668:2780 [0] NCCL INFO Ring 00 : 1 -> 0 via NET/IB/0
                                                                                                       
ta1-0:2668:2780 [0] misc/ibvwrap.cu:268 NCCL WARN Call to ibv_create_cq failed
ta1-0:2668:2780 [0] NCCL INFO transport/net_ib.cu:350 -> 2
ta1-0:2668:2780 [0] NCCL INFO transport/net_ib.cu:447 -> 2
ta1-0:2668:2780 [0] NCCL INFO include/net.h:25 -> 2
ta1-0:2668:2780 [0] NCCL INFO transport/net.cu:290 -> 2
ta1-0:2668:2780 [0] NCCL INFO init.cu:519 -> 2
ta1-0:2668:2780 [0] NCCL INFO init.cu:593 -> 2
ta1-0:2668:2780 [0] NCCL INFO rank 0 nranks 2
                                                                                                       
ta1-1:2712:2824 [0] misc/ibvwrap.cu:268 NCCL WARN Call to ibv_create_cq failed
ta1-1:2712:2824 [0] NCCL INFO transport/net_ib.cu:350 -> 2
ta1-1:2712:2824 [0] NCCL INFO transport/net_ib.cu:447 -> 2
ta1-1:2712:2824 [0] NCCL INFO include/net.h:25 -> 2
ta1-1:2712:2824 [0] NCCL INFO transport/net.cu:290 -> 2
ta1-1:2712:2824 [0] NCCL INFO init.cu:519 -> 2
ta1-1:2712:2824 [0] NCCL INFO init.cu:593 -> 2
ta1-0:2668:2780 [0] NCCL INFO comm 0x7f0a8836a010 rank 0 nranks 2
ta1-1:2712:2824 [0] NCCL INFO rank 1 nranks 2
ta1-1:2712:2824 [0] NCCL INFO comm 0x7fa94836d010 rank 1 nranks 2
ta1-1:2712:2824 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(PHB)
ta1-0:2668:2780 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(PHB)
ta1-0:2668:2780 [0] NCCL INFO Using 256 threads
ta1-0:2668:2780 [0] NCCL INFO Min Comp Cap 6
ta1-0:2668:2780 [0] NCCL INFO Ring 00 :    0   1
ta1-0:2668:2780 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported b
y GPU)
ta1-1:2712:2824 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported b
y GPU)
ta1-1:2712:2824 [0] NCCL INFO Ring 00 : 0 -> 1 via NET/IB/0
ta1-0:2668:2780 [0] NCCL INFO Ring 00 : 1 -> 0 via NET/IB/0
                                                                                                       
ta1-0:2668:2780 [0] misc/ibvwrap.cu:268 NCCL WARN Call to ibv_create_cq failed
ta1-0:2668:2780 [0] NCCL INFO transport/net_ib.cu:350 -> 2
ta1-0:2668:2780 [0] NCCL INFO transport/net_ib.cu:447 -> 2
ta1-0:2668:2780 [0] NCCL INFO include/net.h:25 -> 2
ta1-0:2668:2780 [0] NCCL INFO transport/net.cu:290 -> 2
ta1-0:2668:2780 [0] NCCL INFO init.cu:519 -> 2
ta1-0:2668:2780 [0] NCCL INFO init.cu:593 -> 2
                                                                                                       
ta1-1:2712:2824 [0] misc/ibvwrap.cu:268 NCCL WARN Call to ibv_create_cq failed
ta1-1:2712:2824 [0] NCCL INFO transport/net_ib.cu:350 -> 2
ta1-1:2712:2824 [0] NCCL INFO transport/net_ib.cu:447 -> 2
ta1-1:2712:2824 [0] NCCL INFO include/net.h:25 -> 2
ta1-1:2712:2824 [0] NCCL INFO transport/net.cu:290 -> 2
ta1-1:2712:2824 [0] NCCL INFO init.cu:519 -> 2
ta1-1:2712:2824 [0] NCCL INFO init.cu:593 -> 2
ta1-0:2668:2780 [0] NCCL INFO rank 0 nranks 2
ta1-0:2668:2780 [0] NCCL INFO comm 0x7f0a88401010 rank 0 nranks 2
ta1-1:2712:2824 [0] NCCL INFO rank 1 nranks 2
ta1-1:2712:2824 [0] NCCL INFO comm 0x7fa948405010 rank 1 nranks 2
ta1-0:2668:2780 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(PHB)
ta1-1:2712:2824 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(PHB)
ta1-0:2668:2780 [0] NCCL INFO Using 256 threads
ta1-0:2668:2780 [0] NCCL INFO Min Comp Cap 6
ta1-0:2668:2780 [0] NCCL INFO Ring 00 :    0   1
ta1-0:2668:2780 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported b
y GPU)
ta1-1:2712:2824 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported b
y GPU)
ta1-1:2712:2824 [0] NCCL INFO Ring 00 : 0 -> 1 via NET/IB/0
ta1-0:2668:2780 [0] NCCL INFO Ring 00 : 1 -> 0 via NET/IB/0
                                                                                                       
ta1-0:2668:2780 [0] misc/ibvwrap.cu:268 NCCL WARN Call to ibv_create_cq failed
ta1-0:2668:2780 [0] NCCL INFO transport/net_ib.cu:350 -> 2
ta1-0:2668:2780 [0] NCCL INFO transport/net_ib.cu:447 -> 2
ta1-0:2668:2780 [0] NCCL INFO include/net.h:25 -> 2
ta1-0:2668:2780 [0] NCCL INFO transport/net.cu:290 -> 2
ta1-0:2668:2780 [0] NCCL INFO init.cu:519 -> 2
ta1-0:2668:2780 [0] NCCL INFO init.cu:593 -> 2
                                                                                                       
ta1-1:2712:2824 [0] misc/ibvwrap.cu:268 NCCL WARN Call to ibv_create_cq failed
ta1-1:2712:2824 [0] NCCL INFO transport/net_ib.cu:350 -> 2
ta1-1:2712:2824 [0] NCCL INFO transport/net_ib.cu:447 -> 2
ta1-1:2712:2824 [0] NCCL INFO include/net.h:25 -> 2
ta1-1:2712:2824 [0] NCCL INFO transport/net.cu:290 -> 2
ta1-1:2712:2824 [0] NCCL INFO init.cu:519 -> 2
ta1-1:2712:2824 [0] NCCL INFO init.cu:593 -> 2
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_
call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run
_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _cal
l_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: ncclCommInitRank failed: unhandled system error
        [[{{node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad
_tuple_control_dependency_1_0}} = HorovodAllreduce[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:
0/device:GPU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]
                                                                                                       
During handling of the above exception, another exception occurred:
                                                                                                       
Traceback (most recent call last):
  File "tensorflow_mnist_estimator.py", line 218, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist_estimator.py", line 205, in main
    hooks=[bcast_hook])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in
train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in
 _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1241, in
 _train_model_default
    saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1471, in
 _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 6
71, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1
156, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1
255, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1
240, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1
312, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1
076, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_
run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_
call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: ncclCommInitRank failed: unhandled system error
        [[node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_t
uple_control_dependency_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_DOUBLE, _device="/job:loc
alhost/replica:0/task:0/device:GPU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]
                                                                                                       
Caused by op 'DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tu
ple_control_dependency_1_0', defined at:
  File "tensorflow_mnist_estimator.py", line 218, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist_estimator.py", line 205, in main
    hooks=[bcast_hook])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in
train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in
 _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1237, in
 _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in
 _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "tensorflow_mnist_estimator.py", line 122, in cnn_model_fn
    global_step=tf.train.get_global_step())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 400, in m
inimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 256, in compute_gr
adients
    avg_grads = self._allreduce_grads(grads)
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 210, in allreduce_
grads
    for grad in grads]
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 210, in <listcomp>
    for grad in grads]
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 80, in allreduce
    summed_tensor_compressed = _allreduce(tensor_compressed)
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/mpi_ops.py", line 86, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 51, in horovod_allreduce
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787
, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new
_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in creat
e_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __ini
t__
    self._traceback = tf_stack.extract_stack()
                                                                                                       
UnknownError (see above for traceback): ncclCommInitRank failed: unhandled system error
        [[node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_t
uple_control_dependency_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_DOUBLE, _device="/job:loc
alhost/replica:0/task:0/device:GPU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]
                                                                                                       
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_
call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run
_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _cal
l_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: ncclCommInitRank failed: unhandled system error
        [[{{node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad
_tuple_control_dependency_1_0}} = HorovodAllreduce[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:
0/device:GPU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]
                                                                                                       
During handling of the above exception, another exception occurred:
                                                                                                       
Traceback (most recent call last):
  File "tensorflow_mnist_estimator.py", line 218, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist_estimator.py", line 205, in main
    hooks=[bcast_hook])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in
train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in
 _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1241, in
 _train_model_default
    saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1471, in
 _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 6
71, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1
156, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1
255, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1
240, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1
312, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1
076, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_
run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_
call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: ncclCommInitRank failed: unhandled system error
        [[node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_t
uple_control_dependency_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_DOUBLE, _device="/job:loc
alhost/replica:0/task:0/device:GPU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]
                                                                                                       
Caused by op 'DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tu
ple_control_dependency_1_0', defined at:
  File "tensorflow_mnist_estimator.py", line 218, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist_estimator.py", line 205, in main
    hooks=[bcast_hook])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in
train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in
 _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1237, in
 _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in
 _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "tensorflow_mnist_estimator.py", line 122, in cnn_model_fn
    global_step=tf.train.get_global_step())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 400, in m
inimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 256, in compute_gr
adients
    avg_grads = self._allreduce_grads(grads)
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 210, in allreduce_
grads
    for grad in grads]
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 210, in <listcomp>
    for grad in grads]
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 80, in allreduce
    summed_tensor_compressed = _allreduce(tensor_compressed)
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/mpi_ops.py", line 86, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 51, in horovod_allreduce
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787
, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new
_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in creat
e_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __ini
t__
    self._traceback = tf_stack.extract_stack()
                                                                                                       
UnknownError (see above for traceback): ncclCommInitRank failed: unhandled system error
        [[node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_t
uple_control_dependency_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_DOUBLE, _device="/job:loc
alhost/replica:0/task:0/device:GPU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]
                                                                                                       
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
                                                                                                       
  Process name: [[63694,1],1]
  Exit code:    1

Can you give us some advise? Thanks.

**Comment by tgaddair** [comment]
Related to #1195.  @DEKHTIARJonathan or @romerojosh, are you familiar enough with NCCL configuration to help out with this issue?

**Comment by DEKHTIARJonathan** [comment]
I suppose you are using a docker container. If yes, which one?

Could you try with this one :
nvcr.io/nvidia/tensorflow:19.12-tf1-py3

**Comment by apatsekin** [comment]
Got similar error while using keras. Container: nvcr.io/nvidia/tensorflow:20.01-tf1-py3

```
<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "run.py", line 179, in <module>
[1,0]<stderr>:    main(config_var, rerun=args.rerun)
[1,0]<stderr>:  File "run.py", line 170, in main
[1,0]<stderr>:    callbacks=callbacks_)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
[1,0]<stderr>:    return func(*args, **kwargs)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1732, in fit_generator
[1,0]<stderr>:    initial_epoch=initial_epoch)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 220, in fit_generator
[1,0]<stderr>:    reset_metrics=False)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1514, in train_on_batch
[1,0]<stderr>:    outputs = self.train_function(ins)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
[1,0]<stderr>:    run_metadata=self.run_metadata)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
[1,0]<stderr>:    run_metadata_ptr)
[1,0]<stderr>:tensorflow.python.framework.errors_impl.UnknownError: ncclCommInitRank failed: unhandled system error
[1,0]<stderr>:	 [[{{node training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_0}}]]
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "run.py", line 179, in <module>
[1,1]<stderr>:    main(config_var, rerun=args.rerun)
[1,1]<stderr>:  File "run.py", line 170, in main
[1,1]<stderr>:    callbacks=callbacks_)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
[1,1]<stderr>:    return func(*args, **kwargs)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1732, in fit_generator
[1,1]<stderr>:    initial_epoch=initial_epoch)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 220, in fit_generator
[1,1]<stderr>:    reset_metrics=False)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1514, in train_on_batch
[1,1]<stderr>:    outputs = self.train_function(ins)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
[1,1]<stderr>:    run_metadata=self.run_metadata)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
[1,1]<stderr>:    run_metadata_ptr)
[1,1]<stderr>:tensorflow.python.framework.errors_impl.UnknownError: ncclCommInitRank failed: unhandled system error
[1,1]<stderr>:	 [[{{node training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_0}}]]
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "run.py", line 179, in <module>
[1,2]<stderr>:    main(config_var, rerun=args.rerun)
[1,2]<stderr>:  File "run.py", line 170, in main
[1,2]<stderr>:    callbacks=callbacks_)
[1,2]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
[1,2]<stderr>:    return func(*args, **kwargs)
[1,2]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1732, in fit_generator
[1,2]<stderr>:    initial_epoch=initial_epoch)
[1,2]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 220, in fit_generator
[1,2]<stderr>:    reset_metrics=False)
[1,2]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1514, in train_on_batch
[1,2]<stderr>:    outputs = self.train_function(ins)
[1,2]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
[1,2]<stderr>:    run_metadata=self.run_metadata)
[1,2]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
[1,2]<stderr>:    run_metadata_ptr)
[1,2]<stderr>:tensorflow.python.framework.errors_impl.UnknownError: ncclCommInitRank failed: unhandled system error
[1,2]<stderr>:	 [[{{node training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_0}}]]```

**Comment by DEKHTIARJonathan** [comment]
Can you execute `nvidia-smi` inside the container

**Comment by apatsekin** [comment]
@DEKHTIARJonathan 
I run it through `mpirun` directly (instead of horovodrun). And more verbose output gave more context:
```
gpu2-ru7:8678:8991 [0] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
```

It's a kind of confusing to me. Since There are 250 GB free RAM and 500 GB disk space on /. 
```
➜  keras-classifier df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         3.5T  2.8T  546G  84% /
```

I'm getting this error while running tensorflow_mnist.py or keras_mnist examples. It works for 1 GPU, 2 GPU. But fails starting 3+ GPUs.

**Comment by DEKHTIARJonathan** [comment]
Can you try this:

```python
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.7)

sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
```

**Comment by apatsekin** [comment]
Added to https://github.com/horovod/horovod/blob/7d7a9df9ffb77a121030207f1659ec6c9afaa8ed/examples/tensorflow_mnist.py#L151

```
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.per_process_gpu_memory_fraction = 0.7
config.gpu_options.visible_device_list = str(hvd.local_rank())
```
Running:
```
mpirun --allow-run-as-root -np 4  -bind-to none -map-by slot  -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH  -mca pml ob1 -mca btl ^openib python tensorflow_mnist.py
```

Output:
```
gpu2-ru7:5229:5650 [0] NCCL INFO Bootstrap : Using [0]enp96s0f0:10.1.10.6<0> [1]tunl0:192.168.94.0<0> [2]enp96s0f1:fe80::ae1f:6bff:feac:766d%enp96s0f1<0>
gpu2-ru7:5229:5650 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu2-ru7:5229:5650 [0] NCCL INFO NET/IB : No device found.
gpu2-ru7:5229:5650 [0] NCCL INFO NET/Socket : Using [0]enp96s0f0:10.1.10.6<0> [1]tunl0:192.168.94.0<0> [2]enp96s0f1:fe80::ae1f:6bff:feac:766d%enp96s0f1<0>
NCCL version 2.5.6+cuda10.2
gpu2-ru7:5231:5641 [2] NCCL INFO Bootstrap : Using [0]enp96s0f0:10.1.10.6<0> [1]tunl0:192.168.94.0<0> [2]enp96s0f1:fe80::ae1f:6bff:feac:766d%enp96s0f1<0>
gpu2-ru7:5231:5641 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu2-ru7:5231:5641 [2] NCCL INFO NET/IB : No device found.
gpu2-ru7:5231:5641 [2] NCCL INFO NET/Socket : Using [0]enp96s0f0:10.1.10.6<0> [1]tunl0:192.168.94.0<0> [2]enp96s0f1:fe80::ae1f:6bff:feac:766d%enp96s0f1<0>
gpu2-ru7:5230:5642 [1] NCCL INFO Bootstrap : Using [0]enp96s0f0:10.1.10.6<0> [1]tunl0:192.168.94.0<0> [2]enp96s0f1:fe80::ae1f:6bff:feac:766d%enp96s0f1<0>
gpu2-ru7:5232:5647 [3] NCCL INFO Bootstrap : Using [0]enp96s0f0:10.1.10.6<0> [1]tunl0:192.168.94.0<0> [2]enp96s0f1:fe80::ae1f:6bff:feac:766d%enp96s0f1<0>
gpu2-ru7:5232:5647 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu2-ru7:5230:5642 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu2-ru7:5232:5647 [3] NCCL INFO NET/IB : No device found.
gpu2-ru7:5230:5642 [1] NCCL INFO NET/IB : No device found.
gpu2-ru7:5232:5647 [3] NCCL INFO NET/Socket : Using [0]enp96s0f0:10.1.10.6<0> [1]tunl0:192.168.94.0<0> [2]enp96s0f1:fe80::ae1f:6bff:feac:766d%enp96s0f1<0>
gpu2-ru7:5230:5642 [1] NCCL INFO NET/Socket : Using [0]enp96s0f0:10.1.10.6<0> [1]tunl0:192.168.94.0<0> [2]enp96s0f1:fe80::ae1f:6bff:feac:766d%enp96s0f1<0>
gpu2-ru7:5229:5650 [0] NCCL INFO Setting affinity for GPU 0 to 0f,ff000fff
gpu2-ru7:5232:5647 [3] NCCL INFO Setting affinity for GPU 3 to 0f,ff000fff
gpu2-ru7:5230:5642 [1] NCCL INFO Setting affinity for GPU 1 to 0f,ff000fff
gpu2-ru7:5231:5641 [2] NCCL INFO Setting affinity for GPU 2 to 0f,ff000fff
gpu2-ru7:5230:5642 [1] NCCL INFO Could not find real path of /sys/class/net/tunl0/device
gpu2-ru7:5230:5642 [1] NCCL INFO include/net.h:19 -> 2
gpu2-ru7:5229:5650 [0] NCCL INFO Could not find real path of /sys/class/net/tunl0/device
gpu2-ru7:5229:5650 [0] NCCL INFO include/net.h:19 -> 2
gpu2-ru7:5231:5641 [2] NCCL INFO Could not find real path of /sys/class/net/tunl0/device
gpu2-ru7:5231:5641 [2] NCCL INFO include/net.h:19 -> 2
gpu2-ru7:5232:5647 [3] NCCL INFO Could not find real path of /sys/class/net/tunl0/device
gpu2-ru7:5232:5647 [3] NCCL INFO include/net.h:19 -> 2
gpu2-ru7:5229:5650 [0] NCCL INFO Channel 00/02 :    0   1   2   3
gpu2-ru7:5229:5650 [0] NCCL INFO Channel 01/02 :    0   1   2   3
gpu2-ru7:5229:5650 [0] NCCL INFO Threads per block : 512/640/256
gpu2-ru7:5229:5650 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64
gpu2-ru7:5229:5650 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
gpu2-ru7:5231:5641 [2] NCCL INFO Threads per block : 512/640/256
gpu2-ru7:5231:5641 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64
gpu2-ru7:5231:5641 [2] NCCL INFO Trees [0] 3/-1/-1->2->1|1->2->3/-1/-1 [1] 3/-1/-1->2->1|1->2->3/-1/-1
gpu2-ru7:5230:5642 [1] NCCL INFO Threads per block : 512/640/256
gpu2-ru7:5230:5642 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64
gpu2-ru7:5230:5642 [1] NCCL INFO Trees [0] 2/-1/-1->1->0|0->1->2/-1/-1 [1] 2/-1/-1->1->0|0->1->2/-1/-1
gpu2-ru7:5232:5647 [3] NCCL INFO Threads per block : 512/640/256
gpu2-ru7:5232:5647 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64
gpu2-ru7:5232:5647 [3] NCCL INFO Trees [0] -1/-1/-1->3->2|2->3->-1/-1/-1 [1] -1/-1/-1->3->2|2->3->-1/-1/-1
gpu2-ru7:5230:5642 [1] NCCL INFO Ring 00 : 1[1b000] -> 2[3d000] via direct shared memory
gpu2-ru7:5231:5641 [2] NCCL INFO Ring 00 : 2[3d000] -> 3[3e000] via direct shared memory
gpu2-ru7:5229:5650 [0] NCCL INFO Ring 00 : 0[1a000] -> 1[1b000] via direct shared memory
gpu2-ru7:5232:5647 [3] NCCL INFO Ring 00 : 3[3e000] -> 0[1a000] via direct shared memory
gpu2-ru7:5232:5647 [3] NCCL INFO Ring 00 : 3[3e000] -> 2[3d000] via direct shared memory

gpu2-ru7:5229:5650 [0] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
gpu2-ru7:5229:5650 [0] NCCL INFO include/shm.h:41 -> 2

gpu2-ru7:5229:5650 [0] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-c85095781bd2753b-0-1-0 (size 9637888)

gpu2-ru7:5229:5650 [0] NCCL INFO transport/shm.cc:99 -> 2
gpu2-ru7:5229:5650 [0] NCCL INFO init.cc:284 -> 2
gpu2-ru7:5229:5650 [0] NCCL INFO init.cc:395 -> 2
gpu2-ru7:5229:5650 [0] NCCL INFO init.cc:618 -> 2
gpu2-ru7:5229:5650 [0] NCCL INFO init.cc:732 -> 2

gpu2-ru7:5231:5641 [2] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
gpu2-ru7:5231:5641 [2] NCCL INFO include/shm.h:41 -> 2
gpu2-ru7:5229:5650 [0] NCCL INFO init.cc:771 -> 2
gpu2-ru7:5229:5650 [0] NCCL INFO init.cc:782 -> 2
```
Detailed description how to reproduce I left on Stackoverflow: https://stackoverflow.com/questions/39901311/docker-ubuntu-bash-ping-command-not-found

**Comment by DEKHTIARJonathan** [comment]
Remove: config.gpu_options.allow_growth = True
It overwrites memory management restrictions. Shall be avoided in general

**Comment by apatsekin** [comment]
Same error

related snippet of the file:
```
   # Horovod: pin GPU to be used to process local rank (one GPU per process)
    config = tf.ConfigProto()
   # config.gpu_options.allow_growth = True
    config.gpu_options.per_process_gpu_memory_fraction = 0.5
    config.gpu_options.visible_device_list = str(hvd.local_rank())

    # Horovod: save checkpoints only on worker 0 to prevent other workers from
    # corrupting them.
    checkpoint_dir = './checkpoints' if hvd.rank() == 0 else None
    training_batch_generator = train_input_generator(x_train,
                                                     y_train, batch_size=10)
    # The MonitoredTrainingSession takes care of session initialization,
    # restoring from a checkpoint, saving to a checkpoint, and closing when done
    # or an error occurs.
    with tf.train.MonitoredTrainingSession(checkpoint_dir=None,
                                           hooks=hooks,
                                           config=config) as mon_sess:
        while not mon_sess.should_stop():
            # Run a training step synchronously.
            image_, label_ = next(training_batch_generator)
            mon_sess.run(train_op, feed_dict={image: image_, label: label_})
```
I also set checkpoint_dir=None to exclude possible errors while trying to write the disk. But it doesn't help.

**Comment by DEKHTIARJonathan** [comment]
Do you have this server in premise or you rent to AWS or smthg?

**Comment by apatsekin** [comment]
> Do you have this server in premise or you rent to AWS or smthg?

On premises
I tried on another server with most recent CUDA/Nvidia drivers. Same error.

However, everything works fine with nvcr.io/nvidia/tensorflow:**19.10**-py3

**Comment by DEKHTIARJonathan** [comment]
Sorry, can't tell. We don't support servers with non Tesla products. I can't even reproduce your issue.

**Comment by Loquats** [comment]
Hi @DEKHTIARJonathan, I'm running into a similar error. Could you clarify what you mean by not supporting "non Tesla products"?
I'm using horovod on an AWS g4 machine that has four Nvidia T4 GPU's. Do you know whether T4 is supported? (Turing architecture but part of the Tesla product line.)

**Comment by DEKHTIARJonathan** [comment]
@Loquats nvidia does not RTX and GTX cards in a server configuration. It could even violates the terms of the licence agreement (consult lawyers).
T4 are Tesla products and therefore are perfectly supported. However T4 are non suitable for training. So I'm not sure what you try to do with them with horovod.
Could you post your code and error.

**Comment by Loquats** [comment]
Thanks for clarifying. Actually, I found out my error was caused by multiple processes using the same GPU, and fixed it by pinning to the local rank in pytorch `torch.cuda.set_device(hvd.local_rank())`

Could you explain what you mean by T4 not being suitable for training?

**Comment by DEKHTIARJonathan** [comment]
Awesome. T4 GPUs are designed to do inference. Not training. You will get considerably better training performance with any V100 / A100 GPUs.

**Comment by DEKHTIARJonathan** [comment]
@tgaddair can we close this issue?

**Comment by tgaddair** [comment]
One thing I'd point out: though V100s are definitely better for training in terms of raw performance, in a lot of cloud providers t4s tend of offer better performance / dollar (g4dn.12xlarge instances use t4s, and are very reasonably costed, which is why we use them for Horovod's CI).

**Comment by surak** [comment]
> Thanks for clarifying. Actually, I found out my error was caused by multiple processes using the same GPU, and fixed it by pinning to the local rank in pytorch `torch.cuda.set_device(hvd.local_rank())`

Any idea how to do so on tensorflow2? I tried with `tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')`, but I still see the same error.

**Comment by tgaddair** [comment]
Hey @surak, the recommendation for TF2 is to use the form shown [here](https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_mnist.py#L23):

```
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
if gpus:
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
```

If this isn't working for you, then feel free to open a new issue with the specific error you're receiving and we'll take a look.

**Comment by surak** [comment]
> If this isn't working for you, then feel free to open a new issue with the specific error you're receiving and we'll take a look.

The issue is exactly that which is reported here. 

```
salloc --nodes=2 --partition=develgpus --gres=gpu:4
srun  --pty singularity run ./tensorflow_20.08-tf2-py3.sif python ./horovod-tf2-bench.py

                                                                                                                                                
================
== TensorFlow ==
================

NVIDIA Release 20.08-tf2 (build 15413358)
TensorFlow Version 2.2.0

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
Copyright 2017-2020 The TensorFlow Authors.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.
                                                                                                                                                
================
== TensorFlow ==
================

NVIDIA Release 20.08-tf2 (build 15413358)
TensorFlow Version 2.2.0

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
Copyright 2017-2020 The TensorFlow Authors.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .

Detected MOFED 4.7-3.2.9.

Detected MOFED 4.7-3.2.9.


2020-10-15 11:51:20.086417: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-15 11:51:20.090906: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-15 11:51:22.548363: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-10-15 11:51:22.547118: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-10-15 11:51:22.662460: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:5d:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-15 11:51:22.663385: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:5e:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-15 11:51:22.664252: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 2 with properties: 
pciBusID: 0000:88:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-15 11:51:22.665104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 3 with properties: 
pciBusID: 0000:89:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-15 11:51:22.665165: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-15 11:51:22.718118: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-10-15 11:51:22.723042: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:5d:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-15 11:51:22.723978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:5e:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-15 11:51:22.724824: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 2 with properties: 
pciBusID: 0000:88:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-15 11:51:22.725684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 3 with properties: 
pciBusID: 0000:89:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-15 11:51:22.725730: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-15 11:51:22.737704: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-10-15 11:51:22.762137: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-10-15 11:51:22.782093: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-10-15 11:51:22.801643: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-10-15 11:51:22.830698: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-10-15 11:51:22.836132: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-10-15 11:51:22.851208: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-10-15 11:51:22.852483: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-10-15 11:51:22.858932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1, 2, 3
2020-10-15 11:51:22.893992: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2400000000 Hz
2020-10-15 11:51:22.895046: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2ae1a8000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-15 11:51:22.895065: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-15 11:51:22.911140: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-10-15 11:51:22.927479: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-10-15 11:51:22.928766: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-10-15 11:51:22.935256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1, 2, 3
2020-10-15 11:51:22.974746: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2400000000 Hz
2020-10-15 11:51:22.975789: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2b0e68000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-15 11:51:22.975824: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-15 11:51:23.035129: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x42d1430 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-15 11:51:23.035167: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-SXM2-16GB, Compute Capability 7.0
2020-10-15 11:51:23.037939: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:5d:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-15 11:51:23.038001: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-15 11:51:23.038065: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-10-15 11:51:23.038080: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-10-15 11:51:23.038100: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-10-15 11:51:23.038121: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-10-15 11:51:23.038168: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-10-15 11:51:23.038182: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-10-15 11:51:23.039811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-10-15 11:51:23.041449: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-15 11:51:23.126640: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56fb430 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-15 11:51:23.126680: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-SXM2-16GB, Compute Capability 7.0
2020-10-15 11:51:23.129448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:5d:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-15 11:51:23.129494: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-15 11:51:23.129531: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-10-15 11:51:23.129545: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-10-15 11:51:23.129567: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-10-15 11:51:23.129586: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-10-15 11:51:23.129599: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-10-15 11:51:23.129635: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-10-15 11:51:23.131299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-10-15 11:51:23.135089: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-15 11:51:25.881621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-15 11:51:25.881675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-10-15 11:51:25.881689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-10-15 11:51:25.885721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14793 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:5d:00.0, compute capability: 7.0)
2020-10-15 11:51:26.577458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-15 11:51:26.577507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-10-15 11:51:26.577519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-10-15 11:51:26.581613: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14793 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:5d:00.0, compute capability: 7.0)
Model: ResNet50
Batch size: 32
Number of GPUs: 2
Running warmup...
2020-10-15 11:51:35.079986: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-10-15 11:51:36.493020: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-10-15 11:51:36.913004: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-10-15 11:51:38.449857: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[1561,28711],1] (PID 29003)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[1561,28711],0] (PID 25312)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "./horovod-tf2-bench.py", line 112, in <module>
    benchmark_step(first_batch=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
Traceback (most recent call last):
  File "./horovod-tf2-bench.py", line 112, in <module>
    self.captured_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    benchmark_step(first_batch=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 598, in call
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  ncclCommInitRank failed: unhandled system error
	 [[node HorovodBroadcast_conv1_bn_moving_mean_0 (defined at <string>:234) ]] [Op:__inference_benchmark_step_15833]

Function call stack:
benchmark_step

    self.captured_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  ncclCommInitRank failed: unhandled system error
	 [[node HorovodBroadcast_conv1_bn_moving_mean_0 (defined at <string>:234) ]] [Op:__inference_benchmark_step_15833]

Function call stack:
benchmark_step

srun: error: jwc09n018: task 1: Exited with exit code 1
srun: error: jwc09n012: task 0: Exited with exit code 1
```
