### ISSUE TITLE
cuda runtime error - device not ready

### ISSUE THREAD

**Issue by rudvlf0413** [horovod/horovod#1838]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.4
3. Horovod version: 0.19.1
4. MPI version: OpenMPI 4.0.2
5. CUDA version: 10.1
6. NCCL version: 2.6
7. Python version: 3.7.7
8. OS and version: 
9. GCC version:

I got an error link:
THCudaCheck FAIL file=horovod/torch/ready_event.cc line=94 error=600 : device not ready

And the full logs are:

```
[1,1]<stderr>:THCudaCheck FAIL file=horovod/torch/ready_event.cc line=94 error=600 : device not ready
[1,1]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
[1,1]<stderr>:  what():  [1,1]<stderr>:cuda runtime error (600) : device not ready at horovod/torch/ready_event.cc:94
[1,1]<stderr>:[davian-black:20982] *** Process received signal ***
[1,1]<stderr>:[davian-black:20982] Signal: Aborted (6)
[1,1]<stderr>:[davian-black:20982] Signal code:  (-6)
[1,1]<stderr>:[davian-black:20982] [ 0] [1,1]<stderr>:/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f13a97ed390]
[1,1]<stderr>:[davian-black:20982] [ 1] [1,1]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f13a9447428]
[1,1]<stderr>:[davian-black:20982] [ 2] [1,1]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f13a944902a]
[1,1]<stderr>:[davian-black:20982] [ 3] [1,1]<stderr>:/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/torch/../../../libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0xbc)[0x7f139a2e384a]
[1,1]<stderr>:[davian-black:20982] [ 4] [1,1]<stderr>:/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/torch/../../../libstdc++.so.6(+0xabf47)[0x7f139a2e1f47]
[1,1]<stderr>:[davian-black:20982] [ 5] [1,1]<stderr>:/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/torch/../../../libstdc++.so.6(+0xabf7d)[0x7f139a2e1f7d]
[1,1]<stderr>:[davian-black:20982] [ 6] [1,1]<stderr>:/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/torch/../../../libstdc++.so.6(__cxa_rethrow+0x0)[0x7f139a2e215a]
[1,1]<stderr>:[davian-black:20982] [ 7] [1,1]<stderr>:/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch.so(+0x1c4c0b7)[0x7f136c2140b7]
[1,1]<stderr>:[davian-black:20982] [ 8] [1,1]<stderr>:/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch.so(+0x1c4c31f)[0x7f136c21431f]
[1,1]<stderr>:[davian-black:20982] [ 9] [1,1]<stderr>:/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch.so(__THCudaCheck+0x3b)[0x7f136e82f5cb]
[1,1]<stderr>:[davian-black:20982] [10] [1,1]<stderr>:/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/horovod/torch/mpi_lib_v2.cpython-37m-x86_64-linux-gnu.so(_ZNK7horovod5torch15TorchReadyEvent5ReadyEv+0x29)[0x7f133fa7a3a9]
[1,1]<stderr>:[davian-black:20982] [11] [1,1]<stderr>:/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/horovod/torch/mpi_lib_v2.cpython-37m-x86_64-linux-gnu.so(+0x7a9cc)[0x7f133f9f69cc]
[1,1]<stderr>:[davian-black:20982] [12] [1,1]<stderr>:/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/torch/../../../libstdc++.so.6(+0xc819d)[0x7f139a2fe19d]
[1,1]<stderr>:[davian-black:20982] [13] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f13a97e36ba]
[1,1]<stderr>:[davian-black:20982] [14] [1,1]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f13a951941d]
[1,1]<stderr>:[davian-black:20982] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node davian-black exited on signal 6 (Aborted).
```

I don't know how to solve this problem... Do you know how to solve?

**Comment by hammer2505** [comment]
Have you solved this problem?

**Comment by rudvlf0413** [comment]
@hammer2505 
Yes, I install MPI using `conda install openmpi` and then reinstall Horovod.

**Comment by hammer2505** [comment]
I solved the problem in your way， thank you！
