### ISSUE TITLE
Out of resource error while running horovod 

### ISSUE THREAD

**Issue by Vidyaranya** [horovod/horovod#1932]
**Environment:**
I used singularity to run and hence I used a dockerfile
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: 1.11.0
3. Horovod version:
4. MPI version: 3.1.2
5. CUDA version: 9.0
6. NCCL version: 2.3.5-2+cuda9.0
7. Python version: 2.7
8. OS and version: ubuntu16.04
9. GCC version: 5.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
When I run horovod using mpirun command

```
mpirun -v -np 1 -bind-to none -map-by slot  -x LD_LIBRARY_PATH -x PATH   -mca btl vader,self,tcp,openib,smcuda -mca pml ob1 -mca oob_tcp_if_include enp1s0f1,enp1s0f0   -x NCCL_SOCKET_IFNAME=^lo,docker0  singularity exec --nv horovod.sif run_code.sh 
```
the code fails at hvd.init() with the following error:

```[dgj318:64919] PMIX ERROR: OUT-OF-RESOURCE in file client/pmix_client.c at line 228
[dgj318:64919] OPAL ERROR: Error in file pmix2x_client.c at line 109
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[dgj318:64919] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

I use slurm to schedule my jobs on HPC cluster and as you see, I use singularity. I used the keras_mnist example. Interestingly, the same command and code worked on a different HPC cluster and failing on this.

**Comment by tgaddair** [comment]
Hey @Vidyaranya, usually this kind of error is caused by having different versions of MPI on the system (for example, building Horovod with one version of MPI, then attempting to run it with a different version).  See: [this](https://stackoverflow.com/questions/53149888/error-when-executing-openmpi-code-opal-error-with-nvcc) StackOverflow thread for more info.

**Comment by sai-anyvision** [comment]
Hi @tgaddair, thanks for the quick response! While that solved the problem to an extent, I face another issue now. Specifically, hvd.init() hangs. I went through quite a few issues and tried to implement the solutions present there (as you can see in the mpirun command below as well). However, none of them worked for me. The mpirun command I use is as follows:
```
mpirun  -np 1\
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl tcp,self,vader -mca btl_tcp_if_exclude docker0,lo -mca btl_base_verbose 100 \
    -x NCCL_SOCKET_IFNAME=^docker0,lo \
     singularity exec --nvhorovod.sif run.sh
```
I am running on only one GPU and it still fails! Please let me know how this might be fixed

**Comment by Vidyaranya** [comment]
Hi @tgaddair, thanks for the quick response! While that solved the problem to an extent, I face another issue now. Specifically, hvd.init() hangs. I went through quite a few issues and tried to implement the solutions present there (as you can see in the mpirun command below as well). However, none of them worked for me. The mpirun command I use is as follows:
```
mpirun  -np 1\
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl tcp,self,vader -mca btl_tcp_if_exclude docker0,lo -mca btl_base_verbose 100 \
    -x NCCL_SOCKET_IFNAME=^docker0,lo \
     singularity exec --nvhorovod.sif run.sh
```
I am running on only one GPU and it still fails! Please let me know how this might be fixed

**Comment by tgaddair** [comment]
Hey @Vidyaranya, can you try generating a stack trace from the hanging process?  For example, using `gdb -p <pid>` and provide the output of `thread apply all bt`?

**Comment by Vidyaranya** [comment]
Hi @tgaddair , I am using slurm to schedule my jobs on an HPC cluster. My jobs randomly get allocated to a gpu on a node and I can't ssh to those nodes directly to get the stack trace. Is there anything else that I can do?

**Comment by Vidyaranya** [comment]
After quite a bit of debugging, the problem seems to be arising from using the OpenMPI 3.0.0 version. Upgrading to 3.1.2 worked. Closing this.
