### ISSUE TITLE
Can I have Adasum consume less GPU memory?

### ISSUE THREAD

**Issue by talkhaldi** [horovod/horovod#2251]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.6.0
3. Horovod version: 0.20.0
4. MPI version: 4.0.3
5. CUDA version: 10.2
6. NCCL version: 2.7.8-1
7. Python version: 3.6.5
8. OS and version: Ubuntu 16.04.6
9. GCC version: 5.5.0

**Question:**

My model takes ~15.4G out of my 16G GPU and it runs normally on multiple machines/multiple GPUs. If I use Adasum, I run out of memory. Does it use that much GPU memory? Is there a way to reduce that usage? If not, what other remedies can I do to have a stable run with 512 batch size across 32 nodes?

P.S: I know that one solution is to use fp16, but apex is not yet supported with Adasum. Any update on that?

**Comment by talkhaldi** [comment]
Actually, this issue caused #2244, So I prefer to solve this issue as top priority. (Then I wouldn't need to shard the model).

I appreciate any input on this, please!

**Comment by talkhaldi** [comment]
Just when I thought I solved it.. I found a quote saying:

`To force allreduce to happen on CPU, pass device_dense='/cpu:0' to hvd.DistributedOptimizer`

Unfortunately, "device_dense" is a keyword in all but torch version of DistributedOptimizer! Why is that?

**Comment by tgaddair** [comment]
@kit1980 @Tixxx any thoughts on why the memory utilization is high?

**Comment by talkhaldi** [comment]
A gentle reminder. Can you please take a look at this?

**Comment by talkhaldi** [comment]
Okay, I understand that if Adasum works on GPU, it needs to allocate stuff on GPU:
(from https://horovod.readthedocs.io/en/stable/gpus_include.html)

> Note: Allgather allocates an output tensor which is proportionate to the number of processes participating in the training.

I would use less processes and gradient accumulation as a workaround, but it runs out of memory even with 4 processes.

So I guess it boils down to this very useful option if it existed in torch:
  
> If you find yourself running out of GPU memory, you can force allgather to happen on CPU by passing device_sparse='/cpu:0' to hvd.DistributedOptimizer

Which is not implemented in torch. (As also mentioned in #1230 )

In the torch code, I found this line: https://github.com/horovod/horovod/blob/ae8f9ab98dd0c418007841e51094b99df6f1a86a/horovod/torch/mpi_ops.py#L106

But I did try to install horovod with HOROVOD_GPU_OPERATIONS=MPI and no NCCL support. it still runs out of memory :o

Is there a way/workaround to force it to use CPU, other than waiting for torch's hvd.DistributedOptimizer to support device_sparse?

**Comment by tgaddair** [comment]
Hey @talkhaldi, you can force any tensor in PyTorch to be on CPU: `tensor.cpu()`.  You can try this on your tensors as a first step, which will certainly reduce GPU memory.

Another option is to try compression.  Horovod comes with FP16 compression that will cut the amount of GPU memory required by Horovod during allreduce by half.  You can also implement your own "Compressor" that moves the gradient to CPU before the allreduce then back to GPU after allreduce completes (see: https://github.com/horovod/horovod/blob/master/horovod/torch/compression.py).

One reason we do not expose `device_sparse` for PyTorch is that we do not do allgather on sparse tensors in PyTorch.  Are you working with a lot of sparse gradients in your model?

**Comment by talkhaldi** [comment]
Thank you for your reply!

For the FP16 compression, I oddly got increase of about 200M in GPU memory usage when it was on. However, I tried your other suggestion:

```
class CPUCompressor(Compressor):
    """Default no-op compression."""
    @staticmethod
    def compress(tensor):
        """Returns the tensor unmodified."""
        return tensor.cpu(), None

    @staticmethod
    def decompress(tensor, ctx):
        """Returns the tensor unmodified."""
        return tensor.cuda()
```

And it did save about 300M, but it was not enough.

I ended up changing the architecture with much less tokens to fit and still use Adasum:
- Smaller model, without Adasum: 12931Mib
- Smaller model, with Adasum: 15863MiB

> One reason we do not expose device_sparse for PyTorch is that we do not do allgather on sparse tensors in PyTorch. Are you working with a lot of sparse gradients in your model?

Simplifying it, it's a transformer based QA model.

**Comment by Tixxx** [comment]
Hi @talkhaldi , Adasum indeed needs extra space since it's performing allreduce on the difference between model weights before and after param update, it allocates extra tensors to store previous weights. I think increasing accumulation is a mitigation method to reduce activation size per minibantch to make some space for the extra memory needed for Adasum. 
As for fp16, to make apex work with the async flow of Horovod, you may need to use call allreduce separately instead of using DistributedOptimizer, a general flow I can think of is:
1. create additional buffer to store current values of weights, let's call them prev_weight
2. perform forward + backward in apex loss scale context manager
3. exit context and call original_optimizer.step()
4. get the model weight difference, delta = weight - prev_weight
5. call hvd.allreduce(op=hvd.Adasum) on all deltas
6. synchronize all allreductions to get reduced_delta
7. update final weight, weight = prev_weight + reduced_delta

**Comment by talkhaldi** [comment]
Thank you for your reply!

I understand it needs space, I just wanted to reduce that space by applying the operations on CPU. I did try to "compress" things to CPU and decompress them back to "cuda" but when it wasn't enough, I read the code, and it seems I need to do that earlier (At the time of calculating delta maybe). 

Thanks for the accumulation tip. I would try it but it's running out of memory for batch size 1 on a single machine with 4 GPUs, I would've used accumulation otherwise.

Finally for the fp16, it's strange but when enabling fp16 with transformers, the GPU memory usage increases (Even without using Adasum). It's a transformers/apex issue not related to Horovod, but if in the future I need it, I will follow the steps you described.

Thanks again!

**Comment by Tixxx** [comment]
@talkhaldi Got it, didn't realize it went OOM even with 1 batch. For the CPU offload, you'd probably need to make a "hacky" version of the DistributedAdasumOptimizer to:
1. When initialized, self._starting_model needs to be copied to CPU, right now it allocates on the same device as original model.
2. In _allreduce_grad_async, after calling super().step(), copy start to gpu before doing the subtraction to get delta.
3. In step(), copy start back to cpu after synchronizing the handle.

Note that this doesn't guarantee that OOM won't happen, it just "pipelines" the storing of different weights so that not all weights exist in the memory at once.

For fp16, it definitely sounds like an apex-related issue since with weights, gradients and most of activations being in half precision, it should get a substantial reduction in storage.

**Comment by talkhaldi** [comment]
Thanks, I did try your suggestion and I managed to get the load to the cpu, and the big model fit with Adasum, but of course became very slow. I could still get reasonable time (1 hour per epoch), but using more nodes.

In that regard, I think I can close the issue. 

I have some other questions but I'll open a separate issue for that. Thanks again!
