### ISSUE TITLE
Error "Failed to get convolution algorithm." in Tensorflow 2.3.1 with CUDA

### ISSUE THREAD

**Issue by jtchilders** [horovod/horovod#2345]
**Environment:**
1. Framework: Tensorflow
2. Framework version: 2.3.1
3. Horovod version: 0.20.0
4. MPI version: 3.1
5. CUDA version: 11.0
6. NCCL version: 2.7.8
7. Python version: 3.8
8. Spark / PySpark version: n/a
9. OS and version:  Ubuntu 18.04
10. GCC version: 7.5.0
11. CMake version: 3.18.2

I am working on a system with 4 AMD EPYC CPUs and 8 NVidia A100 GPUs. 

I installed python 3.8 via miniconda, then followed the directions to install Tensorflow 2.3.1 with CUDA from here:
https://www.tensorflow.org/install/source

I linked against
CUDA 11.0
cuDNN 8.0.4
TensorRT 7.2.0.14
NCCL 2.7.8

Then I built Horovod from scratch with tag 0.20.0 in the same environment using the commands:

```bash
HOROVOD_NCCL_LINK=SHARED HOROVOD_NCCL_HOME=$CUDA_DEPS/nccl_2.7.8-1+cuda11.0_x86_64 HOROVOD_CMAKE=$(which cmake) HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 CC=$MPI/bin/mpicc CXX=$MPI/bin/mpicxx python setup.py build_ext

HOROVOD_NCCL_LINK=SHARED HOROVOD_NCCL_HOME=$CUDA_DEPS/nccl_2.7.8-1+cuda11.0_x86_64 HOROVOD_CMAKE=$(which cmake) HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 CC=$MPI/bin/mpicc CXX=$MPI/bin/mpicxx python setup.py install
```

All these steps completed without errors.

I can run the MNIST example in this repo without horovod using:
https://github.com/jtchilders/tensorflow_skeleton
using the command `CUDA_VISIBLE_DEVICES=0 python main.py -c configs/mnist.py`

There are no errors in this case.

However, if I run with horovod using this command:
`mpirun -n 8 main.py -c configs/mnist.py --horovod`

I get the following error:

```bash
Traceback (most recent call last):
  File "main.py", line 304, in <module>
    main()
  File "main.py", line 161, in main
    loss_value,pred = train_step(net,loss_func,opt,inputs,labels,first_batch,hvd)
  File ".../tf-build/miniconda3/latest/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File ".../tf-build/miniconda3/latest/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File ".../tf-build/miniconda3/latest/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File ".../tf-build/miniconda3/latest/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File ".../tf-build/miniconda3/latest/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File ".../tf-build/miniconda3/latest/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File ".../tf-build/miniconda3/latest/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node mnist/conv2d/Conv2D (defined at .../git/tensorflow_skeleton/model/mnist.py:20) ]] [Op:__inference_train_step_759]

Errors may have originated from an input operation.
Input Source operations connected to node mnist/conv2d/Conv2D:
 inputs (defined at main.py:161)

Function call stack:
train_step

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
orterun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[14832,1],3]
  Exit code:    1
--------------------------------------------------------------------------
```

I assume this is some kind of symbol mangling happening between Horovod and Tensorflow since the code runs without error without Horovod.

**Comment by tgaddair** [comment]
Hey @jtchilders, does this error also arise if you run our provided [tensorflow2_mnist.py](https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_mnist.py) script?

**Comment by tgaddair** [comment]
If you have multiple versions of CUDA on your system, you may also need to specify `HOROVOD_CUDA_HOME` when installing Horovod.

**Comment by jtchilders** [comment]
> Hey @jtchilders, does this error also arise if you run our provided [tensorflow2_mnist.py](https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_mnist.py) script?

I was able to run that example with `mpirun -n 8 python tensorflow2_mnist.py` and have it complete without error.

Though, the model definition is slightly different. Would this matter?
 
```python
class MNIST(tf.keras.Model):

   def __init__(self):
      super(MNIST, self).__init__()
      self.conv1 = tf.keras.layers.Conv2D(32, 3, activation='relu')
      self.flatten = tf.keras.layers.Flatten()
      self.d1 = tf.keras.layers.Dense(128, activation='relu')
      self.d2 = tf.keras.layers.Dense(10)

   def call(self, x):
      x = self.conv1(x)
      x = self.flatten(x)
      x = self.d1(x)
      return self.d2(x)
```

**Comment by tgaddair** [comment]
I noticed you set `CUDA_VISIBLE_DEVICES` in your script.  This can cause systems like NCCL to fail to find peer GPUs for allreduce.  Can you try removing that line and setting `tf.config.experimental.set_visible_devices` as we do [here](https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_mnist.py#L27).

**Comment by jtchilders** [comment]
If I remove the CUDA_VISIBLE_DEVICES from the command line it still runs fine without mpi/horovod. 

I also removed my line of code [here](https://github.com/jtchilders/tensorflow_skeleton/blob/master/main.py#L62) which sets:
```python
os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())
```
and then added your suggested 
```python
tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
```
[near here in my code](https://github.com/jtchilders/tensorflow_skeleton/blob/master/main.py#L84)

When I do this and run, I get a bad segmentation fault and the best error feedback I can find in the very long dump is this message:
```bash
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:5 failed. Status: all CUDA-capable devices are busy or unavailable
```
I have had trouble in the past with Horovod/MPI/NVidia trying to run 1 rank per GPU on the same node and I've always found that it works best when `CUDA_VISIBLE_DEVICES` is set to the `hvd.local_rank()`.

In my original version, I only set this environment variable and it has run fine in the past on other NVidia systems like the DGX-V100 systems. On this system, with horovod it fails during model jit-compiling with my original posted error. It's confusing to say the least.

I'll try rebuilding with `HOROVOD_CUDA_HOME` in the morning.

**Comment by jtchilders** [comment]
I added `HOROVOD_CUDA_HOME` to the build/install commands. This didn't change anything. 

The `set_visible_devices` call causes errors at that line of code as posted before.

With the line that sets `CUDA_VISIBLE_DEVICES` the code fails during jit-compilation of the graph or during the first execution of the graph inside the `@tf.function train_step()`.

If I run one rank, without Horovod loaded and no `mpirun`, everything runs with 5 epochs evaluated.

Confusing...

**Comment by tgaddair** [comment]
Hey @jtchilders, since you were able to run `tensorflow2_mnist.py` successfully, we know that `tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')` can work in your setup, so let's try and get it working in your script as well.

The error suggests that some other process has already claimed a lock on that GPU.  Does that error only come from a particular rank?  When you run `nvidia-smi`, are there other processes using that GPU?

It is possible that one of your TF imports is claiming the GPU before we get to `set_visible_devices`.  One option is to move those lines as close to the top of the script as possible (or comment out sections of the code temporarily) so we can rule out the statements above being the culprit.

**Comment by jtchilders** [comment]
OK, I think you are on to something. the `tensorflow2_mnist.py` reports 1 process per GPU. Mine reports 8 per GPU. 

I'll see if I can move this higher up, though, the only thing between importing TF and setting visible devices is the HVD import and parsing command line args.

**Comment by jtchilders** [comment]
OK, I think I have found the problem. 

I had this code:
```python
from tensorflow.python.client import device_lib
# ...
logging.debug(device_lib.list_local_devices())
```
which was the way you probed GPUs some time ago and I had not removed it from the script.

After removing this, it works fine. So that was what is causing my trouble. I think you can close this issue.

**Comment by tgaddair** [comment]
Glad you found the root cause!  Thanks for detailing the fix.  This will be really useful for other people who run into this issue.
