### ISSUE TITLE
NCCL Alltoall hangs in GPUOpContext::FinalizeGPUQueue()

### ISSUE THREAD

**Issue by maxhgerlach** [horovod/horovod#2601]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.4.0
3. Horovod version: 0.21.1
4. MPI version: Open MPI 4.0.2
5. CUDA version: 11.0.3-1
6. NCCL version: 2.8.3-1+cuda11.0
7. Python version: 3.7.5
8. Spark / PySpark version:
9. OS and version: Ubuntu 16.04.7 LTS
10. GCC version: 5.4.0
11. CMake version: 3.5.1

**Bug report:**
Our custom TensorFlow code that makes use of `hvd.alltoall()` and `hvd.allreduce()` tends to hang indefinitely in one of the first training steps, we can reproduce it easily running on four local GPUs. Setting `NCCL_SHM_DISABLE=1` seems to circumvent the issue (at great performance cost), so this might also be an issue in NCCL.

With `HOROVOD_LOG_LEVEL=TRACE` there are these symptoms (slightly edited for brevity):
```
[1,0]<stdout>:[16:34:01. 11643: T common/operations.cc:633] [0]: Finished performing Send/alltoall_io
[1,2]<stdout>:[16:34:01. 11638: T common/operations.cc:633] [2]: Finished performing Send/alltoall_io
[1,3]<stdout>:[16:34:01. 11631: T common/operations.cc:633] [3]: Finished performing Send/alltoall_io
[1,1]<stdout>:[16:34:01. 11676: T common/operations.cc:633] [1]: Finished performing Send/alltoall_io
[1,2]<stdout>:[16:34:01. 12842: T common/operations.cc:1159] [2]: Enqueued Collect/alltoall_io
[1,0]<stdout>:[16:34:01. 12890: T common/operations.cc:1159] [0]: Enqueued Collect/alltoall_io
[1,3]<stdout>:[16:34:01. 12964: T common/operations.cc:1159] [3]: Enqueued Collect/alltoall_io
[1,0]<stdout>:[16:34:01. 13835: T common/controller.cc:173] [0]: Sent 1 messages to coordinator.
[1,0]<stdout>:[16:34:01. 13852: T common/controller.cc:248] Adding messages from rank 0
[1,0]<stdout>:[16:34:01. 13872: T common/controller.cc:273] Adding messages from rank 1
[1,2]<stdout>:[16:34:01. 13834: T common/controller.cc:173] [2]: Sent 1 messages to coordinator.
[1,3]<stdout>:[16:34:01. 13832: T common/controller.cc:173] [3]: Sent 1 messages to coordinator.
[1,0]<stdout>:[16:34:01. 13879: T common/controller.cc:273] Adding messages from rank 2
[1,0]<stdout>:[16:34:01. 13888: T common/controller.cc:273] Adding messages from rank 3
[1,0]<stderr>:[16:35:56.949891: W common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Missing ranks:
[1,0]<stderr>:1: [Collect/alltoall_io]
```
So all four ranks appear to complete the first alltoall operation `Send/alltoall_io`. But only three ranks manage to enqueue the following `Collect/alltoall_io`. I verified that this is not due to a bug in our model code (the TF op corresponding to `Collect/alltoall_io` is reached by each rank).

I attached gdb to the process corresponding to the hanging rank 1 and found this  thread backtrace:
```
Thread 7 (Thread 0x7fdfd4a5e700 (LWP 144799)):
#0  0x00007fe08975c8e7 in sched_yield () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fdf6a03554d in __gthread_yield () at /usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:692
#2  std::this_thread::yield () at /usr/include/c++/5/thread:270
#3  horovod::common::GPUContext::impl::WaitForEvents(std::queue<std::pair<std::string, CUevent_st*>, std::deque<std::pair<std::string, CUevent_st*>, std::allocator<std::pair<std::string, CUevent_st*> > > >&, std::vector<horovod::common::TensorTableEntry, std::allocator<horovod::common::TensorTableEntry> > const&, horovod::common::Timeline&, std::function<void ()> const&) (error_check_callback=..., timeline=..., entries=std::vector of length 1, capacity 1 = {...}, event_queue=std::queue wrapping: std::deque with 0 elements, this=0x61d8ac0) at /mnt/data/max/horovod/horovod/common/ops/cuda_operations.cc:106
#4  horovod::common::GPUContext::WaitForEvents(std::queue<std::pair<std::string, CUevent_st*>, std::deque<std::pair<std::string, CUevent_st*>, std::allocator<std::pair<std::string, CUevent_st*> > > >&, std::vector<horovod::common::TensorTableEntry, std::allocator<horovod::common::TensorTableEntry> > const&, horovod::common::Timeline&, std::function<void ()> const&) (this=<optimized out>, event_queue=std::queue wrapping: std::deque with 0 elements, entries=std::vector of length 1, capacity 1 = {...}, timeline=..., error_check_callback=...) at /mnt/data/max/horovod/horovod/common/ops/gpu_context_impl.cc:17
#5  0x00007fdf6a0368f1 in horovod::common::GPUOpContext::<lambda()>::operator() (__closure=0x7fdaa0000c30) at /mnt/data/max/horovod/horovod/common/ops/gpu_operations.cc:71
#6  std::_Function_handler<void(), horovod::common::GPUOpContext::FinalizeGPUQueue(const std::vector<horovod::common::TensorTableEntry>&, bool, const std::function<void()>&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/5/functional:1871
#7  0x00007fdf69ff842f in std::function<void ()>::operator()() const (this=0x7fdfd4a5ded0) at /usr/include/c++/5/functional:2267
#8  horovod::common::ThreadPool::loop (this=0x7fdf71555df8 <horovod::common::(anonymous namespace)::gpu_context+24>) at /mnt/data/max/horovod/horovod/common/thread_pool.cc:62
#9  0x00007fdff991e030 in std::execute_native_thread_routine_compat (__p=<optimized out>) at /dt7-src/libstdc++-v3/src/nonshared11/../c++11/thread.cc:110
#10 0x00007fe089a436ba in start_thread (arg=0x7fdfd4a5e700) at pthread_create.c:333
#11 0x00007fe0897794dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
Investigating this more closely:
```
(gdb) thread 7
(gdb) frame 3   # WaitForEvents, as called in a thread function executed by FinalizeGPUQueue
(gdb) list
101	        }
102
103	        if (error_check_callback) {
104	          error_check_callback();
105	        }
106	        std::this_thread::yield();
107	      }
108
109	      if (name != "") {
110	        timeline.ActivityEndAll(entries);
(gdb) p name
$1 = ""
(gdb) p cuda_result
$2 = cudaErrorNotReady
(gdb) p event_queue
$3 = std::queue wrapping: std::deque with 0 elements
(gdb) p entries
$4 = std::vector of length 1, capacity 1 = {{tensor_name = "Send/alltoall_io", context = std::shared_ptr<horovod::common::OpContext> (use count 2, weak count 0) = {get() = 0x7fddac009600}, tensor = std::shared_ptr<horovod::common::Tensor> (use count 2, weak count 0) = {get() = 0x7fddac00d400}, output = std::shared_ptr<horovod::common::Tensor> (empty) = {get() = 0x0}, root_rank = 0, ready_event = std::shared_ptr<horovod::common::ReadyEvent> (use count 2, weak count 0) = {get() = 0x7fddac016ed0}, device = 1, callback = {<std::_Maybe_unary_or_binary_function<void, horovod::common::Status const&>> = {<std::unary_function<horovod::common::Status const&, void>> = {<No data fields>}, <No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x7fdaa0007a30, _M_const_object = 0x7fdaa0007a30, _M_function_pointer = 0x7fdaa0007a30, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x7fdaa0007a30, this adjustment 140576963955552}, _M_pod_data = "0z\000\240\332\177\000\000`\v\000\240\332\177\000"}, _M_manager = 0x7fdf6a04e1b0 <std::_Function_base::_Base_manager<horovod::tensorflow::HorovodAlltoallOp::ComputeAsync(tensorflow::OpKernelContext*, std::function<void ()>)::{lambda(horovod::common::Status const&)#1}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<horovod::tensorflow::HorovodAlltoallOp::ComputeAsync(tensorflow::OpKernelContext*, std::function<void ()>)::{lambda(horovod::common::Status const&)#1}> const&, std::_Manager_operation)>}, _M_invoker = 0x7fdf6a04de00 <std::_Function_handler<void (horovod::common::Status const&), horovod::tensorflow::HorovodAlltoallOp::ComputeAsync(tensorflow::OpKernelContext*, std::function<void ()>)::{lambda(horovod::common::Status const&)#1}>::_M_invoke(std::_Any_data const&, horovod::common::Status const&)>}, splits = std::vector of length 4, capacity 4 = {533, 349, 350, 312}}}
```
So it is stuck in a loop in [WaitForEvents in cuda_operations.cc](https://github.com/horovod/horovod/blob/a9dea74abc1f0b8e81cd2b6dd9fe81e2c4244e39/horovod/common/ops/cuda_operations.cc#L94) waiting for an event to be successful that was queued in [GPUOpContext::FinalizeGPUQueue](https://github.com/horovod/horovod/blob/f109550c36bb07a964c3e824433a8aaa23786d48/horovod/common/ops/gpu_operations.cc#L54). From the tensor table entry we see that it is still stuck at the end of [NCCLAlltoall::Execute](https://github.com/horovod/horovod/blob/f109550c36bb07a964c3e824433a8aaa23786d48/horovod/common/ops/nccl_operations.cc#L611) corresponding to the previous `Send/alltoall_io`. I am not sure how to debug this further.

**Comment by romerojosh** [comment]
Hi @maxhgerlach, thanks for the report! I have seen similar hangs occur using NCCL 2.8.3-1 with alltoall. These issues should be fixed in the next NCCL release, which will be out soon. I'll post here when it is available so you can see if it resolves your issue.

**Comment by romerojosh** [comment]
@maxhgerlach NCCL 2.8.4 should be available now. When you get a chance, can you give it a try and see if it resolves this issue?

**Comment by maxhgerlach** [comment]
This issue seems to be fixed with NCCL 2.8.4 indeed. Thanks for pointer, @romerojosh!
