### ISSUE TITLE
Horovod example is hanging on more the 1 GPU

### ISSUE THREAD

**Issue by kuzemchik** [horovod/horovod#280]
Hi, I cannot figure out why Horovod is not working for me.
It is working fine if I allocate only 1 GPU.
If I allocate 2+ It is hanging after first task sent to GPUs. GPUs are spinning 100% but nothing is happening.
I ran both tensorflow and pytorch examples.
I use cuda 9.1.
Latest OpenMPI.
Latest nvidia drivers.
Ubuntu 16.04.
```
mpirun -np 2 \
    -H 127.0.0.1:2 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=DEBUG -x LD_LIBRARY_PATH -x PATH \
    -x NCCL_SOCKET_IFNAME=^enp5s0 \
    -mca btl tcp,self \
    -mca btl_tcp_if_include enp5s0 \
    python tensorflow_mnist.py
```
I tried to do strace, but the output is huge, and I'm not fully sure what am I looking for.
But the only thing that caught my attention is this.
```
[pid 19538] nanosleep({0, 1000000},  <unfinished ...>
[pid 19537] nanosleep({0, 1000000},  <unfinished ...>
[pid 19621] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 19621] futex(0x3bcd708, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 19621] clock_gettime(CLOCK_MONOTONIC_RAW, {6810, 301990448}) = 0
[pid 19621] futex(0x7f8a680008c4, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 19, {1527131426, 124732000}, ffffffff <unfinished ...>
```
I'm only trying to run locally so far.

**Comment by alsrgv** [comment]
@kuzemchik, what interfaces do you have?  I see that you excluded enp5s0 from NCCL but included in MPI - that doesn't seem like a right combination.

**Comment by kuzemchik** [comment]
@alsrgv This is one of things I tried to change back and forth (found in one of questions where there were suggestion either exclude lo,docker from MPI or add another interface).
It didn't work in any case.
```
enp5s0    Link encap:Ethernet  HWaddr 10:7b:44:93:a3:28
          inet addr:192.168.1.17  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:78815 errors:0 dropped:0 overruns:0 frame:0
          TX packets:25850 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:34107594 (34.1 MB)  TX bytes:13376589 (13.3 MB)
          Memory:ef700000-ef71ffff

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:18620 errors:0 dropped:0 overruns:0 frame:0
          TX packets:18620 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:41777011 (41.7 MB)  TX bytes:41777011 (41.7 MB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.8.0.14  P-t-P:10.8.0.13  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Comment by alsrgv** [comment]
@kuzemchik, can you try following the guide, but instead of excluding docker0, exclude tun0?

**Comment by kuzemchik** [comment]
@alsrgv Unfortunately that is where I started from. Just followed the guide.

**Comment by alsrgv** [comment]
@kuzemchik, can you share the command with tun0 excluded?

**Comment by kuzemchik** [comment]
@alsrgv Here:
```
mpirun -np 2 \
>     -H localhost:2 \
>     -bind-to none -map-by slot \
>     -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
>     -x NCCL_SOCKET_IFNAME=enp5s0 \
>     -mca pml ob1 \
>     -mca btl tcp,self \
>     -mca btl_tcp_if_exclude tun0,docker0,lo \
>     python tensorflow_mnist.py
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From tensorflow_mnist.py:70: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From tensorflow_mnist.py:70: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST-data-0/train-images-idx3-ubyte.gz
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST-data-1/train-images-idx3-ubyte.gz
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST-data-0/train-labels-idx1-ubyte.gz
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST-data-1/train-labels-idx1-ubyte.gz
Extracting MNIST-data-0/t10k-images-idx3-ubyte.gz
Extracting MNIST-data-1/t10k-images-idx3-ubyte.gz
Extracting MNIST-data-1/t10k-labels-idx1-ubyte.gz
Extracting MNIST-data-0/t10k-labels-idx1-ubyte.gz
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From tensorflow_mnist.py:84: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
WARNING:tensorflow:From tensorflow_mnist.py:84: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Graph was finalized.
2018-05-25 00:58:36.701191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.607
pciBusID: 0000:0a:00.0
totalMemory: 10.92GiB freeMemory: 10.10GiB
2018-05-25 00:58:36.701228: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-05-25 00:58:36.702129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:0b:00.0
totalMemory: 10.92GiB freeMemory: 10.10GiB
2018-05-25 00:58:36.702167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 1
2018-05-25 00:58:37.348065: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-25 00:58:37.348105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0
2018-05-25 00:58:37.348110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N
2018-05-25 00:58:37.348331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9768 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:0a:00.0, compute capability: 6.1)
2018-05-25 00:58:37.349514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-25 00:58:37.349536: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      1
2018-05-25 00:58:37.349541: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 1:   N
2018-05-25 00:58:37.349747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9768 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:0b:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from ./checkpoints/model.ckpt-2
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

mlstone:37437:37523 [0] misc/ibvwrap.cu:60 WARN Failed to open libibverbs.so[.1]
mlstone:37437:37523 [0] INFO Using internal Network Socket
mlstone:37437:37523 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
mlstone:37437:37523 [0] INFO NET : Using interface enp5s0:192.168.1.17<0>
mlstone:37437:37523 [0] INFO NET/Socket : 1 interfaces found
NCCL version 2.1.15+cuda9.1

mlstone:37438:37520 [1] misc/ibvwrap.cu:60 WARN Failed to open libibverbs.so[.1]
mlstone:37438:37520 [1] INFO Using internal Network Socket
mlstone:37438:37520 [1] INFO Using NCCL Low-latency algorithm for sizes below 16384
mlstone:37438:37520 [1] INFO NET : Using interface enp5s0:192.168.1.17<0>
mlstone:37438:37520 [1] INFO NET/Socket : 1 interfaces found
mlstone:37437:37523 [0] INFO Using 256 threads
mlstone:37437:37523 [0] INFO Min Comp Cap 6
mlstone:37437:37523 [0] INFO NCCL_SINGLE_RING_THRESHOLD=131072
mlstone:37437:37523 [0] INFO Ring 00 :    0   1
mlstone:37438:37520 [1] INFO Ring 00 : 1[1] -> 0[0] via P2P/IPC
mlstone:37437:37523 [0] INFO Ring 00 : 0[0] -> 1[1] via P2P/IPC
mlstone:37437:37523 [0] INFO Launch mode Parallel
```

**Comment by alsrgv** [comment]
@kuzemchik, what's the reason to restrict btl to `self` and `tcp`? Usually `sm` or `vader` are required. I'd recommend keeping default.

**Comment by kuzemchik** [comment]
@alsrgv no reason, just trying everything. It doesn't affect anything, it hangs anyway at the same spot.

```
-mca btl ^openib
```
```
-mca btl vader,self,tcp
```

**Comment by alsrgv** [comment]
@kuzemchik, OK - good to rule out. What were the flags you built Horovod with? Can you capture output of `gdb -p pid`, `thread apply all bt` in a bist?

**Comment by kuzemchik** [comment]
@alsrgv https://gist.github.com/kuzemchik/7b97f8890cfe385ca03f8422c77f68ee

**Comment by alsrgv** [comment]
@kuzemchik, nothing immediately popped out.  Can you try with latest released NCCL 2.2.12?  If that does not help, please capture output of `strace -f -e 'trace=!poll' mpirun ...` into another gist.

**Comment by kuzemchik** [comment]
@alsrgv strace wrote 50M in 15 seconds. I attached the gzipped log. I kept it hanging for 10-15 seconds to make sure I capture stuff. [strace.log.gz](https://github.com/uber/horovod/files/2039426/strace.log.gz)

Also this is running on 2.2.12 now
```
mpirun -np 2 \                                                                                                                                                    *[master]
    -H localhost:2 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -x NCCL_SOCKET_IFNAME=enp5s0 \
    -mca pml ob1 \
    -mca btl ^openib \
    -mca btl_tcp_if_exclude tun0,docker0,lo \
    python tensorflow_mnist.py
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From tensorflow_mnist.py:70: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From tensorflow_mnist.py:70: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST-data-1/train-images-idx3-ubyte.gz
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST-data-0/train-images-idx3-ubyte.gz
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST-data-0/train-labels-idx1-ubyte.gz
Extracting MNIST-data-1/train-labels-idx1-ubyte.gz
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST-data-0/t10k-images-idx3-ubyte.gz
Extracting MNIST-data-1/t10k-images-idx3-ubyte.gz
Extracting MNIST-data-0/t10k-labels-idx1-ubyte.gz
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Extracting MNIST-data-1/t10k-labels-idx1-ubyte.gz
WARNING:tensorflow:From /home/nogod/p3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From tensorflow_mnist.py:84: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
WARNING:tensorflow:From tensorflow_mnist.py:84: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Graph was finalized.
2018-05-25 09:05:49.258752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:0b:00.0
totalMemory: 10.92GiB freeMemory: 10.75GiB
2018-05-25 09:05:49.258782: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 1
2018-05-25 09:05:49.259377: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.607
pciBusID: 0000:0a:00.0
totalMemory: 10.92GiB freeMemory: 10.75GiB
2018-05-25 09:05:49.259393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-05-25 09:05:49.505033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-25 09:05:49.505073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0
2018-05-25 09:05:49.505079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N
2018-05-25 09:05:49.505238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-25 09:05:49.505281: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      1
2018-05-25 09:05:49.505287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 1:   N
2018-05-25 09:05:49.505306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10400 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:0a:00.0, compute capability: 6.1)
2018-05-25 09:05:49.505518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10400 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:0b:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from ./checkpoints/model.ckpt-4
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

mlstone:87783:87873 [0] misc/ibvwrap.cu:61 WARN Failed to open libibverbs.so[.1]
mlstone:87783:87873 [0] INFO Using internal Network Socket
mlstone:87783:87873 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
mlstone:87783:87873 [0] INFO NET : Using interface enp5s0:192.168.1.17<0>
mlstone:87783:87873 [0] INFO NET/Socket : 1 interfaces found
NCCL version 2.2.12+cuda9.1

mlstone:87784:87870 [1] misc/ibvwrap.cu:61 WARN Failed to open libibverbs.so[.1]
mlstone:87784:87870 [1] INFO Using internal Network Socket
mlstone:87784:87870 [1] INFO Using NCCL Low-latency algorithm for sizes below 16384
mlstone:87783:87873 [0] INFO comm 0x7f354837e950 rank 0 nranks 2
mlstone:87784:87870 [1] INFO comm 0x7f35a03767f0 rank 1 nranks 2
mlstone:87784:87870 [1] INFO NET : Using interface enp5s0:192.168.1.17<0>
mlstone:87784:87870 [1] INFO NET/Socket : 1 interfaces found
mlstone:87783:87873 [0] INFO Using 256 threads
mlstone:87783:87873 [0] INFO Min Comp Cap 6
mlstone:87783:87873 [0] INFO NCCL_SINGLE_RING_THRESHOLD=131072
mlstone:87783:87873 [0] INFO Ring 00 :    0   1
mlstone:87784:87870 [1] INFO Ring 00 : 1[1] -> 0[0] via P2P/IPC
mlstone:87783:87873 [0] INFO Ring 00 : 0[0] -> 1[1] via P2P/IPC
mlstone:87783:87873 [0] INFO Launch mode Parallel
```

**Comment by kuzemchik** [comment]
@alsrgv I finally made some progress and made it work with ```export NCCL_P2P_DISABLE=1```. I still want to dig it through to understand why P2P doesn't work.

```
mlstone:116155:116304 [1] INFO Using NCCL Low-latency algorithm for sizes below 16384
mlstone:116157:116301 [3] INFO comm 0x7fa1f03855e0 rank 3 nranks 4
mlstone:116157:116301 [3] INFO NET : Using interface enp5s0:192.168.1.17<0>
mlstone:116157:116301 [3] INFO NET/Socket : 1 interfaces found
mlstone:116155:116304 [1] INFO comm 0x7fe1243ae670 rank 1 nranks 4
mlstone:116156:116307 [2] INFO comm 0x7f4ae43ad6f0 rank 2 nranks 4
mlstone:116155:116304 [1] INFO NET : Using interface enp5s0:192.168.1.17<0>
mlstone:116155:116304 [1] INFO NET/Socket : 1 interfaces found
mlstone:116156:116307 [2] INFO NET : Using interface enp5s0:192.168.1.17<0>
mlstone:116156:116307 [2] INFO NET/Socket : 1 interfaces found
mlstone:116154:116310 [0] INFO comm 0x7f9e0438fe40 rank 0 nranks 4
mlstone:116154:116310 [0] INFO Using 256 threads
mlstone:116154:116310 [0] INFO Min Comp Cap 6
mlstone:116154:116310 [0] INFO NCCL_SINGLE_RING_THRESHOLD=131072
mlstone:116154:116310 [0] INFO Ring 00 :    0   1   2   3
mlstone:116155:116304 [1] INFO 1[116155] -> 2[116156] via direct shared memory
mlstone:116157:116301 [3] INFO 3[116157] -> 0[116154] via direct shared memory
mlstone:116156:116307 [2] INFO 2[116156] -> 3[116157] via direct shared memory
mlstone:116154:116310 [0] INFO 0[116154] -> 1[116155] via direct shared memory
mlstone:116154:116310 [0] INFO Launch mode Parallel
```

**Comment by alsrgv** [comment]
@kuzemchik, great - that's what I was going to suggest next.  Do you have any weird errors in `dmesg`, like in #134 ?

**Comment by kuzemchik** [comment]
Ok, I think I found the problem. Because I'm using AMD Threadripper I needed to add "iommu=soft" to kernel parameters.
https://github.com/NVIDIA/nccl/issues/120
https://github.com/pytorch/pytorch/issues/1637#issuecomment-338268158

@alsrgv Thank you very much!
