### ISSUE TITLE
Installing horovod with error, stdarg.h No such file or directory.

### ISSUE THREAD

**Issue by JKChun** [horovod/horovod#304]
While I try to install horovod with the command 

HOROVOD_NCCL_HOME=/usr/local/nccl_2.2.13-1+cuda8.0_x86_64/ HOROVOD_GPU_ALLREDUCE=NCCL env "PATH=$PATH" env "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" pip3 install --no-cache-dir horovod

It output the error message

fatal error: stdarg.h: No such file or directory

Here is the output message

Collecting horovod
  Downloading https://files.pythonhosted.org/packages/8a/1b/43a2a16e05db68cfbc9eefee0d6af6066eb2a32f512a596371b3f104b48e/horovod-0.13.4.tar.gz (93kB)
    100% |################################| 102kB 12.1MB/s
Requirement already satisfied: cffi>=1.4.0 in /usr/local/lib/python3.5/dist-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.4.0->horovod) (2.18)
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-u07vp65g/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-udwma1g2/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.5/horovod
    creating build/lib.linux-x86_64-3.5/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/torch
    creating build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    creating build/lib.linux-x86_64-3.5/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.5/horovod/common
    creating build/lib.linux-x86_64-3.5/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/keras
    creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
    running build_ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/app/python/deps/include -g -O3 -Wall -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from /usr/include/c++/5/cwchar:44:0,
                     from /usr/include/c++/5/bits/postypes.h:40,
                     from /usr/include/c++/5/bits/char_traits.h:40,
                     from /usr/include/c++/5/string:40,
                     from /usr/include/c++/5/stdexcept:39,
                     from /usr/include/c++/5/array:38,
                     from /usr/include/c++/5/tuple:39,
                     from /usr/include/c++/5/unordered_map:41,
                     from build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.cc:1:
    /usr/include/wchar.h:39:21: fatal error: stdarg.h: No such file or directory
    compilation terminated.
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/app/python/deps/include -g -O3 -Wall -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -stdlib=libc++ -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o
    x86_64-linux-gnu-gcc: error: unrecognized command line option '-stdlib=libc++'
    error: Unable to determine C++ compilation flags (see error above).

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-u07vp65g/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-udwma1g2/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-u07vp65g/horovod/

But the file "stdarg.h" actually exists.
What should I do ?

**Comment by alsrgv** [comment]
@JKChun, what's the location of `stdarg.h` on your system?

**Comment by JKChun** [comment]
this is the output when I type the command "locate stdarg.h"

/home/cch/Downloads/sandbox/usr/include/c++/5/tr1/stdarg.h
/home/cch/Downloads/sandbox/usr/lib/gcc/x86_64-linux-gnu/5/include/cross-stdarg.h
/home/cch/Downloads/sandbox/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/fixincludes/tests/base/stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc/tree-stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc/config/i386/cross-stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc/ginclude/stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc-build-4.8.5/gcc/include/cross-stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc-build-4.8.5/gcc/include/stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc-build-4.8.5/prev-gcc/include/cross-stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc-build-4.8.5/prev-gcc/include/stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc-build-4.8.5/prev-x86_64-unknown-linux-gnu/libstdc++-v3/include/tr1/stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc-build-4.8.5/stage1-gcc/include/cross-stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc-build-4.8.5/stage1-gcc/include/stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc-build-4.8.5/stage1-x86_64-unknown-linux-gnu/libstdc++-v3/include/tr1/stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/gcc-build-4.8.5/x86_64-unknown-linux-gnu/libstdc++-v3/include/tr1/stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/libstdc++-v3/include/c_compatibility/stdarg.h
/home/cch/ENV_BUILD/install_files/gcc-4.8.5/libstdc++-v3/include/tr1/stdarg.h
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/tr1/stdarg.h
/opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/cross-stdarg.h
/opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/stdarg.h
/usr/include/c++/4.4.4/tr1/stdarg.h
/usr/lib/gcc/x86_64-redhat-linux/4.4.4/include/cross-stdarg.h
/usr/lib/gcc/x86_64-redhat-linux/4.4.4/include/stdarg.h
/usr/local/include/c++/4.8.5/tr1/stdarg.h
/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/include/cross-stdarg.h
/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/include/stdarg.h
/usr/share/man/man0p/stdarg.h.0p.gz

**Comment by alsrgv** [comment]
@JKChun, thanks!  And what's the output of `which x86_64-linux-gnu-gcc` ?

**Comment by JKChun** [comment]
/usr/bin/which: no x86_64-linux-gnu-gcc in (/usr/python3/bin:/usr/local/cuda-9.0/bin:/usr/python3/bin:/usr/local/cuda-9.0/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:/home/cch/bin)

**Comment by alsrgv** [comment]
That's strange, given that the output of installation has:
```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/app/python/deps/include -g -O3 -Wall -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o
```

Can you try to find `x86_64-linux-gnu-gcc` then?

**Comment by JKChun** [comment]
this is the output when I type the command "locate x86_64-linux-gnu-gcc"

/home/cch/Downloads/sandbox/usr/bin/x86_64-linux-gnu-gcc
/home/cch/Downloads/sandbox/usr/bin/x86_64-linux-gnu-gcc-5
/home/cch/Downloads/sandbox/usr/bin/x86_64-linux-gnu-gcc-ar
/home/cch/Downloads/sandbox/usr/bin/x86_64-linux-gnu-gcc-ar-5
/home/cch/Downloads/sandbox/usr/bin/x86_64-linux-gnu-gcc-nm
/home/cch/Downloads/sandbox/usr/bin/x86_64-linux-gnu-gcc-nm-5
/home/cch/Downloads/sandbox/usr/bin/x86_64-linux-gnu-gcc-ranlib
/home/cch/Downloads/sandbox/usr/bin/x86_64-linux-gnu-gcc-ranlib-5
/home/cch/Downloads/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-5.1.gz
/home/cch/Downloads/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-ar-5.1.gz
/home/cch/Downloads/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-ar.1.gz
/home/cch/Downloads/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-nm-5.1.gz
/home/cch/Downloads/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-nm.1.gz
/home/cch/Downloads/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-ranlib-5.1.gz
/home/cch/Downloads/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-ranlib.1.gz
/home/cch/Downloads/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc.1.gz
/home/cch/Downloads/singularity/testspace/sandbox/usr/bin/x86_64-linux-gnu-gcc
/home/cch/Downloads/singularity/testspace/sandbox/usr/bin/x86_64-linux-gnu-gcc-5
/home/cch/Downloads/singularity/testspace/sandbox/usr/bin/x86_64-linux-gnu-gcc-ar
/home/cch/Downloads/singularity/testspace/sandbox/usr/bin/x86_64-linux-gnu-gcc-ar-5
/home/cch/Downloads/singularity/testspace/sandbox/usr/bin/x86_64-linux-gnu-gcc-nm
/home/cch/Downloads/singularity/testspace/sandbox/usr/bin/x86_64-linux-gnu-gcc-nm-5
/home/cch/Downloads/singularity/testspace/sandbox/usr/bin/x86_64-linux-gnu-gcc-ranlib
/home/cch/Downloads/singularity/testspace/sandbox/usr/bin/x86_64-linux-gnu-gcc-ranlib-5
/home/cch/Downloads/singularity/testspace/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-5.1.gz
/home/cch/Downloads/singularity/testspace/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-ar-5.1.gz
/home/cch/Downloads/singularity/testspace/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-ar.1.gz
/home/cch/Downloads/singularity/testspace/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-nm-5.1.gz
/home/cch/Downloads/singularity/testspace/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-nm.1.gz
/home/cch/Downloads/singularity/testspace/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-ranlib-5.1.gz
/home/cch/Downloads/singularity/testspace/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc-ranlib.1.gz
/home/cch/Downloads/singularity/testspace/sandbox/usr/share/man/man1/x86_64-linux-gnu-gcc.1.gz

**Comment by alsrgv** [comment]
@JKChun, this is quite a strange environment.  Seems that your compiler is in `/home/cch/Downloads/sandbox`, but I'm not sure libraries are being picked up correctly.  Are you trying to install Horovod in a virtualenv or private Python installation?  If not, can you remove any sandbox paths from `$PATH`?

**Comment by JKChun** [comment]
I trying to install horovod in the sandbox which I built by using singularity.

**Comment by alsrgv** [comment]
@JKChun, are you doing it while running within singularity environment?

**Comment by JKChun** [comment]
Yes.

**Comment by alsrgv** [comment]
@JKChun, can you share your singularity recipe and the build steps, so I could try to repro?

**Comment by JKChun** [comment]
I just try to install horovod within singularity environment on another computer, and it works. 
so I build an image and upload it. That should fix the problem. Thanks for the help.
