### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by anufagbemi** [horovod/horovod#3378]
Hello,
First of all, thank you guys for your package and for making it available.

Right now, I am trying to install horovod based on the instructions you guys gave, but I am still having troubles. I installed it in an anaconda environment and I have the gxx_linux_64 installed.

- NCCL==2.x
- anaconda 4.1.0
- System: Ubuntu 20.04

Whenever I run the following:

`$ HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_NCCL_INCLUDE=/usr/include  HOROVOD_NCCL_LIB=/usr/lib/x86_64-linux-gnu HOROVOD_WITH_TENSORFLOW=1  pip install --no-cache-dir horovod
`

I keep getting this error: 

`In file included from /tmp/pip-install-1o9yj4k1/horovod/horovod/common/operations.cc:63:
    /tmp/pip-install-1o9yj4k1/horovod/horovod/common/ops/nccl_operations.h:22:10: fatal error: nccl.h: No such file or directory
       22 | #include <nccl.h>
          |          ^~~~~~~~
    compilation terminated.
`

Please can you advise me on what could be the problem, because I already have NCCL and I have provided the correct path? Thanks.

Regards,
Sam

**Comment by anufagbemi** [comment]
I solved my problem by upgrading Cuda-11.2 to Cuda-11.4, and reinstalled NCCL for that version. Then reinstalled horovod and it worked fine.
