### ISSUE TITLE
mpirun command stuck on warning

### ISSUE THREAD

**Issue by bluepra** [horovod/horovod#3597]
**Setup:**
I have 2 VMs each with 1 GPU.
I have horovod installed on both VMs.
The training script exists on both VMs

**From my first VM I run the following command:**
/path/to/mpirun -np 2 \
    -H {VM_1_IP}:1,{VM_2_IP}:1 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python training.py

**I get the following message:**
WARNING: Open MPI accepted a TCP connection from what appears to be a
another Open MPI process but cannot find a corresponding process
entry for that peer.

This attempted connection will be ignored; your MPI job may or may not
continue properly.

  Local host: VM_2_IP
  PID:        {4_digit_number}

And then nothing happens...

What am I doing wrong? Any tips appreciated!

**Comment by bluepra** [comment]
I think I fixed the issue. I was forgetting to include the following in my code.

gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
if gpus:
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
