### ISSUE TITLE
Horovod does not work with NCCL with A100 GPUs

### ISSUE THREAD

**Issue by orlopau** [horovod/horovod#3618]
**Environment:**
1. Framework: PyTorch
3. Framework version: 1.10.0
4. Horovod version: 0.25.0
5. MPI version: 4.1.1
6. CUDA version: 11.3.1
7. NCCL version: 2.10.3
8. Python version: 3.9.5
9. Spark / PySpark version: -
10. Ray version: -
11. OS and version: Linux 3.10.0-1160.11.1.el7.x86_64 x86_64
12. GCC version: 10.3.0
13. CMake version: 2.8.12.2

**Bug report:**
Hi, I can not get horovod to work with NCCL + MPI.
When executing this example with `mpiexec -v -N 2 -bind-to none --oversubscribe -x NCCL_DEBUG=TRACE -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python code/test.py`, I receive an Error (see bellow).

I already tried to run the script without Infiniband over ethernet, but nothing changes. I also tried different CUDA versions, and the newest horovod version.

The only related issue i found is this one https://github.com/horovod/horovod/issues/1171, but it unfortunately does not apply to my situation.

I installed horovod with `HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITH_GLOO=1 HOROVOD_WITH_MPI=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_NCCL_HOME=/sw/installed/NCCL/2.10.3-GCCcore-10.3.0-CUDA-11.3.1 HOROVOD_BUILD_CUDA_CC_LIST=80,37 pip install --no-cache-dir "horovod[pytorch]"`

**Log:**
```
tensor([[0.6114, 0.4052]], device='cuda:0')
tensor([[0.4827, 0.4067]], device='cuda:1')

taurusi8001:162088:162095 [0] enqueue.cc:102 NCCL WARN Cuda failure 'invalid device function'
taurusi8001:162088:162095 [0] NCCL INFO Bootstrap : Using ib0:10.1.150.51<0>
taurusi8001:162088:162095 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
taurusi8001:162088:162095 [0] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_0:1/IB ; OOB ib0:10.1.150.51<0>
taurusi8001:162088:162095 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda11.3

taurusi8001:162089:162094 [1] enqueue.cc:102 NCCL WARN Cuda failure 'invalid device function'
taurusi8001:162089:162094 [1] NCCL INFO Bootstrap : Using ib0:10.1.150.51<0>
taurusi8001:162089:162094 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
taurusi8001:162089:162094 [1] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_0:1/IB ; OOB ib0:10.1.150.51<0>
taurusi8001:162089:162094 [1] NCCL INFO Using network IB
taurusi8001:162088:162095 [0] NCCL INFO Channel 00/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 01/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 02/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 03/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 04/24 :    0   1
taurusi8001:162089:162094 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] -1/-1/-1->1->0 [3] -1/-1/-1->1->0 [4] -1/-1/-1->1->0 [5] -1/-1/-1->1->0 [6] -1/-1/-1->1->0 [7] -1/-1/-1->1->0 [8] -1/-1/-1->1->0 [9] -1/-1/-1->1->0 [10] -1/-1/-1->1->0 [11] -1/-1/-1->1->0 [12] -1/-1/-1->1->0 [13] -1/-1/-1->1->0 [14] -1/-1/-1->1->0 [15] -1/-1/-1->1->0 [16] -1/-1/-1->1->0 [17] -1/-1/-1->1->0 [18] -1/-1/-1->1->0 [19] -1/-1/-1->1->0 [20] -1/-1/-1->1->0 [21] -1/-1/-1->1->0 [22] -1/-1/-1->1->0 [23] -1/-1/-1->1->0
taurusi8001:162089:162094 [1] NCCL INFO Setting affinity for GPU 1 to fc,00000000,00fc0000
taurusi8001:162088:162095 [0] NCCL INFO Channel 05/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 06/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 07/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 08/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 09/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 10/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 11/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 12/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 13/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 14/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 15/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 16/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 17/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 18/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 19/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 20/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 21/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 22/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Channel 23/24 :    0   1
taurusi8001:162088:162095 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1 [4] 1/-1/-1->0->-1 [5] 1/-1/-1->0->-1 [6] 1/-1/-1->0->-1 [7] 1/-1/-1->0->-1 [8] 1/-1/-1->0->-1 [9] 1/-1/-1->0->-1 [10] 1/-1/-1->0->-1 [11] 1/-1/-1->0->-1 [12] 1/-1/-1->0->-1 [13] 1/-1/-1->0->-1 [14] 1/-1/-1->0->-1 [15] 1/-1/-1->0->-1 [16] 1/-1/-1->0->-1 [17] 1/-1/-1->0->-1 [18] 1/-1/-1->0->-1 [19] 1/-1/-1->0->-1 [20] 1/-1/-1->0->-1 [21] 1/-1/-1->0->-1 [22] 1/-1/-1->0->-1 [23] 1/-1/-1->0->-1
taurusi8001:162088:162095 [0] NCCL INFO Setting affinity for GPU 0 to fc,00000000,00fc0000
taurusi8001:162089:162094 [1] NCCL INFO Channel 00 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 00 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 01 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 01 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 02 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 02 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 03 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 03 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 04 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 04 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 05 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 05 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 06 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 06 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 07 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 07 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 08 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 08 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 09 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 09 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 10 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 10 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 11 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 11 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 12 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 12 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 13 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 13 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 14 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 14 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 15 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 15 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 16 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 16 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 17 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 17 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 18 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 18 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 19 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 19 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 20 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 20 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 21 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 21 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 22 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 22 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Channel 23 : 1[11000] -> 0[b000] via P2P/IPC/read
taurusi8001:162088:162095 [0] NCCL INFO Channel 23 : 0[b000] -> 1[11000] via P2P/IPC/read
taurusi8001:162089:162094 [1] NCCL INFO Connected all rings
taurusi8001:162089:162094 [1] NCCL INFO Connected all trees
taurusi8001:162089:162094 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
taurusi8001:162088:162095 [0] NCCL INFO Connected all rings
taurusi8001:162088:162095 [0] NCCL INFO Connected all trees
taurusi8001:162088:162095 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
taurusi8001:162089:162094 [1] NCCL INFO 24 coll channels, 32 p2p channels, 32 p2p channels per peer
taurusi8001:162088:162095 [0] NCCL INFO 24 coll channels, 32 p2p channels, 32 p2p channels per peer
taurusi8001:162089:162094 [1] NCCL INFO comm 0x2b5574fc6ed0 rank 1 nranks 2 cudaDev 1 busId 11000 - Init COMPLETE
taurusi8001:162088:162095 [0] NCCL INFO comm 0x2aadc0fc7380 rank 0 nranks 2 cudaDev 0 busId b000 - Init COMPLETE
taurusi8001:162088:162095 [0] NCCL INFO Launch mode Parallel

taurusi8001:162089:162094 [1] enqueue.cc:300 NCCL WARN Cuda failure 'invalid device function'
taurusi8001:162089:162094 [1] NCCL INFO enqueue.cc:1046 -> 1

taurusi8001:162088:162095 [0] enqueue.cc:300 NCCL WARN Cuda failure 'invalid device function'
taurusi8001:162088:162095 [0] NCCL INFO enqueue.cc:1046 -> 1
Traceback (most recent call last):
  File "/sw/installed/Horovod/0.23.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0/lib/python3.9/site-packages/horovod/torch/mpi_ops.py", line 944, in synchronize
Traceback (most recent call last):
  File "/sw/installed/Horovod/0.23.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0/lib/python3.9/site-packages/horovod/torch/mpi_ops.py", line 944, in synchronize
    mpi_lib.horovod_torch_wait_and_clear(handle)
RuntimeError: ncclAllReduce failed: unhandled cuda error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/ssd/ws/s8979104-horovod/sync/code/test.py", line 10, in <module>
    mpi_lib.horovod_torch_wait_and_clear(handle)
RuntimeError: ncclAllReduce failed: unhandled cuda error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/ssd/ws/s8979104-horovod/sync/code/test.py", line 10, in <module>
    print(hvd.allreduce(t))
  File "/sw/installed/Horovod/0.23.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0/lib/python3.9/site-packages/horovod/torch/mpi_ops.py", line 247, in allreduce
    print(hvd.allreduce(t))
  File "/sw/installed/Horovod/0.23.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0/lib/python3.9/site-packages/horovod/torch/mpi_ops.py", line 247, in allreduce
    summed_tensor_compressed = HorovodAllreduce.apply(tensor_compressed, average, name, op,
  File "/sw/installed/Horovod/0.23.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0/lib/python3.9/site-packages/horovod/torch/mpi_ops.py", line 199, in forward
    summed_tensor_compressed = HorovodAllreduce.apply(tensor_compressed, average, name, op,
  File "/sw/installed/Horovod/0.23.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0/lib/python3.9/site-packages/horovod/torch/mpi_ops.py", line 199, in forward
    return synchronize(handle)
  File "/sw/installed/Horovod/0.23.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0/lib/python3.9/site-packages/horovod/torch/mpi_ops.py", line 949, in synchronize
    return synchronize(handle)
  File "/sw/installed/Horovod/0.23.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0/lib/python3.9/site-packages/horovod/torch/mpi_ops.py", line 949, in synchronize
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: ncclAllReduce failed: unhandled cuda error
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: ncclAllReduce failed: unhandled cuda error

taurusi8001:162088:162095 [0] init.cc:1010 NCCL WARN comm 0x2aadc0fc7380 has already been destroyed

taurusi8001:162089:162094 [1] init.cc:1010 NCCL WARN comm 0x2b5574fc6ed0 has already been destroyed
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[44606,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

**Example script:**
```py
import torch
import horovod.torch as hvd

hvd.init()

device = torch.device(f"cuda:{hvd.local_rank()}")

t = torch.rand(1, 2, device=device)
print(t)
print(hvd.allreduce(t))

print("finished!")
```

**Hardware**
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:0B:00.0 Off |                    0 |
| N/A   45C    P0    64W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:11:00.0 Off |                    0 |
| N/A   46C    P0    59W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   46C    P0    60W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  On   | 00000000:40:00.0 Off |                    0 |
| N/A   45C    P0    61W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
```

**Comment by maxhgerlach** [comment]
Hi @orlopau, 

could you check if you can build and run `all_reduce_perf` from nccl-tests? See https://github.com/NVIDIA/nccl-tests 

In case that one works fine the issue may be specific to Horovod (or how it has been built for your system).

**Comment by maxhgerlach** [comment]
Yes, it looks like something on your system may not be configured right. Is NCCL built correctly for your CUDA setup?

**Comment by orlopau** [comment]
You definitely pushed me in the right direction, I had NCCL version 2.10.3 installed and downgraded to 2.9.9.

Now the error is gone!
But I've got a new Error, but with Infiniband, so not related.

Tank you and have a great day!
