### ISSUE TITLE
ncclCommInitRank failed: unhandled cuda error

### ISSUE THREAD

**Issue by WingsOfPanda** [horovod/horovod#3625]
**Environment:**
1. Framework: Tensorflow
2. Framework version: 2.9.1
3. Horovod version: 0.25.0
4. MPI version: 4.1.3
5. CUDA version: 11.7
6. NCCL version: 2.13
7. Python version: 3.10.5
8. Spark / PySpark version:
9. Ray version:
10. OS and version: ubuntu 20.04.2
11. GCC version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
12. CMake version: cmake version 3.23.2

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I am testing on Nvidia Geforce 3090 GPU card with driver version 515. I installed NCCL with `apt install` and tested it by using [nccl-test](https://github.com/NVIDIA/nccl-tests) and it succeeded.

Now if I set `CUDA_VISIBLE_DEVICES=0`, i.e., testing against 1 GPU card by running `hordovodrun -np 1 python3 main.py`, the sample demo can run without problem. Next, if I set `CUDA_VISIBLE_DEVICES=0,1` and run `hordovodrun -np 2 python3 main.py`, i.e., testing against 2 GPU cards, then I encounter the following errors...

```
2022-07-29 00:06:58.785131: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[1,0]<stderr>:2022-07-29 00:07:00.634827: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[1,1]<stderr>:2022-07-29 00:07:00.634825: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[1,0]<stdout>:hvd.local_rank(): 0
[1,1]<stdout>:hvd.local_rank(): 1
[1,1]<stdout>:gpu: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]
[1,0]<stdout>:gpu: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]
[1,1]<stderr>:2022-07-29 00:07:02.355240: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
[1,1]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,0]<stderr>:2022-07-29 00:07:02.361996: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
[1,0]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,1]<stderr>:2022-07-29 00:07:03.185713: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22258 MB memory:  -> device: 1, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:3b:00.0, compute capability: 8.6
[1,0]<stderr>:2022-07-29 00:07:03.244172: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22258 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:18:00.0, compute capability: 8.6
[1,1]<stderr>:WARNING:tensorflow:From /home/liupan/CollaborationForce/Framework-Horovod/frameworkhorovod/supl/data.py:16: shuffle_and_repeat (from tensorflow.python.data.experimental.ops.shuffle_ops) is deprecated and will be removed in a future version.
[1,1]<stderr>:Instructions for updating:
[1,1]<stderr>:Use `tf.data.Dataset.shuffle(buffer_size, seed)` followed by `tf.data.Dataset.repeat(count)`. Static tf.data optimizations will take care of using the fused implementation.
[1,0]<stderr>:WARNING:tensorflow:From /home/liupan/CollaborationForce/Framework-Horovod/frameworkhorovod/supl/data.py:16: shuffle_and_repeat (from tensorflow.python.data.experimental.ops.shuffle_ops) is deprecated and will be removed in a future version.
[1,0]<stderr>:Instructions for updating:
[1,0]<stderr>:Use `tf.data.Dataset.shuffle(buffer_size, seed)` followed by `tf.data.Dataset.repeat(count)`. Static tf.data optimizations will take care of using the fused implementation.
[1,1]<stdout>:Broadcasting initial variable states from rank 0 to all other processes...
[1,0]<stdout>:Broadcasting initial variable states from rank 0 to all other processes...
[1,1]<stdout>:Broadcasting initial variable states from rank 0 to all other processes...
[1,0]<stdout>:Broadcasting initial variable states from rank 0 to all other processes...
[1,1]<stderr>:2022-07-29 00:07:21.059097: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8401
[1,0]<stderr>:2022-07-29 00:07:21.245936: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8401
[1,1]<stderr>:2022-07-29 00:07:23.090369: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
[1,0]<stderr>:2022-07-29 00:07:23.319955: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
[1,1]<stderr>:[biomind:587896:0:587978] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))
[1,0]<stderr>:[biomind:587895:0:587975] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))
[1,1]<stderr>:==== backtrace (tid: 587978) ====
[1,1]<stderr>: 0  /usr/local/ucx-1.13.0/lib/libucs.so.0(ucs_handle_error+0x2dc) [0x7f5a6c0b6bdc]
[1,1]<stderr>: 1  /usr/local/ucx-1.13.0/lib/libucs.so.0(+0x33dc7) [0x7f5a6c0b6dc7]
[1,1]<stderr>: 2  /usr/local/ucx-1.13.0/lib/libucs.so.0(+0x340f4) [0x7f5a6c0b70f4]
[1,1]<stderr>: 3  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x1f018f) [0x7f5a6e00518f]
[1,1]<stderr>: 4  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common11NCCLContext10ErrorCheckENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE12ncclResult_tRP8ncclComm+0x64) [0x7f5a6df6c824]
[1,1]<stderr>: 5  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common13NCCLAllreduce7ExecuteERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x246) [0x7f5a6df6dc56]
[1,1]<stderr>: 6  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteAllreduceERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x7d) [0x7f5a6df2ebed]
[1,1]<stderr>: 7  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteOperationERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseERNS0_10ProcessSetE+0x4c) [0x7f5a6df2f0cc]
[1,1]<stderr>: 8  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0xeaee8) [0x7f5a6deffee8]
[1,1]<stderr>: 9  /usr/local/Python-3.10.5/lib/python3.10/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x1a52490) [0x7f5af77d2490]
[1,1]<stderr>:10  /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f5b28a4d609]
[1,1]<stderr>:11  /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f5b28b87133]
[1,1]<stderr>:=================================
[1,1]<stderr>:[biomind:587896] *** Process received signal ***
[1,1]<stderr>:[biomind:587896] Signal: Segmentation fault (11)
[1,1]<stderr>:[biomind:587896] Signal code:  (-6)
[1,1]<stderr>:[biomind:587896] Failing at address: 0x3e50008f878
[1,1]<stderr>:[biomind:587896] [ 0] [1,1]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7f5b28aab090]
[1,1]<stderr>:[biomind:587896] [ 1] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x1f018f)[0x7f5a6e00518f]
[1,1]<stderr>:[biomind:587896] [ 2] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common11NCCLContext10ErrorCheckENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE12ncclResult_tRP8ncclComm+0x64)[0x7f5a6df6c824]
[1,1]<stderr>:[biomind:587896] [ 3] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common13NCCLAllreduce7ExecuteERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x246)[0x7f5a6df6dc56]
[1,1]<stderr>:[biomind:587896] [ 4] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteAllreduceERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x7d)[0x7f5a6df2ebed]
[1,1]<stderr>:[biomind:587896] [ 5] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteOperationERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseERNS0_10ProcessSetE+0x4c)[0x7f5a6df2f0cc]
[1,1]<stderr>:[biomind:587896] [ 6] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0xeaee8)[0x7f5a6deffee8]
[1,1]<stderr>:[biomind:587896] [ 7] [1,0]<stderr>:==== backtrace (tid: 587975) ====
[1,0]<stderr>: 0  /usr/local/ucx-1.13.0/lib/libucs.so.0(ucs_handle_error+0x2dc) [0x7f708465dbdc]
[1,0]<stderr>: 1  /usr/local/ucx-1.13.0/lib/libucs.so.0(+0x33dc7) [0x7f708465ddc7]
[1,0]<stderr>: 2  /usr/local/ucx-1.13.0/lib/libucs.so.0(+0x340f4) [0x7f708465e0f4]
[1,0]<stderr>: 3  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x1f018f) [0x7f70876fd18f]
[1,0]<stderr>: 4  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common11NCCLContext10ErrorCheckENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE12ncclResult_tRP8ncclComm+0x64) [0x7f7087664824]
[1,0]<stderr>: 5  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common13NCCLAllreduce7ExecuteERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x246) [0x7f7087665c56]
[1,0]<stderr>: 6  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteAllreduceERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x7d) [0x7f7087626bed]
[1,0]<stderr>: 7  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteOperationERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseERNS0_10ProcessSetE+0x4c) [0x7f70876270cc]
[1,0]<stderr>: 8  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0xeaee8) [0x7f70875f7ee8]
[1,0]<stderr>: 9  /usr/local/Python-3.10.5/lib/python3.10/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x1a52490) [0x7f7110eca490]
[1,0]<stderr>:10  /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f7142145609]
[1,0]<stderr>:11  /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f714227f133]
[1,0]<stderr>:=================================
[1,0]<stderr>:[biomind:587895] *** Process received signal ***
[1,0]<stderr>:[biomind:587895] Signal: Segmentation fault (11)
[1,0]<stderr>:[biomind:587895] Signal code:  (-6)
[1,0]<stderr>:[biomind:587895] Failing at address: 0x3e50008f877
[1,0]<stderr>:[biomind:587895] [ 0] [1,0]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7f71421a3090]
[1,0]<stderr>:[biomind:587895] [ 1] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x1f018f)[0x7f70876fd18f]
[1,0]<stderr>:[biomind:587895] [ 2] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common11NCCLContext10ErrorCheckENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE12ncclResult_tRP8ncclComm+0x64)[0x7f7087664824]
[1,0]<stderr>:[biomind:587895] [ 3] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common13NCCLAllreduce7ExecuteERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x246)[0x7f7087665c56]
[1,0]<stderr>:[biomind:587895] [ 4] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteAllreduceERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x7d)[0x7f7087626bed]
[1,0]<stderr>:[biomind:587895] [ 5] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x1a52490)[0x7f5af77d2490]
[1,1]<stderr>:[biomind:587896] [ 8] /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609)[0x7f5b28a4d609]
[1,1]<stderr>:[biomind:587896] [ 9] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteOperationERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseERNS0_10ProcessSetE+0x4c)[0x7f70876270cc]
[1,0]<stderr>:[biomind:587895] [ 6] [1,1]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f5b28b87133]
[1,1]<stderr>:[biomind:587896] *** End of error message ***
[1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0xeaee8)[0x7f70875f7ee8]
[1,0]<stderr>:[biomind:587895] [ 7] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x1a52490)[0x7f7110eca490]
[1,0]<stderr>:[biomind:587895] [ 8] /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609)[0x7f7142145609]
[1,0]<stderr>:[biomind:587895] [ 9] [1,0]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f714227f133]
[1,0]<stderr>:[biomind:587895] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node biomind exited on signal 11 (Segmentation fault).

```

I also tried to down-grade nccl to 2.12.12, however, this time I even can not run on single gpu mode, i.e., `horovodrun -np 1 python3 main.py`. 

Any ideas? Thx!!

**Comment by maxhgerlach** [comment]
When you tried nccl-tests successfully, did you also run them via MPI (rather than with two threads in one process)?

I'm not sure if I read it right, but your segmentation fault backtrace seems to begin in Horovod's `NCCLContext::ErrorCheck()` and end in `libucx`. So something may have already gone wrong earlier with the Allreduce, then `ncclCommAbort(nccl_comm)` leads to the crash?

You could try setting `NCCL_DEBUG=INFO` in your environment to get more logging. This could surface a warning message before the crash.

**Comment by WingsOfPanda** [comment]
Hi @maxhgerlach , here the the log after I enable `NCCL_DEBUG=INFO`. Sorry for a long post...
```

[1,1]<stdout>:Broadcasting initial variable states from rank 0 to all other processes...
[1,0]<stdout>:Broadcasting initial variable states from rank 0 to all other processes...
[1,1]<stdout>:Broadcasting initial variable states from rank 0 to all other processes...
[1,0]<stdout>:Broadcasting initial variable states from rank 0 to all other processes...
[1,1]<stderr>:2022-07-29 21:30:06.898118: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8401
[1,0]<stderr>:2022-07-29 21:30:09.412056: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8401
[1,1]<stderr>:2022-07-29 21:31:18.809173: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
[1,0]<stderr>:2022-07-29 21:31:22.416300: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO Bootstrap : Using lo:127.0.0.1<0>
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO cudaDriverVersion 11070
[1,0]<stdout>:NCCL version 2.13.4+cuda11.7
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO cudaDriverVersion 11070
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO Failed to open libibverbs.so[.1]
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0>
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO Using network Socket
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO Bootstrap : Using lo:127.0.0.1<0>
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO Failed to open libibverbs.so[.1]
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0>
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO Using network Socket
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO Setting affinity for GPU 1 to 3ff003ff
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO Setting affinity for GPU 0 to 3ff003ff
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO Channel 00/02 :    0   1
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO Channel 01/02 :    0   1
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO Channel 00 : 1[3b000] -> 0[18000] via SHM/direct/direct
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO Channel 01 : 1[3b000] -> 0[18000] via SHM/direct/direct
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO Channel 00 : 0[18000] -> 1[3b000] via SHM/direct/direct
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO Channel 01 : 0[18000] -> 1[3b000] via SHM/direct/direct
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO Connected all rings
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO Connected all trees
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO Connected all rings
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO Connected all trees
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO comm 0x7f8f3034a1b0 rank 1 nranks 2 cudaDev 1 busId 3b000 - Init COMPLETE
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO comm 0x7fd72034c4d0 rank 0 nranks 2 cudaDev 0 busId 18000 - Init COMPLETE
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] misc/strongstream.cc:33 NCCL WARN Cuda failure 'CUDA driver is a stub library'
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1423 -> 1
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1459 -> 1
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1465 -> 1
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] misc/strongstream.cc:33 NCCL WARN Cuda failure 'CUDA driver is a stub library'
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1423 -> 1
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1459 -> 1
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1465 -> 1
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO comm 0x7fd72034c4d0 rank 0 nranks 2 cudaDev 0 busId 18000 - Abort COMPLETE
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO comm 0x7f8f3034a1b0 rank 1 nranks 2 cudaDev 1 busId 3b000 - Abort COMPLETE
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1452 -> 4
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1465 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] init.cc:1137 NCCL WARN comm 0x7fd72034c4d0 has already been destroyed
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO init.cc:1191 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1452 -> 4
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1465 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] init.cc:1137 NCCL WARN comm 0x7f8f3034a1b0 has already been destroyed
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO init.cc:1191 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1452 -> 4
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1465 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] init.cc:1137 NCCL WARN comm 0x7fd72034c4d0 has already been destroyed
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO init.cc:1191 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1452 -> 4
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1465 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] init.cc:1137 NCCL WARN comm 0x7f8f3034a1b0 has already been destroyed
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO init.cc:1191 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1452 -> 4
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1465 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] init.cc:1137 NCCL WARN comm 0x7fd72034c4d0 has already been destroyed
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO init.cc:1191 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1452 -> 4
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1465 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] init.cc:1137 NCCL WARN comm 0x7f8f3034a1b0 has already been destroyed
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO init.cc:1191 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1452 -> 4
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1465 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] init.cc:1137 NCCL WARN comm 0x7fd72034c4d0 has already been destroyed
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO init.cc:1191 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1452 -> 4
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1465 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] init.cc:1137 NCCL WARN comm 0x7f8f3034a1b0 has already been destroyed
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO init.cc:1191 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1452 -> 4
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1465 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] init.cc:1137 NCCL WARN comm 0x7fd72034c4d0 has already been destroyed
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO init.cc:1191 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1452 -> 4
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1465 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] init.cc:1137 NCCL WARN comm 0x7f8f3034a1b0 has already been destroyed
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO init.cc:1191 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1452 -> 4
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1465 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] init.cc:1137 NCCL WARN comm 0x7fd72034c4d0 has already been destroyed
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO init.cc:1191 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] misc/argcheck.cc:39 NCCL WARN AllReduce : invalid root 0 (root should be in the 0..-1 range)
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1452 -> 4
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO enqueue.cc:1465 -> 4
[1,1]<stdout>:
[1,1]<stdout>:biomind:6503:6591 [1] init.cc:1137 NCCL WARN comm 0x7f8f3034a1b0 has already been destroyed
[1,1]<stdout>:biomind:6503:6591 [1] NCCL INFO init.cc:1191 -> 4
[1,0]<stdout>:
[1,0]<stdout>:biomind:6502:6588 [0] enqueue.cc:1450 NCCL WARN Cuda failure 'invalid device ordinal'
[1,0]<stdout>:biomind:6502:6588 [0] NCCL INFO enqueue.cc:1465 -> 1
[1,0]<stderr>:[biomind:6502 :0:6588] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))
[1,1]<stderr>:[biomind:6503 :0:6591] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))
[1,0]<stderr>:==== backtrace (tid:   6588) ====
[1,0]<stderr>: 0  /usr/local/ucx-1.13.0/lib/libucs.so.0(ucs_handle_error+0x2dc) [0x7fd71cacdbdc]
[1,0]<stderr>: 1  /usr/local/ucx-1.13.0/lib/libucs.so.0(+0x33dc7) [0x7fd71cacddc7]
[1,0]<stderr>: 2  /usr/local/ucx-1.13.0/lib/libucs.so.0(+0x340f4) [0x7fd71cace0f4]
[1,0]<stderr>: 3  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x1f018f) [0x7fd724fc618f]
[1,0]<stderr>: 4  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common11NCCLContext10ErrorCheckENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE12ncclResult_tRP8ncclComm+0x64) [0x7fd724f2d824]
[1,0]<stderr>: 5  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common13NCCLAllreduce7ExecuteERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x246) [0x7fd724f2ec56]
[1,0]<stderr>: 6  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteAllreduceERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x7d) [0x7fd724eefbed]
[1,0]<stderr>: 7  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteOperationERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseERNS0_10ProcessSetE+0x4c) [0x7fd724ef00cc]
[1,0]<stderr>: 8  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0xeaee8) [0x7fd724ec0ee8]
[1,0]<stderr>: 9  /usr/local/Python-3.10.5/lib/python3.10/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x1a52490) [0x7fd7ae793490]
[1,0]<stderr>:10  /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7fd7dfa0e609]
[1,0]<stderr>:11  /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fd7dfb48133]
[1,0]<stderr>:=================================
[1,0]<stderr>:[biomind:06502] *** Process received signal ***
[1,0]<stderr>:[biomind:06502] Signal: Segmentation fault (11)
[1,0]<stderr>:[biomind:06502] Signal code:  (-6)
[1,0]<stderr>:[biomind:06502] Failing at address: 0x3e500001966
[1,0]<stderr>:[biomind:06502] [ 0] [1,0]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7fd7dfa6c090]
[1,0]<stderr>:[biomind:06502] [ 1] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x1f018f)[0x7fd724fc618f]
[1,0]<stderr>:[biomind:06502] [ 2] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common11NCCLContext10ErrorCheckENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE12ncclResult_tRP8ncclComm+0x64)[0x7fd724f2d824]
[1,0]<stderr>:[biomind:06502] [ 3] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common13NCCLAllreduce7ExecuteERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x246)[0x7fd724f2ec56]
[1,0]<stderr>:[biomind:06502] [ 4] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteAllreduceERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x7d)[0x7fd724eefbed]
[1,0]<stderr>:[biomind:06502] [ 5] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteOperationERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseERNS0_10ProcessSetE+0x4c)[0x7fd724ef00cc]
[1,0]<stderr>:[biomind:06502] [ 6] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0xeaee8)[0x7fd724ec0ee8]
[1,0]<stderr>:[biomind:06502] [ 7] [1,1]<stderr>:==== backtrace (tid:   6591) ====
[1,1]<stderr>: 0  /usr/local/ucx-1.13.0/lib/libucs.so.0(ucs_handle_error+0x2dc) [0x7f8f260edbdc]
[1,1]<stderr>: 1  /usr/local/ucx-1.13.0/lib/libucs.so.0(+0x33dc7) [0x7f8f260eddc7]
[1,1]<stderr>: 2  /usr/local/ucx-1.13.0/lib/libucs.so.0(+0x340f4) [0x7f8f260ee0f4]
[1,1]<stderr>: 3  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x20b02b) [0x7f8f3660302b]
[1,1]<stderr>: 4  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x1fdc27) [0x7f8f365f5c27]
[1,1]<stderr>: 5  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x228d43) [0x7f8f36620d43]
[1,1]<stderr>: 6  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common13NCCLAllreduce7ExecuteERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x1c2) [0x7f8f36550bd2]
[1,1]<stderr>: 7  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteAllreduceERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x7d) [0x7f8f36511bed]
[1,1]<stderr>: 8  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteOperationERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseERNS0_10ProcessSetE+0x4c) [0x7f8f365120cc]
[1,1]<stderr>: 9  /usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0xeaee8) [0x7f8f364e2ee8]
[1,1]<stderr>:10  /usr/local/Python-3.10.5/lib/python3.10/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x1a52490) [0x7f8fbfdb5490]
[1,1]<stderr>:11  /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f8ff1030609]
[1,1]<stderr>:12  /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f8ff116a133]
[1,1]<stderr>:=================================
[1,1]<stderr>:[biomind:06503] *** Process received signal ***
[1,1]<stderr>:[biomind:06503] Signal: Segmentation fault (11)
[1,1]<stderr>:[biomind:06503] Signal code:  (-6)
[1,1]<stderr>:[biomind:06503] Failing at address: 0x3e500001967
[1,1]<stderr>:[biomind:06503] [ 0] [1,1]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7f8ff108e090]
[1,1]<stderr>:[biomind:06503] [ 1] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x20b02b)[0x7f8f3660302b]
[1,1]<stderr>:[biomind:06503] [ 2] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x1fdc27)[0x7f8f365f5c27]
[1,1]<stderr>:[biomind:06503] [ 3] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0x228d43)[0x7f8f36620d43]
[1,1]<stderr>:[biomind:06503] [ 4] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZN7horovod6common13NCCLAllreduce7ExecuteERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x1c2)[0x7f8f36550bd2]
[1,1]<stderr>:[biomind:06503] [ 5] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteAllreduceERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x7d)[0x7f8f36511bed]
[1,1]<stderr>:[biomind:06503] [ 6] [1,0]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x1a52490)[0x7fd7ae793490]
[1,0]<stderr>:[biomind:06502] [ 8] /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609)[0x7fd7dfa0e609]
[1,0]<stderr>:[biomind:06502] [ 9] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteOperationERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseERNS0_10ProcessSetE+0x4c)[0x7f8f365120cc]
[1,1]<stderr>:[biomind:06503] [ 7] [1,0]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7fd7dfb48133]
[1,0]<stderr>:[biomind:06502] *** End of error message ***
[1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so(+0xeaee8)[0x7f8f364e2ee8]
[1,1]<stderr>:[biomind:06503] [ 8] [1,1]<stderr>:/usr/local/Python-3.10.5/lib/python3.10/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x1a52490)[0x7f8fbfdb5490]
[1,1]<stderr>:[biomind:06503] [ 9] /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609)[0x7f8ff1030609]
[1,1]<stderr>:[biomind:06503] [10] [1,1]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f8ff116a133]
[1,1]<stderr>:[biomind:06503] *** End of error message ***
--------------------------------------------------------------------------
```

**Comment by maxhgerlach** [comment]
First warning: 
```[1,0]<stdout>:biomind:6502:6588 [0] misc/strongstream.cc:33 NCCL WARN Cuda failure 'CUDA driver is a stub library'
```
Looks like NCCL can't find the GPU driver. Please double check your setup.

**Comment by njzjz** [comment]
We are from a downstream package using horovod, and our users have reported the same error in https://github.com/deepmodeling/deepmd-kit/issues/1774 and https://github.com/deepmodeling/deepmd-kit/issues/1836. The error can be reproduced, and there is no problem with using GPUs when not using horovod.

The environment is as below:
TensorFlow 2.9.0, Horovod 0.24.3, CUDA Toolkit 11.6.0, NCCL 2.12.12, MPICH 3.3.2, mpi4py 3.1.3

**Comment by maxhgerlach** [comment]
Hmm, is there anything interesting in the more verbose logs when installing Horovod via `pip install -v`? Could there be some mismatch between CUDA, NCCL, TensorFlow?

**Comment by thomas-bouvier** [comment]
PyTorch 1.12 comes up with NCCL 2.10.3. I think that could cause some issues if Horovod was compiled against the system NCCL 2.12.12 because of the version mismatch.

**Comment by njzjz** [comment]
Here, a docker image can be used to reproduce the issue.
```bash
# go to horovod examples directory
cd horovod/examples/tensorflow2
docker run --gpus all -v `pwd`:/tmp -e "NCCL_DEBUG=info" ghcr.io/deepmodeling/deepmd-kit:2.1.3_cuda11.6_gpu horovodrun -n 2 python /tmp/tensorflow2_mnist.py
```

```
[1] c940b4ae7a81:36:37 [1] init.cc:255 NCCL WARN Cuda failure 'CUDA driver is a stub library'
```

Packages:
```sh
docker run ghcr.io/deepmodeling/deepmd-kit:2.1.3_cuda11.6_gpu pip list
```

<details>

```
Package                 Version
----------------------- ---------
absl-py                 1.0.0
aiohttp                 3.8.1
aiosignal               1.2.0
astunparse              1.6.3
async-timeout           4.0.1
attrs                   21.4.0
backrefs                5.0.1
blinker                 1.4
bracex                  2.1.1
brotlipy                0.7.0
cachetools              4.2.2
certifi                 2022.6.15
cffi                    1.15.0
charset-normalizer      2.0.4
click                   8.0.4
cloudpickle             2.0.0
conda                   4.13.0
conda-package-handling  1.8.1
cryptography            37.0.1
dargs                   0.2.6
deepmd-kit              2.1.3
dpdata                  0.2.5
flatbuffers             2.0
frozenlist              1.2.0
gast                    0.4.0
google-auth             2.6.0
google-auth-oauthlib    0.4.4
google-pasta            0.2.0
grpcio                  1.42.0
h5py                    3.6.0
horovod                 0.24.3
idna                    3.3
importlib-metadata      4.11.3
keras                   2.9.0
Keras-Preprocessing     1.1.2
Markdown                3.3.4
mkl-fft                 1.3.1
mkl-random              1.2.2
mkl-service             2.4.0
monty                   2022.1.19
mpi4py                  3.1.3
multidict               5.1.0
numpy                   1.22.3
oauthlib                3.2.0
opt-einsum              3.3.0
packaging               21.3
pip                     21.2.4
protobuf                3.20.1
psutil                  5.9.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycosat                 0.6.3
pycparser               2.21
PyJWT                   2.4.0
pyOpenSSL               22.0.0
pyparsing               3.0.4
PySocks                 1.7.1
python-hostlist         1.21
PyYAML                  6.0
requests                2.28.0
requests-oauthlib       1.3.0
rsa                     4.7.2
ruamel-yaml-conda       0.15.100
scipy                   1.7.3
setuptools              61.2.0
six                     1.16.0
tensorboard             2.9.0
tensorboard-data-server 0.6.0
tensorboard-plugin-wit  1.6.0
tensorflow              2.9.0
tensorflow-estimator    2.9.0
termcolor               1.1.0
tqdm                    4.64.0
typing_extensions       4.1.1
urllib3                 1.26.9
wcmatch                 8.2
Werkzeug                2.0.3
wheel                   0.37.1
wrapt                   1.13.3
yarl                    1.6.3
zipp                    3.8.0
```

</details>

```sh
docker run ghcr.io/deepmodeling/deepmd-kit:2.1.3_cuda11.6_gpu conda list
```

<details>

```sh
# packages in environment at /opt/deepmd-kit:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
abseil-cpp                20211102.0           hd4dd3e8_0
absl-py                   1.0.0                    pypi_0    pypi
aiohttp                   3.8.1           py310h7f8727e_1
aiosignal                 1.2.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async-timeout             4.0.1                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
backrefs                  5.0.1                    pypi_0    pypi
blas                      1.0                         mkl
blinker                   1.4             py310h06a4308_0
bracex                    2.1.1                    pypi_0    pypi
brotlipy                  0.7.0           py310h7f8727e_1002
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.18.1               h7f8727e_0
ca-certificates           2022.4.26            h06a4308_0
cachetools                4.2.2                    pypi_0    pypi
certifi                   2022.6.15       py310h06a4308_0
cffi                      1.15.0          py310hd667e15_1
charset-normalizer        2.0.4                    pypi_0    pypi
click                     8.0.4           py310h06a4308_0
cloudpickle               2.0.0                    pypi_0    pypi
conda                     4.13.0          py310h06a4308_0
conda-package-handling    1.8.1           py310h7f8727e_0
cryptography              37.0.1          py310h9ce1e76_0
cudatoolkit               11.6.0              hd754f66_10    deepmodeling
cudnn                     8.4.0.27             h5453bde_0    deepmodeling
dargs                     0.2.6                    pypi_0    pypi
dataclasses               0.8                pyh6d0b6a4_7
deepmd-kit                2.1.3           py310_0_cuda11.6_gpu    deepmodeling
dpdata                    0.2.5                    pypi_0    pypi
fftw                      3.3.9                h27cfd23_1
flatbuffers               2.0                      pypi_0    pypi
frozenlist                1.2.0           py310h7f8727e_1
gast                      0.4.0                    pypi_0    pypi
giflib                    5.2.1                h7b6447c_0
google-auth               2.6.0                    pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.42.0          py310hce63b2e_0
gsl                       2.7.1                h6e86dc7_1
h5py                      3.6.0           py310h18f346e_0
hdf5                      1.10.6               hb1b8bf9_0
horovod                   0.24.3          py310h50483eb_0    deepmodeling
icu                       68.1                 h2531618_0
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.11.3          py310h06a4308_0
intel-openmp              2021.4.0          h06a4308_3561
jpeg                      9e                   h7f8727e_0
jsoncpp                   1.9.4                hff7bd54_2
keras                     2.9.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
krb5                      1.19.2               hac12032_0
lammps                    20220623.0           h9954876_0    deepmodeling
ld_impl_linux-64          2.38                 h1181459_1
libcurl                   7.82.0               h0b77cf5_0
libdeepmd                 2.1.3            0_cuda11.6_gpu    deepmodeling
libedit                   3.1.20210910         h7f8727e_0
libev                     4.33                 h7f8727e_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0               h1234567_1
libgfortran-ng            7.5.0               ha8ba4b0_17
libgfortran4              7.5.0               ha8ba4b0_17
libgomp                   11.2.0               h1234567_1
libnghttp2                1.46.0               hce63b2e_0
libopenblas               0.3.18               hf726d26_0
libpng                    1.6.37               hbc83047_0
libprotobuf               3.20.1               h4ff587b_0
libssh2                   1.10.0               h8f2d780_0
libstdcxx-ng              11.2.0               h1234567_1
libtensorflow_cc          2.9.0           cuda116h4bf587c_0    deepmodeling
libuuid                   1.0.3                h7f8727e_2
markdown                  3.3.4           py310h06a4308_0
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0           py310h7f8727e_0
mkl_fft                   1.3.1           py310hd6ae3a3_0
mkl_random                1.2.2           py310h00e6091_0
monty                     2022.1.19                pypi_0    pypi
mpi                       1.0                       mpich
mpi4py                    3.1.3           py310h21fafdc_1    deepmodeling
mpich                     3.3.2                hc856adb_0
multidict                 5.1.0           py310h7f8727e_2
nccl                      2.12.12.1            h82364f3_0    deepmodeling
ncurses                   6.3                  h7f8727e_2
numpy                     1.22.3          py310hfa59a62_0
numpy-base                1.22.3          py310h9585f30_0
oauthlib                  3.2.0                    pypi_0    pypi
openssl                   1.1.1p               h5eee18b_0
opt-einsum                3.3.0                    pypi_0    pypi
opt_einsum                3.3.0              pyhd3eb1b0_1
packaging                 21.3                     pypi_0    pypi
pip                       21.2.4          py310h06a4308_0
plumed                    2.8.0                h5980d18_1    deepmodeling
protobuf                  3.20.1          py310h295c915_0
psutil                    5.9.0           py310h5eee18b_0
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycosat                   0.6.3           py310h7f8727e_0
pycparser                 2.21                     pypi_0    pypi
pyjwt                     2.4.0                    pypi_0    pypi
pylammps                  20220623.0         pyh29e1a88_0    deepmodeling
pyopenssl                 22.0.0                   pypi_0    pypi
pyparsing                 3.0.4                    pypi_0    pypi
pysocks                   1.7.1           py310h06a4308_0
python                    3.10.4               h12debd9_0
python-flatbuffers        2.0                pyhd3eb1b0_0
python-hostlist           1.21                     pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h7f8727e_1
requests                  2.28.0          py310h06a4308_0
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
ruamel_yaml               0.15.100        py310h7f8727e_0
scipy                     1.7.3           py310hfa59a62_0
setuptools                61.2.0          py310h06a4308_0
six                       1.16.0                   pypi_0    pypi
snappy                    1.1.9                h295c915_0
sqlite                    3.38.5               hc218d9a_0
tensorboard               2.9.0                    pypi_0    pypi
tensorboard-data-server   0.6.0           py310hca6d32c_0
tensorboard-plugin-wit    1.6.0                    pypi_0    pypi
tensorflow                2.9.0           cuda116py310h5dcf97d_0    deepmodeling
tensorflow-estimator      2.9.0           cuda116py310h81bfea3_0    deepmodeling
termcolor                 1.1.0           py310h06a4308_1
tk                        8.6.12               h1ccaba5_0
tqdm                      4.64.0          py310h06a4308_0
typing-extensions         4.1.1                    pypi_0    pypi
typing_extensions         4.1.1              pyh06a4308_0
tzdata                    2022a                hda174b7_0
urllib3                   1.26.9          py310h06a4308_0
wcmatch                   8.2                      pypi_0    pypi
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.37.1                   pypi_0    pypi
wrapt                     1.13.3          py310h7f8727e_2
xz                        5.2.5                h7f8727e_1
yaml                      0.2.5                h7b6447c_0
yarl                      1.6.3           py310h7f8727e_1
zipp                      3.8.0           py310h06a4308_0
zlib                      1.2.12               h7f8727e_2
```

</details>

Note: Lots of packages, like TensorFlow, NCCL, horovod, are built by me. I can provide the build script if it is helpful.

**Comment by otaj** [comment]
I'm just chiming in here, that the original issue is here https://github.com/NVIDIA/nccl/issues/658

**Comment by nvcastet** [comment]
@njzjz How do you build NCCL? Are you setting the variable `CUDARTLIB` or you use the default (static cudart)?

**Comment by njzjz** [comment]
> @njzjz How do you build NCCL? Are you setting the variable `CUDARTLIB` or you use the default (static cudart)?

I follow the script from [conda-forge](https://github.com/conda-forge/nccl-feedstock/blob/main/recipe/build.sh), which sets `CUDARTLIB="cudart"`.

**Comment by cliffwoolley** [comment]
Thanks to @nvcastet @otaj for cross-referencing this issue and calling it to my attention.

The conda-forge recipe linked above, @njzjz , does use `CUDARTLIB="cudart"`, instead of leaving it at the default (and best-practice) `CUDARTLIB="cudart_static"`.  So this is indeed a duplicate of https://github.com/NVIDIA/nccl/issues/658 , and you could work around it by simply dropping the CUDARTLIB="cudart" argument from your Makefile.  Fixing the original issue 658 is still on my backlog.

**Comment by leofang** [comment]
Hi @cliffwoolley, what if on the conda-forge side we compile NCCL using CUDA 11.3, but still allow dynamic cudart? Would it work? Because if so that would solve both this issue and https://github.com/conda-forge/nccl-feedstock/issues/62.

**Comment by leofang** [comment]
(But I agree, the conda-forge NCCL is deviating from the NV libraries' standard practice. In our defense, though, linking to cudart_static is not the proper conda-forge practice as per [CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md)...)

**Comment by leofang** [comment]
@njzjz just curious, which CUDA version did you use to build your NCCL?

**Comment by tgaddair** [comment]
@cliffwoolley I'm seeing this issue pop up with the version of NCCL shipped in the `nvidia/cuda:11.6.1-cudnn8-devel-ubuntu18.04` image on Docker Hub. Is this a known issue with this image?

**Comment by njzjz** [comment]
> @njzjz just curious, which CUDA version did you use to build your NCCL?

@leofang I built NCCL using CUDA 11.6.

**Comment by leofang** [comment]
Thanks, @njzjz, so what I asked Cliff above would not work...

**Comment by njzjz** [comment]
`CUDARTLIB="cudart"` does work for me.

**Comment by cliffwoolley** [comment]
We will test https://github.com/cliffwoolley/nccl/commit/b68eb91b5028e94388918de7d11e0da771329bb9 for inclusion in a future NCCL.  But it should do what you want, if cudart_static isn't usable for you for some reason.

**Comment by ZeroExistence** [comment]
Hello, just adding this information here.
https://github.com/horovod/horovod/issues/3752#issuecomment-1285423023

If you are using CUDA11.6, it might be better to downgrade the NCCL. I was able to use horovod-v0.24.3 and horovod-v0.26.1 with Pytorch-v1.13.0 after downgrading the NCCL from 2.12 to 2.11 (`2.11.4-1+cuda11.6`). By default, the NVIDIA hosted cuda11.6 images were bundled with NCCL 2.12.

**Comment by njzjz** [comment]
I believe the problem was fixed in https://github.com/NVIDIA/nccl/commit/78313a6d216486efebdba96a3c367fe763b26d26. I have not tested it yet.
