### ISSUE TITLE
ROCm-Compilation fails for 0.28.0

### ISSUE THREAD

**Issue by will-HPE** [horovod/horovod#3927]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version: 0.28.0
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. Spark / PySpark version:
9. Ray version:
10. OS and version:
11. GCC version:
12. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? N/A
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? N/A
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.
When building horovod-0.28.0 an update to torch/cuda_util.cc causes torch/hip_util.cc to fail build:
```
In file included from /tmp/pip-req-build-favtnjl1/horovod/torch/../common/ops/collective_operations.h:26,
                     from /tmp/pip-req-build-favtnjl1/horovod/torch/mpi_ops_v2_hip.cc:33:
    /tmp/pip-req-build-favtnjl1/horovod/torch/../common/ops/../half.h: In function 'void horovod::common::HalfBits2Float(const short unsigned int*, float*)':
    /tmp/pip-req-build-favtnjl1/horovod/torch/../common/ops/../half.h:76:11: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       76 |   *res = *reinterpret_cast<float const*>(&f);
          |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /tmp/pip-req-build-favtnjl1/horovod/torch/hip_util.cc:34:28: error: expected ')' before '*' token
       34 | typedef hipError_t (CUDAAPI *PFN_cuCtxGetDevice)(hipDevice_t* device);
          |                    ~       ^~
          |                            )
    /tmp/pip-req-build-favtnjl1/horovod/torch/hip_util.cc:36:8: error: 'PFN_cuCtxGetDevice' does not name a type; did you mean 'hipCtxGetDevice'?
       36 | static PFN_cuCtxGetDevice pfn_cuCtxGetDevice = nullptr;
          |        ^~~~~~~~~~~~~~~~~~
          |        hipCtxGetDevice
    /tmp/pip-req-build-favtnjl1/horovod/torch/hip_util.cc: In function 'void horovod::torch::initialize_driver_api()':
    /tmp/pip-req-build-favtnjl1/horovod/torch/hip_util.cc:47:3: error: 'pfn_cuCtxGetDevice' was not declared in this scope; did you mean 'hipCtxGetDevice'?
       47 |   pfn_cuCtxGetDevice = (PFN_cuCtxGetDevice) dlsym(cudalib, "hipCtxGetDevice");
          |   ^~~~~~~~~~~~~~~~~~
          |   hipCtxGetDevice
    /tmp/pip-req-build-favtnjl1/horovod/torch/hip_util.cc:47:25: error: 'PFN_cuCtxGetDevice' was not declared in this scope; did you mean 'hipCtxGetDevice'?
       47 |   pfn_cuCtxGetDevice = (PFN_cuCtxGetDevice) dlsym(cudalib, "hipCtxGetDevice");
          |                         ^~~~~~~~~~~~~~~~~~
          |                         hipCtxGetDevice
    /tmp/pip-req-build-favtnjl1/horovod/torch/hip_util.cc: In constructor 'horovod::torch::with_device::with_device(int)':
    /tmp/pip-req-build-favtnjl1/horovod/torch/hip_util.cc:61:16: error: 'pfn_cuCtxGetDevice' was not declared in this scope; did you mean 'hipCtxGetDevice'?
       61 |     auto err = pfn_cuCtxGetDevice(&cudev);
          |                ^~~~~~~~~~~~~~~~~~
          |                hipCtxGetDevice
```
 This happens because hip doesn't support PFN_cuCtxGetDevice (it does support cuCtxGetDevice though).
 A quick workaround that seems to alleviate the issues is to enclose the offending code with `#ifndef __HIP_PLATFORM_HCC__`.

**Comment by maxhgerlach** [comment]
This is due to changes from this PR, which fixed a problem with CUDA 12.x: https://github.com/horovod/horovod/pull/3912 Unfortunately we don't have any ROCm-based CI.

@rsanthanam-amd, @ronakmal, @weihanmines: Tagging you because you've contributed ROCm-specific fixes in the past year. Is there a chance you could look into this issue or raise it within AMD?

**Comment by will-HPE** [comment]
I think if you look here [rocmdocs](https://rocmdocs.amd.com/projects/HIPIFY/en/latest/tables/CUDA_Driver_API_functions_supported_by_HIP.html) you'll see that `PFN_cuCtxGetDevice` isn't supported while the quite similar `cuCtxGetDevice` -> `hipCtxGetDevice` is.

**Comment by will-HPE** [comment]
I wasn't able to check in my changes but what I changed is this:

**Comment by paklui** [comment]
I stumble upon it this morning when compiling horovod v28.0.0 for ROCm.
using the v28.0.0 release, If i remove `CUDAAPI` I was able to compile, haven't tried running it though.

```
(hugging-venv-pytorch2) [paklui@login2.crusher ~/horovod]$ git diff
diff --git a/horovod/mxnet/cuda_util.cc b/horovod/mxnet/cuda_util.cc
index 7bb3c1b..474ba03 100644
--- a/horovod/mxnet/cuda_util.cc
+++ b/horovod/mxnet/cuda_util.cc
@@ -30,7 +30,7 @@ namespace horovod {
 namespace mxnet {

 #if HAVE_CUDA
-typedef CUresult (CUDAAPI *PFN_cuCtxGetDevice)(CUdevice* device);
+typedef CUresult (*PFN_cuCtxGetDevice)(CUdevice* device);
 static void* cudalib = nullptr;
 static PFN_cuCtxGetDevice pfn_cuCtxGetDevice = nullptr;

diff --git a/horovod/torch/cuda_util.cc b/horovod/torch/cuda_util.cc
index 522cc24..5f34aa3 100644
--- a/horovod/torch/cuda_util.cc
+++ b/horovod/torch/cuda_util.cc
@@ -30,7 +30,7 @@ namespace horovod {
 namespace torch {

 #if HAVE_GPU
-typedef CUresult (CUDAAPI *PFN_cuCtxGetDevice)(CUdevice* device);
+typedef CUresult (*PFN_cuCtxGetDevice)(CUdevice* device);
 static void* cudalib = nullptr;
 static PFN_cuCtxGetDevice pfn_cuCtxGetDevice = nullptr;

```

**Comment by paklui** [comment]
I tried my work around and the fix by @will-hpe, they both compiled fine
but when i try to run the benchmark I see undefined symbol below. 
any ideas? thanks in advance.

```
$ python3 pytorch_synthetic_benchmark.py --batch-size=96 --fp16-allreduce --model=resnet50
Traceback (most recent call last):
  File "pytorch_synthetic_benchmark.py", line 7, in <module>
    import horovod.torch as hvd
  File "/opt/conda/lib/python3.8/site-packages/horovod/torch/__init__.py", line 31, in <module>
    from horovod.torch import elastic
  File "/opt/conda/lib/python3.8/site-packages/horovod/torch/elastic/__init__.py", line 17, in <module>
    from horovod.torch.mpi_ops import init, shutdown
  File "/opt/conda/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 36, in <module>
    raise e
  File "/opt/conda/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 33, in <module>
    from horovod.torch import mpi_lib_v2 as mpi_lib
ImportError: /opt/conda/lib/python3.8/site-packages/horovod/torch/mpi_lib_v2.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN7horovod6common10GPUContextD1Ev

$ echo _ZN7horovod6common10GPUContextD1Ev|c++filt
horovod::common::GPUContext::~GPUContext()
```

**Comment by will-HPE** [comment]
> I tried my work around and the fix by @will-HPE, they both compiled fine but when i try to run the benchmark I see undefined symbol below. any ideas? thanks in advance.
> 
> ```
> $ python3 pytorch_synthetic_benchmark.py --batch-size=96 --fp16-allreduce --model=resnet50
> Traceback (most recent call last):
>   File "pytorch_synthetic_benchmark.py", line 7, in <module>
>     import horovod.torch as hvd
>   File "/opt/conda/lib/python3.8/site-packages/horovod/torch/__init__.py", line 31, in <module>
>     from horovod.torch import elastic
>   File "/opt/conda/lib/python3.8/site-packages/horovod/torch/elastic/__init__.py", line 17, in <module>
>     from horovod.torch.mpi_ops import init, shutdown
>   File "/opt/conda/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 36, in <module>
>     raise e
>   File "/opt/conda/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 33, in <module>
>     from horovod.torch import mpi_lib_v2 as mpi_lib
> ImportError: /opt/conda/lib/python3.8/site-packages/horovod/torch/mpi_lib_v2.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN7horovod6common10GPUContextD1Ev
> 
> $ echo _ZN7horovod6common10GPUContextD1Ev|c++filt
> horovod::common::GPUContext::~GPUContext()
> ```

Does the same benchmark work with 0.27.0?

**Comment by paklui** [comment]
> Does the same benchmark work with 0.27.0?
v0.27.0 failed with different error for me

**Comment by will-HPE** [comment]
Does that .so show something like this:
```
  896: 00000000000dc8a0  1455 FUNC    GLOBAL DEFAULT   12 horovod::common::GPUContext::~GPUContext()
   982: 00000000000dc8a0  1455 FUNC    GLOBAL DEFAULT   12 horovod::common::GPUContext::~GPUContext()
  2374: 00000000000dc8a0  1455 FUNC    GLOBAL DEFAULT   12 horovod::common::GPUContext::~GPUContext()
  2663: 00000000000dc8a0  1455 FUNC    GLOBAL DEFAULT   12 horovod::common::GPUContext::~GPUContext()
```

**Comment by paklui** [comment]
i tried readelf and seem to get undefined symbol there. the line is truncated but it should be for ~GPUContext().
```
root@asdf:/var/lib/jenkins/horovod/examples/pytorch# readelf -a /opt/conda/lib/python3.8/site-packages/horovod/torch/mpi_lib_v2.cpython-38-x86_64-linux-gnu.so |grep GPUC
   136: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZN7horovod6common10GPUCo
   140: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZN7horovod6common10GPUCo
   141: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZN7horovod6common10GPUCo
  3507: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZN7horovod6common10GPUCo
  3593: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZN7horovod6common10GPUCo
  3594: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZN7horovod6common10GPUCo
```

maybe there's linker or rpath issue? I am not sure some flags you could recommend for me to try to set, here's what I use:

```
root@asdf:/var/lib/jenkins/horovod # VERBOSE=1 CXXFLAGS=-D__HIP_PLATFORM_HCC__ CFLAGS=-D__HIP_PLATFORM_HCC__ HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_GPU=ROCM HOROVOD_ROCM_PATH=/opt/rocm pip install --no-cache-dir horovod
Requirement already satisfied: cloudpickle in /opt/conda/lib/python3.8/site-packages (from horovod) (2.2.1)
Requirement already satisfied: psutil in /opt/conda/lib/python3.8/site-packages (from horovod) (5.9.5)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.8/site-packages (from horovod) (6.0)
Requirement already satisfied: packaging in /opt/conda/lib/python3.8/site-packages (from horovod) (23.0)
Requirement already satisfied: cffi>=1.4.0 in /opt/conda/lib/python3.8/site-packages (from horovod) (1.15.1)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.8/site-packages (from cffi>=1.4.0->horovod) (2.21)
Building wheels for collected packages: horovod
  Building wheel for horovod (setup.py) ... done
  Created wheel for horovod: filename=horovod-0.28.0-cp38-cp38-linux_x86_64.whl size=19843473 sha256=a1edfd57ec10ba6673658e20a7e8240cca8296b1b61f273ee1e23890f11ba51b
  Stored in directory: /tmp/pip-ephem-wheel-cache-bnwhfxwr/wheels/ab/3a/7f/dd43d63c36e0f90d5c1ab96296967c3432ce4b185b13c7748d
Successfully built horovod
Installing collected packages: horovod
Successfully installed horovod-0.28.0
```

thanks..

**Comment by will-HPE** [comment]
Paklui,

**Comment by maxhgerlach** [comment]
@paklui, Will's fix is merged now. If you like, you could do a quick check to confirm that Horovod master now works for you.

**Comment by paklui** [comment]
I checked with the latest master c1a88083670a848d28ceab20090eeb858e251bf0 and horovod installs and runs fine for me. Thanks @will-HPE and @maxhgerlach

**Comment by will-HPE** [comment]
I can't help but wonder if we are going to be revisiting this, backing the changes and getting `cuCtxGetDevice` to work.

**Comment by coreyjadams** [comment]
Sorry to post on a closed issue, but it seems the AMD experts are here already.  I'll open a new one if necessary.  I'm trying to run horovod.torch on AMD Mi250 and came across this thread.  I have an error with a missing symbol:

```
>>> import horovod.torch as hvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/jlse-fs0/users/corey.adams/miniconda3/envs/rocm/lib/python3.9/site-packages/horovod-0.28.1-py3.9-linux-x86_64.egg/horovod/torch/__init__.py", line 31, in <module>
    from horovod.torch import elastic
  File "/gpfs/jlse-fs0/users/corey.adams/miniconda3/envs/rocm/lib/python3.9/site-packages/horovod-0.28.1-py3.9-linux-x86_64.egg/horovod/torch/elastic/__init__.py", line 17, in <module>
    from horovod.torch.mpi_ops import init, shutdown
  File "/gpfs/jlse-fs0/users/corey.adams/miniconda3/envs/rocm/lib/python3.9/site-packages/horovod-0.28.1-py3.9-linux-x86_64.egg/horovod/torch/mpi_ops.py", line 36, in <module>
    raise e
  File "/gpfs/jlse-fs0/users/corey.adams/miniconda3/envs/rocm/lib/python3.9/site-packages/horovod-0.28.1-py3.9-linux-x86_64.egg/horovod/torch/mpi_ops.py", line 33, in <module>
    from horovod.torch import mpi_lib_v2 as mpi_lib
ImportError: /gpfs/jlse-fs0/users/corey.adams/miniconda3/envs/rocm/lib/python3.9/site-packages/horovod-0.28.1-py3.9-linux-x86_64.egg/horovod/torch/mpi_lib_v2.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN7horovod6common10GPUContextD1Ev
```

I've got the master branch of horovod and confirmed the changes by @will-HPE were merged into my branch.  I did have to modify the `setup.py` script to enable HIP compilation:

```bash
❯ cat setup.py-diff.txt
diff --git a/setup.py b/setup.py
index b890286..a297c98 100644
--- a/setup.py
+++ b/setup.py
@@ -113,6 +113,8 @@ class custom_build_ext(build_ext):
 
         cmake_args = ['-DCMAKE_BUILD_TYPE=' + config,
                       '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_{}={}'.format(config.upper(), build_dir),
+                      '-DCMAKE_C_FLAGS=-D__HIP_PLATFORM_AMD__',
+                      '-DCMAKE_CXX_FLAGS=-D__HIP_PLATFORM_AMD__',
                       '-DPYTHON_EXECUTABLE:FILEPATH=' + sys.executable]
 
         make_args = ['-j8'] if not os.environ.get('MAKEFLAGS') else []

```

And I'm compiling like so, from the source repo:
```
HOROVOD_GPU=ROCM python setup.py install
```

Any ideas why I'm still missing a destructor on horovod::common::GPUContext?  Thanks!
