### ISSUE TITLE
Unable to run Horovod Pytorch on AMD AMI100 GPUs

### ISSUE THREAD

**Issue by kf-cuanschutz** [horovod/horovod#4019]
**Environment:**
1. Framework: PyTorch
2. Framework version: Pytorch 1.13.0
3. Horovod version: 0.25.0
4. MPI version: OpenMPI 4.1.1
5. CUDA version: 12.1.1
6. NCCL version: 2.18.3-1
7. Python version: 3.10.0
8. Spark / PySpark version:
9. Ray version:
10. OS and version: Red Hat Enterprise Linux 8.4 (Ootpa)
11. GCC version: 11.2.0
12. CMake version: 3.27.7
13. ROCm 5.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? N/A
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? N/A
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Bug report:**
I was able to build horovod on an HPC cluster, thanks to this thread mostly: https://github.com/horovod/horovod/issues/3537

My final command to build it is below and I have attached the full log of the build as well.

```bash
HOROVOD_WITH_PYTORCH=1 HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_GPU=ROCM HOROVOD_ROCM_HOME=$ROCM_PATH HOROVOD_WITH_MPI=1 pip install --target=$PIP_INSTALL_DIR -v git+https://github.com/horovod/horovod.git@refs/pull/3588/head --upgrade >& make_horovod_update_V9.log &
```

According to the log, the build was successful. Thus I tried to check the build shortly afterwards using the command below.
The outcome is attached with this thread as well.

```bash
horovodrun --check-build
```

Then I went to try the following example : https://github.com/horovod/horovod/blob/master/examples/pytorch/pytorch_mnist.py

When running the horovod command, I get an `Unable to find code object for all current devices!` error. See below:

```bash
pytorch]$export AMDGPU_TARGETS="gfx908"
pytorch]$export GFX_ARCH=gfx908
pytorch]$ horovodrun -np 1 -H localhost:1 pytorch_mnist.py
[1,0]<stderr>:"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 2386976 on node c3gpu-c2-u29 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```

Does anyone know what can be the problem?
Here are all the attached files.
[check_build.log](https://github.com/horovod/horovod/files/14103329/check_build.log)
[horovod_build_logs_V9.log](https://github.com/horovod/horovod/files/14103330/horovod_build_logs_V9.log)

**Comment by kf-cuanschutz** [comment]
I fixed the issue by adding "CUDA_VISIBLE_DEVICES=1". Full command below:


```bash
CUDA_VISIBLE_DEVICES=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_GPU=ROCM HOROVOD_ROCM_HOME=$ROCM_PATH HOROVOD_WITH_MPI=1  AMD_LOG_LEVEL=1 ROC_ENABLE_PRE_VEGA=1  AMDGPU_TARGETS="gfx803" HSA_OVERRIDE_GFX_VERSION=10.3.0  horovodrun -np 1 -H localhost:2 pytorch_mnist.py
```

**Comment by kf-cuanschutz** [comment]
Closing the issue.
