### ISSUE TITLE
Distributed training hangs in docker RoCE environment

### ISSUE THREAD

**Issue by EdwardZhang88** [horovod/horovod#468]
Hi, @alsrgv I am currently stuck with distributed training using Horovod in a docker RoCE environment. I have two 4-Nvidia-Tesla-M40-GPU nodes, each of which has 2 NICs, one Mellanox RoCE NIC(eno2.100) and the other one regular Ethernet NIC(eth0). I have installed and started nv_peer_memory on both servers to enable GPUDirect RDMA; the same Mellanox OFED drive is also installed on top of the latest Horovod image. I have managed to get the below settings run through.
1. SSH passwordless login is successful inside the containers from the primary node to the secondary one.
2. The Mellanox NCIs are well set up as the ib_write_bw test inside the containers are also good.
3. Distributed training is OK when I submit the commad with NCCL_IB_DISABLE=1 and NCCL_SOCKETIF_NAME=eno2.100; Actually, it has achieved a 6x time speed up compared to using NCCL_SOCKETIF_NAME=eth0 with everything else unchanged.

However, no matter what value combination I give to enable RoCE training, the MPI task will always get hung with the same warning message below.

4.1. NCCL_IB_DISABLE=0 and NCCL_IB_CUDA_SUPPORT=1
On Secondary node
`nvidia-docker run --rm -it --privileged --network=host -v /root/.ssh:/root/.ssh uber/horovod_custom_ib:0.13.11-tf1.10.0-torch4.0-py2.7 bash -c "/usr/sbin/sshd -p 12345; sleep infinity"`
On Primary node
`nvidia-docker run --rm -it --privileged --network=host -v /root/.ssh:/root/.ssh uber/horovod_custom_ib:0.13.11-tf1.10.0-torch4.0-py2.7`
`mpirun -np 2 -H 11.11.72.23:1,11.11.71.60:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x NCCL_IB_DISABLE=0 -x NCCL_IB_CUDA_SUPPORT=1 -x NCCL_SOCKET_IFNAME=eno2.100 -x NCCL_IB_HCA=mlx5_0 -x LD_LIBRARY_PATH -x PATH -mc pml ob1 -mca btl ^openib -mca btl_tcp_if_exclude lo,docker0 -mca plm_rsh_args "-p 12345 -vvvv" python /training_scripts/tensorflow_mnist_estimator.py`

`INFO Ring 00 : 	0	1

 INFO 0 -> 1 via NET/IB/0/GDRDMA

 INFO 1 -> 0 via NET/IB/0/GDRDMA
 ... ...
transport/net_ib.cu:781 WARN NET/IB : Got completion with error 12, opcode 1, len 0, vendor err 129`

4.2. NCCL_IB_DISABLE=0 and NCCL_IB_CUDA_SUPPORT=0
The only thing I changed is to set NCCL_IB_CUDA_SUPPORT=0
`mpirun -np 2 -H 11.11.72.23:1,11.11.71.60:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x NCCL_IB_DISABLE=0 -x NCCL_IB_CUDA_SUPPORT=0 -x NCCL_SOCKET_IFNAME=eno2.100 -x NCCL_IB_HCA=mlx5_0 -x LD_LIBRARY_PATH -x PATH -mc pml ob1 -mca btl ^openib -mca btl_tcp_if_exclude lo,docker0 -mca plm_rsh_args "-p 12345 -vvvv" python /training_scripts/tensorflow_mnist_estimator.py`

`INFO Ring 00 : 	0	1

 INFO 0 -> 1 via NET/IB/0

 INFO 1 -> 0 via NET/IB/0
 ... ...
transport/net_ib.cu:781 WARN NET/IB : Got completion with error 12, opcode 1, len 0, vendor err 129`

I have also tried what is suggested in other threads (#162 and #272 )but to no vail.
Below is the detail of the GPU and the Mellanox NIC I am using. The server OS is CentOS Linux release 7.4.1708 (Core).
`nvidia-smi topo -m

		GPUO	GPU1	GPU2	GPU3	mlx5_0
GPU0	X       PHB     SYS     SYS     PHB
GPU1	PHB     X       SYS     SYS     PHB
GPU2	SYS     SYS     X       PHB     SYS
GPU3	SYS     SYS     PHB     X       SYS
mlx5_0	PHB     PHB     SYS     SYS     X
`

` lspci -v|grep Mellanox

01:00.0 Ethernet controller: Mellanox Techonologies MT27710 Family [ConnextX-4 Lx]
        Subsystem: 	Mellanox Techonologies Device 0001
`	
At this point, I really don't know what to look into next. Appreciate if you can shed some light here. Thanks!

**Comment by alsrgv** [comment]
@EdwardZhang88, thanks for the detailed question!  Which Ethernet switch are you using for RoCE?  I've seen this issue happen on a shallow-buffer switch.

**Comment by LiweiPeng** [comment]
Because you are using RoCE, the proper OpenMPI options for RoCE needs to be specified. See this OpenMPI page for details: https://www.open-mpi.org/faq/?category=openfabrics#ompi-over-roce.

**Comment by EdwardZhang88** [comment]
Hi @LiweiPeng Thanks for you reply. I tried replacing  '--mca btl ^openib' 
with 
'--mca btl openib,self,sm --mca btl_openib_cpc_include rdmacm --mca btl_openib_rroce_enable 1 --mca btl_openib_want_cuda_gdr 1 '
but it ended up with an error in MPI_Init as below. 
`Framework: btl
 Component: openib
mca_bml_base_open() failed
--> Returned "Not Found" (13) instead of "Success" (0)
`
According to [this post by alsrgv](https://github.com/uber/horovod/issues/74#issuecomment-343833576), it should be OK that only NCCL run over RoCE while openMPI uses plain sockets. So this might not be the cause of the problem I am facing.

**Comment by EdwardZhang88** [comment]
Thanks @alsrgv . I will try to figure out if it's a pure network setting issue or not.

**Comment by EdwardZhang88** [comment]
It turns out that the default NCCL_IB_GID_INDEX=0 was wrong as the GID is actually 3 in my case. I accidentally came to find this when running a ib_write_bw test. After I append NCCL_IB_GID_INDEX=3 to my previous command, both NCCL_IB_CUDA_SUPPORT=0 and NCCL_IB_CUDA_SUPPORT=1 work like a charm.
<img width="582" alt="db29cf73dd90f69bf36011596c4d3da8" src="https://user-images.githubusercontent.com/28944236/44965431-28287600-af68-11e8-9816-caef3d782ad4.png">
@alsrgv I guess it's not a network issue then. However, I don't know if this value is configurable.
Hi @LiweiPeng I noticed that you also set NCCL_IB_GID_INDEX=3 in your #452 . I am wondering if you can explain what the purpose of this attribute is and how to standardize it among multiple nodes in a cluster. Thanks.

**Comment by tingweiwu** [comment]
@EdwardZhang88 could you tell me how to do the `ib_write_bw` test inside the containers?
I run `ib_write_bw`  in my container and it print `bash: ib_write_bw: command not found
 ` 
thanks a lot if you reply.

**Comment by tingweiwu** [comment]
@EdwardZhang88 thanks a lot. I have add the OFED drive on the top of `uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5`.

now I can use `ibstatus` in the new images but when I run the examples. it occurs that
```
/examples# mpirun -np 1 -H localhost:1 python tensorflow_mnist.py
Traceback (most recent call last):
  File "tensorflow_mnist.py", line 17, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[36859,1],0]
  Exit code:    1
--------------------------------------------------------------------------

```
here is my Dockefile
```
FROM horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5
ENV MOFED_DIR MLNX_OFED_LINUX-4.2-1.0.0.0-ubuntu16.04-x86_64
ENV MOFED_SITE_PLACE MLNX_OFED-4.2-1.0.0.0
ENV MOFED_IMAGE MLNX_OFED_LINUX-4.2-1.0.0.0-ubuntu16.04-x86_64.tgz
WORKDIR /tmp/
RUN apt-get update && apt-get install -y --no-install-recommends \
        wget \
        net-tools \
        ethtool \
        perl \
        lsb-release \
        iproute2 \
        pciutils \
        libnl-route-3-200 \
        kmod \
        libnuma1 \
        lsof \
        linux-headers-4.4.0-92-generic \
        python-libxml2 
RUN wget http://content.mellanox.com/ofed/${MOFED_SITE_PLACE}/${MOFED_IMAGE} && \
        tar -xzvf ${MOFED_IMAGE} && \
        ${MOFED_DIR}/mlnxofedinstall --user-space-only --without-fw-update --all -q 
```

Could you share your Dockerfile with me, Thanks?

**Comment by Eric716** [comment]
What's your NCCL version?
