### ISSUE TITLE
ERROR: TensorFlow device is being mapped to multiple CUDA devices

### ISSUE THREAD

**Issue by zqlai** [horovod/horovod#676]
I've been trying to transform the [tensorflow.resnet](https://github.com/tensorflow/models/tree/master/official/resnet) model to Horovod version following the [Horovod usage](https://github.com/uber/horovod#usage) steps, mainly by modifying the [resnet_run_loop.py](https://github.com/tensorflow/models/blob/master/official/resnet/resnet_run_loop.py). 
When I tried to test the modified resnet on 2 K80 GPUs on a single machine (it has 4 GPUs) by:
```
$ mpirun -np 2 \
    python cifar10_main.py \
        --data_dir='/.../datasets' \
        --model_dir='/.../checkpoints' \
```
I got the following two types of error:

- many out-of-memory errors in the initialization stage of Tensorflow
```
failed to allocate 10.41G (11172973568 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
failed to allocate 9.36G (10055675904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
failed to allocate 8.43G (9050107904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
failed to allocate 7.58G (8145096704 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
......
```
- GPU-mapping error in the training stage:
```
tensorflow.python.framework.errors_impl.AlreadyExistsError: TensorFlow device (GPU:0) is being
 mapped to multiple CUDA devices (1 now, and 0 previously), which is not supported. This may be the 
result of providing different GPU configurations (ConfigProto.gpu_options, for example different 
visible_device_list) when creating multiple Sessions in the same process. This is not  currently supported, 
see https://git    hub.com/tensorflow/tensorflow/issues/19083
```
The complete output log is attached as 
[output.log](https://github.com/uber/horovod/files/2647861/output.log).

BTW, when I launched the same program on 1 GPU by `-np 1`, it worked fine. The output log is 
[output-on-1-GPUs.log](https://github.com/uber/horovod/files/2647880/output-on-1-GPUs.log).

Any suggestion is appreciated.

**Comment by tgaddair** [comment]
Hey @zqlai, to verify, does your training script have this piece of code in it:

```
# Pin GPU to be used to process local rank (one GPU per process)
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())
```

Do the tensorflow examples included with Horovod work in your environment?

**Comment by zqlai** [comment]
@tgaddair Thanks for your response.
Yes, I configured the gpu_options as:
```
  session_config = tf.ConfigProto()
  session_config.gpu_options.allow_growth = True
  session_config.gpu_options.visible_device_list = str(hvd.local_rank())
```
Then pass the `session_config` to `run_config` as
```
  run_config = tf.estimator.RunConfig(
  #    train_distribute=distribution_strategy,
      session_config=session_config,
      save_checkpoints_secs=60*60*24)
```
As I found the ResNet is a distributed version using Tensorflow's distribution strategy,  I commented the ` train_distribute=distribution_strategy`, but not sure if this worked.

The modified `resnet_run_loop.py` is here [resnet_run_loop.py.txt](https://github.com/uber/horovod/files/2651564/resnet_run_loop.py.txt). You can see my modifications in the `resnet_main()` function from Line 445.

My horovod version is 0.15, and the mnist example works well in the distributed mode.
Also, the same ResNet program on 1 GPU worked well. 
So, I think the the Horovod is fine.

**Comment by alsrgv** [comment]
@zqlai, seems that some code in the script initializes all GPUs, and the code to pin TF to specific GPU is executed too late.  Which version of TensorFlow are you using?

**Comment by zqlai** [comment]
@alsrgv Thanks for your comment.
My TensorFlow version is 1.11.0.
Your analysis makes sense. From the [output.log](https://github.com/uber/horovod/files/2647861/output.log) , we can see multiple 'Adding visible gpu devices' logs, firstly:
```
2018-12-05 16:02:24.047159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0, 1, 2, 3
2018-12-05 16:02:24.047155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0, 1, 2, 3
```
and then:
```
2018-12-05 16:02:38.714632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-12-05 16:02:38.728954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 1
```
Unfortunately， I have not figured out if the TensorFlow or the [tensorflow.resnet](https://github.com/tensorflow/models/tree/master/official/resnet) model initializes all the GPUs.

Another weird thing is that, the `visible_device_list` of gpu_options seems already set up to 0 or 1, as the begin of [output.log](https://github.com/uber/horovod/files/2647861/output.log) showing:
```
I1205 16:02:09.299397 47693075944192 tf_logging.py:115] Using config: {'_save_checkpoints_secs': 86400, '_session_config': gpu_options {
  allow_growth: true
  visible_device_list: "0"
}
I1205 16:02:09.299473 46992336483072 tf_logging.py:115] Using config: {'_save_checkpoints_secs': 86400, '_session_config': gpu_options {
  allow_growth: true
  visible_device_list: "1"
}
```
why it still went to initialize all the four GPUs? 

Looking forward to your comments.

**Comment by libliang** [comment]
I met the same issue as zqlai, is there any suggestions?

**Comment by alsrgv** [comment]
Other suspicion falls on `device_lib.list_local_devices()` function. And surely, it is used in this repo:
```python
logs/logger.py:  local_device_protos = device_lib.list_local_devices(session_config)
flags/_base.py:  local_device_protos = device_lib.list_local_devices()
```

Can you get rid of its usage and see if it helps?

**Comment by blessengeorge** [comment]
In your output.log file, I find the following from line 192.

```
I1205 16:02:38.712547 47693075944192 tf_logging.py:115] Graph was finalized.
2018-12-05 16:02:38.714632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-12-05 16:02:38.714663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-05 16:02:38.714670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-12-05 16:02:38.714674: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-12-05 16:02:38.714853: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10655 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:84:00.0, compute capability: 3.7)
I1205 16:02:38.728630 46992336483072 tf_logging.py:115] Graph was finalized.
```

What this means is that the Graph was initialized using by mapping onto GPU 0. As mentioned by @zqlai 
the code to pin TF to a specific GPU is executed late. So after the initial mapping, changes are not permitted. 

Generally, what happens is something of the following form takes place:

```
with tf.Graph().as_default():
    config = tf.ConfigProto(allow_soft_placement=True)
    config.gpu_options.visible_device_list = '2'
    with tf.Session(config=config) as sess:
```

The first line creates the graph with some default GPU initialization mapping, later a Session object is created with specific user GPU mapping.

**Comment by XuesongYang** [comment]
Another workaround is to avoid using `tf.test.is_gpu_available()` if your script used it. After removing it, the following error is gone:
`[1,1]<stderr>:tensorflow.python.framework.errors_impl.AlreadyExistsError: TensorFlow device (G
PU:0) is being mapped to multiple CUDA devices (0 now, and 1 previously), which is not support
ed. This may be the result of providing different GPU configurations (ConfigProto.gpu_options, for example different visible_device_list) when creating multiple Sessions in the same proces
s. This is not  currently supported, see https://github.com/tensorflow/tensorflow/issues/19083
`

**Comment by mivenHan** [comment]
@zqlai Have you solved the problem? I tried the solution of @XuesongYang and @blessengeorge , and failed to solve this problem. My tensorflow is 1.12 and horovod is 0.12. Be grateful if you have any new updates or solutions.

**Comment by mivenHan** [comment]
@zqlai sorry about the horovod version which is the latest 1.12

**Comment by XuesongYang** [comment]
@mivenHan My setup is using tf 1.12 and hvd 0.16.1 for your information.

**Comment by yurijvolkov** [comment]
I fixed it with `os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())` at the beginning of script.

**Comment by zqlai** [comment]
@mivenHan I commented two lines of code so that the error disappeared. 
Firstly, as @XuesongYang mentioned, I commented this line in utils/flags/_base.py file to avoid using  tf.test.is_gpu_available()
`
105         #default=1 if tf.test.is_gpu_available() else 0, 
`
Secondly, commented this in utils/logs/logger.py
`319   #_collect_gpu_info(run_info, session_config)`

I think the method of @yurijvolkov is better if it works for you.
Hope these help.

**Comment by skywalkerytx** [comment]
I just ran into the same problem.

turns out it was `tensorflow.python.client.device_lib.list_local_devices()` before `hvd.init()` happens

**Comment by TUMAAA** [comment]
> I fixed it with `os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())` at the beginning of script.

Make sure to do that right after importing tensorflow and horovod otherwise it is ignored!

**Comment by Vidyaranya** [comment]
I am getting a similar error on my device. 
"`TensorFlow device (GPU:0) is being mapped to multiple CUDA devices (1 now, and 0 previously), which is not supported.`".
 So, I tried using the method suggested by @yurijvolkov and @TUMAAA However, using that solution (adding `os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())`), I end up getting a different error. Specifically, 

`InvalidArgumentError: 'visible_device_list' listed an invalid GPU id '1' but visible device count is 1`

There is an issue related to that #520 However, the solution suggested in that issue to overcome this problem is to unset the `CUDA_VISIBLE_DEVICES` variable. Now, this is a catch 22 situation. Any suggestions will be really helpful.

**Comment by godblessY** [comment]
> I am getting a similar error on my device.
> "`TensorFlow device (GPU:0) is being mapped to multiple CUDA devices (1 now, and 0 previously), which is not supported.`".
> So, I tried using the method suggested by @yurijvolkov and @TUMAAA However, using that solution (adding `os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())`), I end up getting a different error. Specifically,
> 
> `InvalidArgumentError: 'visible_device_list' listed an invalid GPU id '1' but visible device count is 1`
> 
> There is an issue related to that #520 However, the solution suggested in that issue to overcome this problem is to unset the `CUDA_VISIBLE_DEVICES` variable. Now, this is a catch 22 situation. Any suggestions will be really helpful.

try this
config.gpu_options.visible_device_list = '0'

**Comment by Vidyaranya** [comment]
It 'sort of works' but it runs out of memory when I use two GPUs. When I used 1 GPU the process runs fine but for 2 GPUs with 2 processes, the first process runs fine but the second process runs out of memory. I suspect this is because visible_device_list is set to 0, every process is using just the first GPU?

**Comment by Vidyaranya** [comment]
> > I am getting a similar error on my device.
> > "`TensorFlow device (GPU:0) is being mapped to multiple CUDA devices (1 now, and 0 previously), which is not supported.`".
> > So, I tried using the method suggested by @yurijvolkov and @TUMAAA However, using that solution (adding `os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())`), I end up getting a different error. Specifically,
> > `InvalidArgumentError: 'visible_device_list' listed an invalid GPU id '1' but visible device count is 1`
> > There is an issue related to that #520 However, the solution suggested in that issue to overcome this problem is to unset the `CUDA_VISIBLE_DEVICES` variable. Now, this is a catch 22 situation. Any suggestions will be really helpful.
> 
> try this
> config.gpu_options.visible_device_list = '0'
It 'sort of works' but it runs out of memory when I use two GPUs. When I used 1 GPU the process runs fine but for 2 GPUs with 2 processes, the first process runs fine but the second process runs out of memory. I suspect this is because visible_device_list is set to 0, every process is using just the first GPU?

**Comment by tgaddair** [comment]
Hey @Vidyaranya, for most environments, you should do the following:

1. Unset `CUDA_VISIBLE_DEVICES`.  That way, every process can see every GPU initially (this is important for NCCL to work correctly).
2. Set `config.gpu_options.visible_device_list = str(hvd.local_rank())`.  This will ensure that process 0 sees only GPU 0, process 1 sees GPU 1, etc.

Use `nvidia-smi` to verify that both GPUs are being used correctly.

If this does not work for you, then we can chat more about solutions for your specific runtime environment.

**Comment by Vidyaranya** [comment]
> Hey @Vidyaranya, for most environments, you should do the following:
> 
> 1. Unset `CUDA_VISIBLE_DEVICES`.  That way, every process can see every GPU initially (this is important for NCCL to work correctly).
> 2. Set `config.gpu_options.visible_device_list = str(hvd.local_rank())`.  This will ensure that process 0 sees only GPU 0, process 1 sees GPU 1, etc.
> 
> Use `nvidia-smi` to verify that both GPUs are being used correctly.
> 
> If this does not work for you, then we can chat more about solutions for your specific runtime environment.

Hi @tgaddair, thanks for the quick response. It still get the same 'mapped to multiple cuda devices'. I use a singularity container to run my python training script. I have done unset CUDA_VISIBLE_DEVICES and then config.gpu_options.visible_device_list = str(hvd.local_rank()) in the script.

**Comment by tgaddair** [comment]
Hey @Vidyaranya, since you're using Singularity, did you follow the guidance in this doc: https://github.com/sylabs/examples/tree/master/machinelearning/horovod

Were you able to run the `keras_mnist_advanced.py` example without needing to modify the training script?

Also, are you using SLURM to launch your jobs?

**Comment by Vidyaranya** [comment]
Hi @tgaddair, I did follow those instructions while I initially created the singularity container. However, now I see that the `keras_mnist_advanced` example doesn't work. it fails with error `AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'`

And yes, I am using slurm to launch my jobs.

**Comment by Huhao123** [comment]
I have met the same problem. So did you solve it?

**Comment by adiprasad** [comment]
any solution to this yet?
