### ISSUE TITLE
horovod with pytorch produces seg fault

### ISSUE THREAD

**Issue by tsmolcic** [horovod/horovod#761]
Hi.

I have a problem running Horovod PyTorch examples from Horovod git.

mpirun flags used to run:
```-bind-to none -x NCCL_DEBUG=INFO -mca pml ob1 -mca btl ^openib python3.5 horovod/examples/pytorch_mnist.py```

My system: CentOS 7, CUDA 10.0, NCCL 2.3.5, Horovod 0.15.2, PyTorch 1.0.0

Horovod is installed with 
`HOROVOD_NCCL_HOME=/apps/nvidia/nccl/nccl_2.3.5-2+cuda10.0_x86_64 HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_CUDA_HOME=/usr/local/cuda-10.0/ pip3 install --no-cache-dir horovod`

Horovod runs without problems with TensorFlow, as does PyTorch by itself.

Error log:
```[c4140-02:236649] *** Process received signal ***
[c4140-02:236649] Signal: Segmentation fault (11)
[c4140-02:236649] Signal code: Address not mapped (1)
[c4140-02:236649] Failing at address: 0xb
[c4140-02:236649] [ 0] /lib64/libpthread.so.0(+0xf5d0)[0x2b09b2d695d0]
[c4140-02:236649] [ 1] /usr/lib64/python3.5/site-packages/horovod/torch/mpi_lib_v2.cpython-35m-x86_64-linux-gnu.so(+0x55871)[0x2b0a3bad6871]
[c4140-02:236649] [ 2] /lib64/libpython3.5m.so.1.0(PyCFunction_Call+0xe9)[0x2b09b29350f9]
[c4140-02:236649] [ 3] /lib64/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x81a6)[0x2b09b29ae646]
[c4140-02:236649] [ 4] /lib64/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x75e8)[0x2b09b29ada88]
[c4140-02:236649] [ 5] /lib64/libpython3.5m.so.1.0(+0x12bebc)[0x2b09b29afebc]
[c4140-02:236649] [ 6] /lib64/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x6d8f)[0x2b09b29ad22f]
[c4140-02:236649] [ 7] /lib64/libpython3.5m.so.1.0(+0x12bebc)[0x2b09b29afebc]
[c4140-02:236649] [ 8] /lib64/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x6d8f)[0x2b09b29ad22f]
[c4140-02:236649] [ 9] /lib64/libpython3.5m.so.1.0(+0x12bebc)[0x2b09b29afebc]
[c4140-02:236649] [10] /lib64/libpython3.5m.so.1.0(PyEval_EvalCodeEx+0x48)[0x2b09b29affc8]
[c4140-02:236649] [11] /lib64/libpython3.5m.so.1.0(PyEval_EvalCode+0x3b)[0x2b09b29b000b]
[c4140-02:236649] [12] /lib64/libpython3.5m.so.1.0(+0x14b434)[0x2b09b29cf434]
[c4140-02:236649] [13] /lib64/libpython3.5m.so.1.0(PyRun_FileExFlags+0x9d)[0x2b09b29d18bd]
[c4140-02:236649] [14] /lib64/libpython3.5m.so.1.0(PyRun_SimpleFileExFlags+0xf7)[0x2b09b29d1a27]
[c4140-02:236649] [15] /lib64/libpython3.5m.so.1.0(Py_Main+0xeac)[0x2b09b29e7bec]
[c4140-02:236649] [16] python3.5(main+0x169)[0x400a29]
[c4140-02:236649] [17] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2b09b36a13d5]
[c4140-02:236649] [18] python3.5[0x400ad6]
[c4140-02:236649] *** End of error message ***
[c4140-02:236650] *** Process received signal ***
[c4140-02:236650] Signal: Segmentation fault (11)
[c4140-02:236650] Signal code: Address not mapped (1)
[c4140-02:236650] Failing at address: 0xb
[c4140-02:236650] [ 0] /lib64/libpthread.so.0(+0xf5d0)[0x2abcd4e175d0]
[c4140-02:236650] [ 1] /usr/lib64/python3.5/site-packages/horovod/torch/mpi_lib_v2.cpython-35m-x86_64-linux-gnu.so(+0x55871)[0x2abd5db84871]
[c4140-02:236650] [ 2] /lib64/libpython3.5m.so.1.0(PyCFunction_Call+0xe9)[0x2abcd49e30f9]
[c4140-02:236650] [ 3] /lib64/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x81a6)[0x2abcd4a5c646]
[c4140-02:236650] [ 4] /lib64/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x75e8)[0x2abcd4a5ba88]
[c4140-02:236650] [ 5] /lib64/libpython3.5m.so.1.0(+0x12bebc)[0x2abcd4a5debc]
[c4140-02:236650] [ 6] /lib64/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x6d8f)[0x2abcd4a5b22f]
[c4140-02:236650] [ 7] /lib64/libpython3.5m.so.1.0(+0x12bebc)[0x2abcd4a5debc]
[c4140-02:236650] [ 8] /lib64/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x6d8f)[0x2abcd4a5b22f]
[c4140-02:236650] [ 9] /lib64/libpython3.5m.so.1.0(+0x12bebc)[0x2abcd4a5debc]
[c4140-02:236650] [10] /lib64/libpython3.5m.so.1.0(PyEval_EvalCodeEx+0x48)[0x2abcd4a5dfc8]
[c4140-02:236650] [11] /lib64/libpython3.5m.so.1.0(PyEval_EvalCode+0x3b)[0x2abcd4a5e00b]
[c4140-02:236650] [12] /lib64/libpython3.5m.so.1.0(+0x14b434)[0x2abcd4a7d434]
[c4140-02:236650] [13] /lib64/libpython3.5m.so.1.0(PyRun_FileExFlags+0x9d)[0x2abcd4a7f8bd]
[c4140-02:236650] [14] /lib64/libpython3.5m.so.1.0(PyRun_SimpleFileExFlags+0xf7)[0x2abcd4a7fa27]
[c4140-02:236650] [15] /lib64/libpython3.5m.so.1.0(Py_Main+0xeac)[0x2abcd4a95bec]
[c4140-02:236650] [16] python3.5(main+0x169)[0x400a29]
[c4140-02:236650] [17] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2abcd574f3d5]
[c4140-02:236650] [18] python3.5[0x400ad6]
[c4140-02:236650] *** End of error message ***
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[52704,1],0]
  Exit code:    139
--------------------------------------------------------------------------
```

In case needed, `ifconfig` from one of the compute nodes (all are identical):
```
em3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.8.24.35  netmask 255.255.255.0  broadcast 10.8.24.255
        ether e4:43:4b:25:29:30  txqueuelen 1000  (Ethernet)
        RX packets 274491139  bytes 165023078264 (153.6 GiB)
        RX errors 0  dropped 28  overruns 0  frame 0
        TX packets 178014888  bytes 76517750008 (71.2 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0x95300000-953fffff

ib0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 2044
        inet 192.168.1.35  netmask 255.255.255.0  broadcast 192.168.1.255
Infiniband hardware address can be incorrect! Please read BUGS section in ifconfig(8).
        infiniband 00:00:00:86:FE:80:00:00:00:00:00:00:00:00:00:00:00:00:00:00  txqueuelen 256  (InfiniBand)
        RX packets 9472296  bytes 17044801102 (15.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12509238  bytes 21559339153 (20.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 576445  bytes 81571228 (77.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 576445  bytes 81571228 (77.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Kind regards,
Tomislav

**Comment by alsrgv** [comment]
@tsmolcic, to narrow down the problem, are you using workers in DataLoader in your PyTorch script?  Does the error disappear if you set workers to 0?

**Comment by tsmolcic** [comment]
@alsrgv I was using the original horovod example script, `pytorch_mnist.py`. I tried setting `num_workers = 0`, but I get the same error.

**Comment by alsrgv** [comment]
@tsmolcic, could you make a docker image with repro?  That would help a lot.

**Comment by zxb1489479870** [comment]
@aladdha-uber , I also have a similary error when I use the latest pytorch to test the example on one **cpu core** , but the mnist example can be run if pytorch downgrade to version 0.4.1. I hope you can reproduce the results according to following steps on Linux:

1. Install OpenMPI as said in https://github.com/uber/horovod#install
2. Install Pytorch: `conda install pytorch-cpu torchvision-cpu -c pytorch`
3. Install horovod: `pip install horovod`

And run the follwing script.
```
mpirun -np 1 \
    -H localhost:1 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python train.py
```
there will have a **Segmentation fault**:
```
[mlt-bdw024:63733] *** Process received signal ***
[mlt-bdw024:63733] Signal: Segmentation fault (11)
[mlt-bdw024:63733] Signal code: Address not mapped (1)
[mlt-bdw024:63733] Failing at address: 0xb
[mlt-bdw024:63733] [ 0] /usr/lib64/libpthread.so.0(+0xf5e0)[0x7f68cf7415e0]
[mlt-bdw024:63733] [ 1] /home/xiaobinz/anaconda3/envs/horovod/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(+0x65621)[0x7f68b05b8621]
[mlt-bdw024:63733] [ 2] python(_PyCFunction_FastCallDict+0x154)[0x562cf8922744]
[mlt-bdw024:63733] [ 3] python(+0x19842c)[0x562cf89a942c]
[mlt-bdw024:63733] [ 4] python(_PyEval_EvalFrameDefault+0x30a)[0x562cf89ce38a]
[mlt-bdw024:63733] [ 5] python(+0x19253b)[0x562cf89a353b]
[mlt-bdw024:63733] [ 6] python(+0x198505)[0x562cf89a9505]
[mlt-bdw024:63733] [ 7] python(_PyEval_EvalFrameDefault+0x30a)[0x562cf89ce38a]
[mlt-bdw024:63733] [ 8] python(+0x1918e4)[0x562cf89a28e4]
[mlt-bdw024:63733] [ 9] python(+0x192771)[0x562cf89a3771]
[mlt-bdw024:63733] [10] python(+0x198505)[0x562cf89a9505]
[mlt-bdw024:63733] [11] python(_PyEval_EvalFrameDefault+0x30a)[0x562cf89ce38a]
[mlt-bdw024:63733] [12] python(+0x1918e4)[0x562cf89a28e4]
[mlt-bdw024:63733] [13] python(+0x192771)[0x562cf89a3771]
[mlt-bdw024:63733] [14] python(+0x198505)[0x562cf89a9505]
[mlt-bdw024:63733] [15] python(_PyEval_EvalFrameDefault+0x10c7)[0x562cf89cf147]
[mlt-bdw024:63733] [16] python(PyEval_EvalCodeEx+0x329)[0x562cf89a4289]
[mlt-bdw024:63733] [17] python(PyEval_EvalCode+0x1c)[0x562cf89a501c]
[mlt-bdw024:63733] [18] python(+0x2163c4)[0x562cf8a273c4]
[mlt-bdw024:63733] [19] python(PyRun_FileExFlags+0xa1)[0x562cf8a277c1]
[mlt-bdw024:63733] [20] python(PyRun_SimpleFileExFlags+0x1c3)[0x562cf8a279c3]
[mlt-bdw024:63733] [21] python(Py_Main+0x613)[0x562cf8a2b4b3]
[mlt-bdw024:63733] [22] python(main+0xee)[0x562cf88f402e]
[mlt-bdw024:63733] [23] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f68cf390c05]
[mlt-bdw024:63733] [24] python(+0x1c3e0e)[0x562cf89d4e0e]
[mlt-bdw024:63733] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node mlt-bdw024 exited on signal 11 (Segmentation fault).
```
If I downgrade Pytorch to version 0.4.1 by:
1.  `pip uninstall torch`
2. `pip uninstall horovod`
3. `conda install pytorch=0.4.1 -c pytorch`
4. `pip install --no-cache-dir horovod`

And run the former script again,  the minist example can be passed. Thanks.

**Comment by alsrgv** [comment]
@zxb1489479870, can you get a backtrace from the core file that gets dumped?

**Comment by wangzhimingchn** [comment]
@alsrgv I meet the same problem. It looks like pybind11。
# gdb python3 core.22995
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/python3.6...Reading symbols from /usr/bin/python3.6...(no debugging symbols found)...done.
(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 22995]
[New LWP 23063]
[New LWP 23064]
[New LWP 23070]
[New LWP 23071]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Missing separate debuginfo for /usr/local/lib64/python3.6/site-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0
Missing separate debuginfo for /usr/local/lib64/python3.6/site-packages/torch/lib/libgomp-8bba0e50.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/c2/a2ccfc1797d8d8444dad457030e82610ca77a6.debug
Missing separate debuginfo for /usr/local/lib64/python3.6/site-packages/PIL/.libs/libz-a147dcb0.so.1.2.3
Core was generated by `python3 ./pytorch_imagenet_resnet50.py --batch-size 112 --train-dir /mnt/'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fa37f0078e1 in construct<_object*, _object*> (__p=0xb, this=0x2b0c908) at /usr/include/c++/4.8.2/ext/new_allocator.h:120
120             { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 expat-2.1.0-10.el7_3.x86_64 glibc-2.17-260.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-34.el7.x86_64 libcom_err-1.42.9-13.el7.x86_64 libffi-3.0.13-18.el7.x86_64 libgcc-4.8.5-36.el7.x86_64 libselinux-2.5-14.1.el7.x86_64 libstdc++-4.8.5-36.el7.x86_64 openssl-libs-1.0.2k-16.el7.x86_64 pcre-8.32-17.el7.x86_64 python36-3.6.6-1.el7.x86_64 python36-libs-3.6.6-1.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) where
#0  0x00007fa37f0078e1 in construct<_object*, _object*> (__p=0xb, this=0x2b0c908) at /usr/include/c++/4.8.2/ext/new_allocator.h:120
#1  _S_construct<_object*, _object*> (__p=0xb, __a=...) at /usr/include/c++/4.8.2/bits/alloc_traits.h:254
#2  construct<_object*, _object*> (__p=0xb, __a=...) at /usr/include/c++/4.8.2/bits/alloc_traits.h:393
#3  emplace_back<_object*> (this=0x2b0c908) at /usr/include/c++/4.8.2/bits/vector.tcc:96
#4  push_back (__x=<unknown type in /usr/local/lib64/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so, CU 0x143219, DIE 0x26fe02>, this=0x2b0c908)
    at /usr/include/c++/4.8.2/bits/stl_vector.h:920
#5  loader_life_support (this=0x7ffc855e0cc0) at /usr/local/lib64/python3.6/site-packages/torch/lib/include/pybind11/cast.h:44
#6  pybind11::cpp_function::dispatcher (self=<optimized out>, args_in=0x7fa42c6f16d8, kwargs_in=0x0)
    at /usr/local/lib64/python3.6/site-packages/torch/lib/include/pybind11/pybind11.h:618
#7  0x00007fa45286c807 in _PyCFunction_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#8  0x00007fa4528d848f in call_function () from /usr/lib64/libpython3.6m.so.1.0
#9  0x00007fa4528cc8b7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#10 0x00007fa4528d827a in fast_function () from /usr/lib64/libpython3.6m.so.1.0
#11 0x00007fa4528d85b3 in call_function () from /usr/lib64/libpython3.6m.so.1.0
#12 0x00007fa4528cc8b7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#13 0x00007fa4528d74cc in _PyEval_EvalCodeWithName () from /usr/lib64/libpython3.6m.so.1.0
#14 0x00007fa4528d832a in fast_function () from /usr/lib64/libpython3.6m.so.1.0
#15 0x00007fa4528d85b3 in call_function () from /usr/lib64/libpython3.6m.so.1.0
#16 0x00007fa4528cc8b7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#17 0x00007fa4528d88b2 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.6m.so.1.0
#18 0x00007fa452846d23 in function_call () from /usr/lib64/libpython3.6m.so.1.0
#19 0x00007fa45282e853 in PyObject_Call () from /usr/lib64/libpython3.6m.so.1.0
#20 0x00007fa438e83ab1 in THPFunction_apply(_object*, _object*) () from /usr/local/lib64/python3.6/site-packages/torch/lib/libtorch_python.so
#21 0x00007fa45286c75a in _PyCFunction_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#22 0x00007fa4528d848f in call_function () from /usr/lib64/libpython3.6m.so.1.0
#23 0x00007fa4528cc8b7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#24 0x00007fa4528d74cc in _PyEval_EvalCodeWithName () from /usr/lib64/libpython3.6m.so.1.0
#25 0x00007fa4528d832a in fast_function () from /usr/lib64/libpython3.6m.so.1.0
#26 0x00007fa4528d85b3 in call_function () from /usr/lib64/libpython3.6m.so.1.0
#27 0x00007fa4528cdb46 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#28 0x00007fa4528d88b2 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.6m.so.1.0
#29 0x00007fa4528d953b in PyEval_EvalCode () from /usr/lib64/libpython3.6m.so.1.0
#30 0x00007fa452961b0e in run_mod () from /usr/lib64/libpython3.6m.so.1.0
#31 0x00007fa45280d1bc in PyRun_FileExFlags () from /usr/lib64/libpython3.6m.so.1.0
#32 0x00007fa45280d57c in PyRun_SimpleFileExFlags () from /usr/lib64/libpython3.6m.so.1.0
#33 0x00007fa4529683dc in Py_Main () from /usr/lib64/libpython3.6m.so.1.0
#34 0x0000000000400a99 in main ()
(gdb)

**Comment by jaliyae** [comment]
Facing a similar issue and originating from pybind11. Any suggestions?
`Signal: Segmentation fault (11)
Signal code: Address not mapped (1)
Failing at address: 0x7fe7cc8e2000
[ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fe981079390]
[ 1] /lib/x86_64-linux-gnu/libc.so.6(+0x14e199)[0x7fe980dec199]
[ 2] [1,15]<stderr>:/opt/conda/lib/python3.6/site-packages/readers/data_ext.cpython-36m-x86_64-linux-gnu.so(+0x38fd2)[0x7fe8cbfe3fd2]
[ 3] /opt/conda/lib/python3.6/site-packages/readers/data_ext.cpython-36m-x86_64-linux-gnu.so(+0x303db)[0x7fe8cbfdb3db]
[ 4] /opt/conda/lib/python3.6/site-packages/readers/data_ext.cpython-36m-x86_64-linux-gnu.so(+0x62e50)[0x7fe8cc00de50]
[ 5] [1,15]<stderr>:/opt/conda/lib/libstdc++.so.6(+0xb8678)[0x7fe908044678]
[ 6] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7fe98106f6ba]
[ 7] [1,15]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fe980da53dd]`

**Comment by alsrgv** [comment]
@wangzhimingchn, @jaliyae, can you specify `mpirun` command that you use and whether you have RDMA capable NICs in your system?

**Comment by wangzhimingchn** [comment]
@alsrgv No RDMA capable NICs in our system. 
The mpirun command:
mpirun --allow-run-as-root --bind-to none -np ${total_gpus} -npernode ${n_per_node} \
     --mca btl_tcp_if_include eth0 \
     --mca orte_keep_fqdn_hostnames t \
     -x HOROVOD_TIMELINE \
     -x HOROVOD_FUSION_THRESHOLD \
     -x NCCL_SOCKET_IFNAME=eth0 \
     -x LD_LIBRARY_PATH \
     python ./scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py ...

**Comment by alsrgv** [comment]
@wangzhimingchn, thanks!  Which version of Horovod are you using?

**Comment by jaliyae** [comment]
@wangzhimingchn, 
This is the mpirun command we used.
`mpirun --hostfile mpi-hosts -x NCCL_IB_DISABLE=1 -x NCCL_SOCKET_IFNAME=eth0 -x NCCL_DEBUG=INFO -x NCCL_IB_DISABLE=1 --mca pml ob1 python`

The NICs are capable of RDMA but we have not enabled it yet.

**Comment by wangzhimingchn** [comment]
@alsrgv  0.15.2

**Comment by alsrgv** [comment]
@jaliyae, what if you add `--mca btl ^openib` to your command?
@wangzhimingchn, can you try upgrading to 0.16.0 and see if it changes anything?

**Comment by ssstuvz** [comment]
same error, adding --mca btl ^openib didn't help.
I also upgraded to 0.16.0 - didn't help. Tensorflow works fine. 

I also have a singularity image with horovod and pytorch that works on the same machine (it has other problems though).

**Comment by alsrgv** [comment]
@wangzhimingchn, @jaliyae, @ssstuvz, @dasight, which version of gcc are you guys using?

I've recently painfully found out that gcc 4.8 [does not work](https://github.com/horovod/horovod/pull/958) with pybind11, which is used by PyTorch plugin mechanism since PyTorch 1.0.  The solution is to upgrade to gcc 4.9 or 5+.

**Comment by tsmolcic** [comment]
@alsrgv I'm using 4.8.5. Will upgrade and try it out.

**Comment by cyxtj** [comment]
gcc 4.8.5 on Centos, PyTorch 1.0, run into same error
```
± % mpirun -np 1 python pytorch_mnist.py
                                                                                                        !9291
[c3:15883] *** Process received signal ***
[c3:15883] Signal: Segmentation fault (11)
[c3:15883] Signal code: Address not mapped (1)
[c3:15883] Failing at address: 0xb
[c3:15883] [ 0] /lib64/libpthread.so.0(+0xf5d0)[0x7f8e6b61a5d0]
[c3:15883] [ 1] /home/cyx/.conda/envs/torch1.0/lib/python2.7/site-packages/horovod/torch/mpi_lib_v2.so(+0x84d0e)[0x7f8db9c89d0e]
[c3:15883] [ 2] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x7b35)[0x7f8e6b9241e5]
[c3:15883] [ 3] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e)[0x7f8e6b925c3e]
[c3:15883] [ 4] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b47)[0x7f8e6b9251f7]
[c3:15883] [ 5] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e)[0x7f8e6b925c3e]
[c3:15883] [ 6] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b47)[0x7f8e6b9251f7]
[c3:15883] [ 7] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e)[0x7f8e6b925c3e]
[c3:15883] [ 8] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8b47)[0x7f8e6b9251f7]
[c3:15883] [ 9] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e)[0x7f8e6b925c3e]
[c3:15883] [10] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32)[0x7f8e6b925d52]
[c3:15883] [11] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(PyRun_FileExFlags+0xb0)[0x7f8e6b946450]
[c3:15883] [12] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xef)[0x7f8e6b94662f]
[c3:15883] [13] /home/cyx/.conda/envs/torch1.0/bin/../lib/libpython2.7.so.1.0(Py_Main+0xca4)[0x7f8e6b95bfd4]
[c3:15883] [14] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f8e6ab573d5]
[c3:15883] [15] python[0x400729]
[c3:15883] *** End of error message ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node c3 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```
But tensorflow works fine.
```
± % mpirun -np 1 python tensorflow_mnist.py                                                                                                                                                                                                                                                                             !9293
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2019-04-04 18:32:09.579041: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Restoring parameters from ./checkpoints/model.ckpt-0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into ./checkpoints/model.ckpt.
INFO:tensorflow:loss = 2.32194, step = 1
INFO:tensorflow:loss = 2.32473, step = 11 (3.541 sec)
INFO:tensorflow:loss = 2.29579, step = 21 (3.561 sec)
```
Is there any workaround except updating GCC ?

**Comment by alsrgv** [comment]
@cyxtj, pybind11 that PyTorch uses does not like GCC 4.8.  I'm not aware of a way to fix it, unfortunately :-(

**Comment by Qiuzhuang** [comment]
> @wangzhimingchn, @jaliyae, @ssstuvz, @dasight, which version of gcc are you guys using?
> 
> I've recently painfully found out that gcc 4.8 [does not work](https://github.com/horovod/horovod/pull/958) with pybind11, which is used by PyTorch plugin mechanism since PyTorch 1.0. The solution is to upgrade to gcc 4.9 or 5+.

I also just upgrade to pytorch 1.1.0, the error seems to be resolved now.

**Comment by jaliyae** [comment]
I am using gcc 7.3.0. Yes, the error seems to resolved with the latest PyTorch.

**Comment by luzhilin19951120** [comment]
Really? @jaliyae  @Qiuzhuang Are you successfully implement horovod on PyTorch1.1.0?

I tried with the latest version of horovod and failed with the same segmentation default.

**Comment by luzhilin19951120** [comment]
Dear author: @alsrgv 
Do we have a solution for implement horovod on PyTorch1.0+ version now?

**Comment by alsrgv** [comment]
@luzhilin19951120, can you share more details about your segmentation fault?  We do have integration tests against PyTorch latest, which are passing.

**Comment by jaliyae** [comment]
@luzhilin19951120 Yes, just validated again. Horovod 0.16.1, PyTorch 1.1.0, works fine.

**Comment by luzhilin19951120** [comment]
@alsrgv @jaliyae 
- System:
Linux version 3.10.0-327.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCG))
- Horovod 0.16.1:
HOROVOD_NCCL_HOME=/home/user_name/software/nccl_2.2 HOROVOD_GPU_ALLREDUCE=NCCL pip install --user --no-cache-dir horovod
- PyTorch 1.1.0:
installed with anaconda3
- Seg Error Message:
![image](https://user-images.githubusercontent.com/25010679/57684741-f7f1b500-7668-11e9-8cfd-09bdcdd4afde.png)

**Comment by Qiuzhuang** [comment]
@luzhilin19951120  what is your mpi version?  The log seems not to complain about gcc version which I run into.

**Comment by luzhilin19951120** [comment]
@Qiuzhuang My mpi version is `openmpi 3.0.0`

**Comment by Qiuzhuang** [comment]
I remember that @alsrgv suggested better upgrade to 4.0. Looking into your log, it complains mpi torch error. Can you please try with upgrading mpi?

**Comment by luzhilin19951120** [comment]
I installed OpenMPI4.0.1 and add `--mca btl ^openib` flag when using mpirun.

However, the same error occurs. @alsrgv @Qiuzhuang 

![image](https://user-images.githubusercontent.com/25010679/57703480-bfff6780-7692-11e9-8159-0faa4bf52326.png)

**Comment by alsrgv** [comment]
@luzhilin19951120, could you try installing gcc7 in your conda environment (`conda install gcc_linux-64 gxx_linux-64`) and re-install Horovod within the conda environment?

**Comment by luzhilin19951120** [comment]
Thank you very much, the problem is solved after installing gcc7.

This seems to be a key request of using horovod0.16.1 together with PyTorch1.1.0, I suppose you may add a special instruction about it.

And there exists a small problem about isl version when installing gcc7 with anaconda3. The following code will solve it.
``` bash
conda create -n torch1.1 python=3.6
conda install -n torch1.1 -c omgarcia isl
conda install -n torch1.1 -c quantstack gcc-7
```

Thank you again ! ^_^
@alsrgv

**Comment by qiuyang163** [comment]
Does any one solved the problem?

**Comment by qiuyang163** [comment]
Did any one solve the problem?

**Comment by Kylin9511** [comment]
@qiuyang163  Please refer to the common records and you shall see.
