### ISSUE TITLE
Internal error. Requested ReadyEvent with GPU device but not compiled with CUDA.

### ISSUE THREAD

**Issue by windson87** [horovod/horovod#851]
HI,
I am new to horovod and openmpi stuff..
I want to run distributed training on ubuntu 18.04 with pytorch and two tesla GPU..
After installing horovod newest version (0.16.0) and pytorch (cuda 10, 1.0.1-post2)

it always give me this error (running  horovod/examples/pytorch_mnist.py)
Internal error. Requested ReadyEvent with GPU device but not compiled with CUDA.

I dont know how to handle it, seems it has sth to do with CUDA, but I installed CUDA 10 and it's already in my env path (lib too).
Could someone help me out? 
Thanks!!

**Comment by souxun2015** [comment]
Have you solved it yet? I am with the same problem.

**Comment by alsrgv** [comment]
@windson87, @souxun2015, to help debug this, could you make a [gist](https://gist.github.com) with Horovod installation logs (add -v --no-cache-dir), and use latest Horovod version?

**Comment by souxun2015** [comment]
Sure, I have made a gist with my Horovod installation [logs](https://gist.github.com/souxun2015/759346c038f35d514327f006cffdce6c).
I use Anaconda as my python environment, which includes:
pytorch 1.1.0, 
cudatoolkit 9.0,
horovod 0.16.4.
My system installed the Open MPI 2.1.1

**Comment by alsrgv** [comment]
@souxun2015, can you uninstall Horovod first, and then rerun the installation? This log says that Horovod is already installed.

**Comment by souxun2015** [comment]
Sorry about that. This is the whole [logs](https://gist.github.com/souxun2015/75315e894c0a395f110b127d57fc7904)

**Comment by souxun2015** [comment]
Hi, when I reinstalled horovod, I am not sure what happend, but I can run pytorch_mnist.py without the error.

**Comment by alsrgv** [comment]
@souxun2015, great!  As a rule of thumb, if you upgrade the framework (or see other issues), you should reinstall Horovod and see if it resolved the issue.

**Comment by linhanxiao** [comment]
@souxun2015 Have you solved it yet? I am with the same problem.

**Comment by linhanxiao** [comment]
@souxun2015 @windson87 @alsrgv how did you solved this problem

**Comment by souxun2015** [comment]
I didn't find the real reason behind this problem. When I uninstalled it and reinstalled it, it was gone.

**Comment by linhanxiao** [comment]
@alsrgv @souxun2015  I have uninstalled it and reinstalled it with the command “pip install -v --no-cache-dir horovod ”，but it still have that error “   Internal error. Requested ReadyEvent with GPU device but not compiled with CUDA.”

**Comment by linhanxiao** [comment]
@alsrgv  @souxun2015  @windson87 my log is


Traceback (most recent call last):
[1,1]<stderr>:  File "train.py", line 560, in <module>
[1,1]<stderr>:    train(args, log_dir, writer, logger)
[1,1]<stderr>:  File "train.py", line 212, in train
[1,1]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,1]<stderr>:  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/horovod/torch/__init__.py", line 275, in broadcast_parameters
[1,1]<stderr>:    handle = broadcast_async_(p, root_rank, name)
[1,1]<stderr>:  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 380, in broadcast_async_
[1,1]<stderr>:    return _broadcast_async(tensor, tensor, root_rank, name)
[1,1]<stderr>:  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 290, in _broadcast_async
[1,1]<stderr>:    tensor, output, root_rank, name.encode() if name is not None else _NULL)
[1,1]<stderr>:RuntimeError: Internal error. Requested ReadyEvent with GPU device but not compiled with CUDA.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train.py", line 560, in <module>
[1,0]<stderr>:    train(args, log_dir, writer, logger)
[1,0]<stderr>:  File "train.py", line 212, in train
[1,0]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,0]<stderr>:  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/horovod/torch/__init__.py", line 275, in broadcast_parameters
[1,0]<stderr>:    handle = broadcast_async_(p, root_rank, name)
[1,0]<stderr>:  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 380, in broadcast_async_
[1,0]<stderr>:    return _broadcast_async(tensor, tensor, root_rank, name)
[1,0]<stderr>:  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 290, in _broadcast_async
[1,0]<stderr>:    tensor, output, root_rank, name.encode() if name is not None else _NULL)
[1,0]<stderr>:RuntimeError: Internal error. Requested ReadyEvent with GPU device but not compiled with CUDA.

**Comment by veritas9872** [comment]
I also have the same error but erasing then reinstalling doesn't work for me either. I am using Pytorch 1.4 OpenMPI 4.0.1. and horovod 0.18.

**Comment by veritas9872** [comment]
I suspect that it has something to do with the installation process of horovod. When I try to specify CUDA settings during the install, it keeps failing.

**Comment by Approximetal** [comment]
I have the same issue.

**Comment by AliOskooeiTR** [comment]
Same issue here. Tried everything from this post and other posts related to installation with HOROVOD_CUDA_HOME and --no-cache-dir but none worked for me.

**Comment by AlexYoung757** [comment]
i have  the same problem。 maybe your cuda version is not match。

**Comment by fei-wang-1314** [comment]
[1,0]<stderr>:RuntimeError: Internal error. Requested ReadyEvent with GPU device but not compiled with CUDA.

The same problem.

**Comment by thesidshah** [comment]
need help with this!

**Comment by fei-wang-1314** [comment]
> @fei-wang-1314 Hello! Do you fix this problem?

Hi, no, I choose to train on single card.
