### ISSUE TITLE
Horovod Docker hangs in distributed settings or throws error

### ISSUE THREAD

**Issue by vtczk** [horovod/horovod#971]
**Environment:**
1 Docker image : horovod/horovod:0.16.1-tf1.12.0-torch1.0.0-mxnet1.4.0-py3.5 
2. OS and version: Ubuntu 18.04.2 both hosts

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**
Im trying to run horovod docker on two machines.
I have set up password-less ssh connection between host A and B

When i run the horovod on host A only it works

When i run horovod distributed with command : 
`horovodrun --verbose -np 2 -H localhost:1,192.168.1.117:1 -p 12345  python keras_mnist_advanced.py`

The output is : 
`Filtering local host names.
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.`

and then the executions hangs indefinitely.

when i run job on host B from host A : 
`horovodrun --verbose -np 1 -H 192.168.1.117:1 -p 12345  python keras_mnist_advanced.py`

The output is:
`Filtering local host names.
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Launching horovodrun task function was not successful:
bash: /usr/bin/python: No such file or directory`

Which is weird as the docker image has symbolic link for /user/bin/python 
My only theory is that somehow horovod run connects to host  B instead of docker container on host B

Have any of you experienced similar symptoms ? Any suggestions how to fix the issue or debug it further will be highly appreciated.Thanks in advance.

**Comment by abditag2** [comment]
@vtczk 
I am assuming that you are running the above commands from the hosts and not inside the containers.

If this is the case, try the following. First, make sure you can ssh from host B into host A using  `ssh 192.168.1.117 -p 12345`. And make sure after doing ssh, you end up in the container environment and not the host itself and you can run `python`. If this works, then check the same thing from host A to B. 

If both of the above work, try running the following command but replace `localhost` with the IP of the localhost. 
`horovodrun --verbose -np 2 -H localhost:1,192.168.1.117:1 -p 12345 python keras_mnist_advanced.py`

**Comment by vtczk** [comment]
I have omitted the step to allow ssh from B to A as i thought only one way is sufficient.
Even though it takes considerable amounts of time for two hosts to make a connection, that seemed to fix the issue and the example script went through.

I also have a three side questions:
* is there a clear way of verification that both host indeed are working together and one host didn't silently died in the background ?
* is horovod docker only suited for GPU training or is there a way to make it suitable image for CPU training ?
* is root ssh connection required or can the images be run with user privileges?

@abditag2 Thanks for quick response.Should you be able to answer any mentioned questions i would be grateful for every bit of clarification.

**Comment by abditag2** [comment]
Glad that your problem is resolved. To answer your questions: 

> is there a clear way of verification that both host indeed are working together and one host didn't silently died in the background ?

As long as you start all the nodes correctly the training will continute only if all the nodes are up and running. If any of the workers die, MPI will terminate all the processes on all the hosts. 

> is horovod docker only suited for GPU training or is there a way to make it suitable image for CPU training ?

The dockerfile that comes in our repository is aimed at the users who want to run with a GPU. The base image is `nvidia/cuda:9.0-devel-ubuntu16.04` which has cuda9 in it. Also the instructions that we have in the `docs` folder asks you to use `nvidia-docker` which is a wrapper around docker for providing gpu support in the docker container. That said, there is nothing stopping you from running a CPU version of horovod in a docker file. You can modify our docker file in the following way: use a non cuda base docker image such as `ubuntu:18.04`, change the `tensorlfow-gpu` package to `tensorflow`, remove this flag `HOROVOD_GPU_ALLREDUCE=NCCL` and you should be good to go. 

Notice that you would not need to use `nvidia-docker` anymore and can probably use docker to run the non-gpu docker image.

> is root ssh connection required or can the images be run with user privileges?

You can configure docker to run without root access. That is purely based on how your hosts are set up.

**Comment by vtczk** [comment]
@abditag2 
Are these :
 libcudnn7=${CUDNN_VERSION} \
        libnccl2=${NCCL_VERSION} \
        libnccl-dev=${NCCL_VERSION} \
        libjpeg-dev \
        libpng-dev \

also required for CPU usage or can they be dropped as well ?

**Comment by alsrgv** [comment]
@vtczk, libcudnn7, libnccl2 and libnccl-dev can be dropped. It will fall back to CPU allreduce algorithm implemented in MPI, likely ring-allreduce.

**Comment by abhi278** [comment]
Environment:
1 Docker image : horovod/horovod:latest (checked out on 8 Apr 2019)
2. OS and version: Ubuntu 16.04 on 2 hosts

I am having a similar problem as @vtczk mentioned in the first comment. I am running the horovodrun command from docker container on host A on 2 machines A and B. Following is the command and its output:

`root@A:/examples# horovodrun --verbose -np 2 -H 10.110.43.22:1,10.110.43.72:1 -p 12351 python keras_mnist_advanced.py 
Filtering local host names.
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Launching horovodrun task function was not successful:
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/task_fn.py", line 68, in <module>
    _task_fn(index, driver_addresses, num_hosts, tmout, key)
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/task_fn.py", line 31, in _task_fn
    task.wait_for_initial_registration(tmout)
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/common/service/task_service.py", line 110, in wait_for_initial_registration
    timeout.check_time_out_for('Spark tasks to start')
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/common/util/timeout.py", line 34, in check_time_out_for
    'if your Spark resources are allocated on-demand.' % activity)
Exception: Timed out waiting for Spark tasks to start. Please check that you have enough resources to run all Horovod processes. Each Horovod process runs in a Spark task. You may need to increase the start_timeout parameter to a larger value if your Spark resources are allocated on-demand.

`
While it is `Waiting for the hosts to acknowledge.`, if I check `ps aux' within container on B, I see a
`/usr/bin/python -m horovod.run.task_fn ...` kind of process running.

I have checked that I am able to ssh from docker container on A to docker container on B and vice-versa.
I tried the same example on localhost of each machine inside docker container - it is working fine. But when I try to run from one machine to another, I am facing this issue.
Any suggestions?

**Comment by alsrgv** [comment]
@abhi278, could you reinstall Horovod from master and execute `horovodrun` with `--verbose 2`?

**Comment by mmisono** [comment]
@abhi278 
I had the same issue. In my case, as commented on [here](https://github.com/horovod/horovod/issues/403#issuecomment-418725026), using `mpirun` instead of `horovodrun` and specifying `NCCL_SOCKET_IFNAME` and `-mca btl_tcp_if_include` solve the problem.

**Comment by Sleepychord** [comment]
Another possible reason is the firewall, check `sudo ufw status` to make sure that host ip is not blocked. This is my case.
